B-11151 - Enhance the logging in the volume handler logic
hortonworks/cloudbreak pull request #10134
Opened 2021-02-24 14:44 UTC by gregito

Enhance the logging in the volume handler logic with some additional refactors that removes code duplications and a NPE weak code snippet

2021-02-25 08:33 UTC, bergerdenes requested changes

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
> +                        String message = String.format("%s [code: %d, message: %s, error: ]", VOLUME_DELETION_FAILED_BASE_MSG,
one string placeholder is missing

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
> +        LOGGER.info(String.format("%s, %s", VOLUME_DELETION_FAILED_BASE_MSG, e.getMessage()), e);
remove the comma from the format str

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +        LOGGER.debug(GoogleJsonResponseException.class.getSimpleName() + " contains the following " + GoogleJsonError.class.getSimpleName() + ": " +
String.format ?

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +                LOGGER.debug("Unable to uncover the error code of " + GoogleJsonResponseException.class.getSimpleName() + "! "
String.format?

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +                        + GoogleJsonError.class.getSimpleName() + ": " + jsonError != null ? jsonError.toString() : "null");
jsonError is already not null here

2021-02-25 08:33 UTC, bergerdenes commented on cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceCheckerTest.java
> +        assertTrue(expectedException.getMessage().contains(expectedExceptionMessage));
consider using AssertJ, it provides more usable assert fail messages (and has substring checks as well)

2021-02-25 16:47 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
> +                        String message = String.format("%s [code: %d, message: %s, error: ]", VOLUME_DELETION_FAILED_BASE_MSG,
added

2021-02-25 16:48 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/compute/GcpAttachedDiskResourceBuilder.java
> +        LOGGER.info(String.format("%s, %s", VOLUME_DELETION_FAILED_BASE_MSG, e.getMessage()), e);
removed

2021-02-25 16:51 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +                        + GoogleJsonError.class.getSimpleName() + ": " + jsonError != null ? jsonError.toString() : "null");
simplified

2021-02-25 16:52 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +                LOGGER.debug("Unable to uncover the error code of " + GoogleJsonResponseException.class.getSimpleName() + "! "
applied

2021-02-25 17:00 UTC, bergerdenes commented on cloud-gcp/src/main/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceChecker.java
> +        LOGGER.debug(GoogleJsonResponseException.class.getSimpleName() + " contains the following " + GoogleJsonError.class.getSimpleName() + ": " +
formatted

2021-02-25 17:04 UTC, bergerdenes commented on cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/service/checker/AbstractGcpBaseResourceCheckerTest.java
> +        assertTrue(expectedException.getMessage().contains(expectedExceptionMessage));
used AssertJ

2021-02-26 16:55 UTC, biharitomi approved these changes
LGTM

2021-02-27 08:14 UTC, bergerdenes approved these changes

2021-02-27 08:14 UTC, merged