CB-11322 Set freeipa instanceprofile using backup when telemetry is null
hortonworks/cloudbreak pull request #10147
Opened 2021-02-25 15:10 UTC by christmasferret

The original design was always taking instanceprofile from telemetry for freeipa so that user don't mistakenly set it in backup, because there is only one instanceprofile. Now We want to use the instanceprofile from backup if telemetry is null to include below test case.

See detailed description in the commit message.

2021-03-01 15:24 UTC, christmasferret commented
I've tested dpcli with and without telemetry. Both works. 

Below is the json without telemetry.

```
{
  "name": "yuwang-env2-6242",
  "description": "",
  "location": {
    "name": "us-west-2"
  },
  "authentication": {
    "publicKeyId": "eng-sdx-key"
  },
  "credentialName": "yuwang-local-newbackup-test",
  "backup": {
    "s3": {
      "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
    },
    "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/logs"
  },
  "regions": [
    "us-west-2"
  ],
  "securityAccess": {
    "cidr": "0.0.0.0/0"
  },
  "aws": {
    "s3guard": {
      "dynamoDbTableName": "yuwang-env2-6242"
    }
  },
  "idBrokerMappingSource": "MOCK",
  "network": {
    "subnetIds": [
      "subnet-003570df81d2fadcb",
      "subnet-0198053720e75605f",
      "subnet-0d0ae15bc71549212"
    ],
    "aws": {
      "vpcId": "vpc-0507f88d49efb8118"
    }
  },
  "tunnel": "DIRECT",
  "freeIpa": {
    "create": true,
    "instanceCountByGroup": 2
  },
  "tags": {
    "project": "freeipa-ha"
  }
}
```
in environment request, the telemetry is null and only backup is provided.

![Screenshot from 2021-02-26 16-25-25](https://user-images.githubusercontent.com/67844271/109518380-d0532300-7a6f-11eb-8bc8-5196cc777c1e.png)

The instance profile is attached to ec2 instance
![Screenshot from 2021-02-27 11-37-51](https://user-images.githubusercontent.com/67844271/109518443-dba64e80-7a6f-11eb-8013-c458994dc79a.png)
![Screenshot from 2021-02-27 11-38-24](https://user-images.githubusercontent.com/67844271/109518523-eeb91e80-7a6f-11eb-86cb-b2dc91abaf47.png)

The backup files in S3
![Screenshot from 2021-02-27 11-36-41](https://user-images.githubusercontent.com/67844271/109518536-f24ca580-7a6f-11eb-82c2-9ae5c7c9fd35.png)

2021-03-01 15:26 UTC, christmasferret commented
@lacikaaa 

Hi Mihaly, I've tested with the new dpcli. It works very well. Would you take a look? Thanks!

2021-03-01 16:13 UTC, lacikaaa approved these changes

2021-03-01 16:14 UTC, lacikaaa commented
I think what Jamison says is a good idea. It would be nice if you could add it to the PR. Or it can be a separate one. as you wish

2021-03-01 16:28 UTC, christmasferret commented
> I think what Jamison says is a good idea. It would be nice if you could add it to the PR. Or it can be a separate one. as you wish

Thanks! I will sync up with Jamison for this change.

2021-03-02 00:34 UTC, christmasferret commented
I made the code change that if backup and telemetry provide different instance profiles. It will throw an exception "User-provided logging %s and backup file %s system views are conflicting"

I made the following tests.
1) backup and telemetry provide different instance profiles. The provision will fail with exception 
"com.sequenceiq.environment.exception.FreeIpaOperationFailedException: FreeIpa creation operation failed. FreeIpa creation failed. Status: 'CREATE_FAILED' statusReason: 'User-provided logging S3CloudStorageV1Parameters{instanceProfile='arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role'} and backup file S3CloudStorageV1Parameters{instanceProfile='arn:aws:iam::308408126366:instance-profile/mow-dev-role'} system views are conflicting'"

![Screenshot from 2021-03-01 18-23-11](https://user-images.githubusercontent.com/67844271/109577828-e1298600-7abb-11eb-9f59-b1cdccf5b2d9.png)
![Screenshot from 2021-03-01 16-29-28](https://user-images.githubusercontent.com/67844271/109577835-e2f34980-7abb-11eb-85e7-e7fd71aa31c7.png)
```
{
  "name": "yuwang-env2-4537",
  "description": "",
  "location": {
    "name": "us-west-2"
  },
  "authentication": {
    "publicKeyId": "eng-sdx-key"
  },
  "credentialName": "yuwang-local-newbackup-test",
  "telemetry": {
    "logging": {
      "s3": {
        "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
      },
      "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/logs"
    }
  },
  "backup": {
    "s3": {
      "instanceProfile": "arn:aws:iam::308408126366:instance-profile/mow-dev-role"
    },
    "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/backup"
  },
  "regions": [
    "us-west-2"
  ],
  "securityAccess": {
    "cidr": "0.0.0.0/0"
  },
  "aws": {
    "s3guard": {
      "dynamoDbTableName": "yuwang-env2-4537"
    }
  },
  "idBrokerMappingSource": "MOCK",
  "network": {
    "subnetIds": [
      "subnet-003570df81d2fadcb",
      "subnet-0198053720e75605f",
      "subnet-0d0ae15bc71549212"
    ],
    "aws": {
      "vpcId": "vpc-0507f88d49efb8118"
    }
  },
  "tunnel": "DIRECT",
  "freeIpa": {
    "create": true,
    "instanceCountByGroup": 2
  },
  "tags": {
    "project": "freeipa-ha"
  }
}
```


2) backup and telemetry provide the same instance profiles. works as expected. 
```
{
  "name": "yuwang-env2-10705",
  "description": "",
  "location": {
    "name": "us-west-2"
  },
  "authentication": {
    "publicKeyId": "eng-sdx-key"
  },
  "credentialName": "yuwang-local-newbackup-test",
  "telemetry": {
    "logging": {
      "s3": {
        "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
      },
      "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/logs"
    }
  },
  "backup": {
    "s3": {
      "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
    },
    "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/backup"
  },
  "regions": [
    "us-west-2"
  ],
  "securityAccess": {
    "cidr": "0.0.0.0/0"
  },
  "aws": {
    "s3guard": {
      "dynamoDbTableName": "yuwang-env2-10705"
    }
  },
  "idBrokerMappingSource": "MOCK",
  "network": {
    "subnetIds": [
      "subnet-003570df81d2fadcb",
      "subnet-0198053720e75605f",
      "subnet-0d0ae15bc71549212"
    ],
    "aws": {
      "vpcId": "vpc-0507f88d49efb8118"
    }
  },
  "tunnel": "DIRECT",
  "freeIpa": {
    "create": true,
    "instanceCountByGroup": 2
  },
  "tags": {
    "project": "freeipa-ha"
  }
}

```
3) only telemetry provides an instance profile. works as expected. 
```
{
  "name": "yuwang-env2-29712",
  "description": "",
  "location": {
    "name": "us-west-2"
  },
  "authentication": {
    "publicKeyId": "eng-sdx-key"
  },
  "credentialName": "yuwang-local-newbackup-test",
  "telemetry": {
    "logging": {
      "s3": {
        "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
      },
      "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/logs"
    }
  },
  "regions": [
    "us-west-2"
  ],
  "securityAccess": {
    "cidr": "0.0.0.0/0"
  },
  "aws": {
    "s3guard": {
      "dynamoDbTableName": "yuwang-env2-29712"
    }
  },
  "idBrokerMappingSource": "MOCK",
  "network": {
    "subnetIds": [
      "subnet-003570df81d2fadcb",
      "subnet-0198053720e75605f",
      "subnet-0d0ae15bc71549212"
    ],
    "aws": {
      "vpcId": "vpc-0507f88d49efb8118"
    }
  },
  "tunnel": "DIRECT",
  "freeIpa": {
    "create": true,
    "instanceCountByGroup": 2
  },
  "tags": {
    "project": "freeipa-ha"
  }
}
```

4) only backup provides an instance profile. works as expected. 
```
{
  "name": "yuwang-env2-19180",
  "description": "",
  "location": {
    "name": "us-west-2"
  },
  "authentication": {
    "publicKeyId": "eng-sdx-key"
  },
  "credentialName": "yuwang-local-newbackup-test",
  "backup": {
    "s3": {
      "instanceProfile": "arn:aws:iam::308408126366:instance-profile/yuwang-mow-dev-role"
    },
    "storageLocation": "s3a://eng-sdx-daily-datalake/yuwang-env2/backup"
  },
  "regions": [
    "us-west-2"
  ],
  "securityAccess": {
    "cidr": "0.0.0.0/0"
  },
  "aws": {
    "s3guard": {
      "dynamoDbTableName": "yuwang-env2-19180"
    }
  },
  "idBrokerMappingSource": "MOCK",
  "network": {
    "subnetIds": [
      "subnet-003570df81d2fadcb",
      "subnet-0198053720e75605f",
      "subnet-0d0ae15bc71549212"
    ],
    "aws": {
      "vpcId": "vpc-0507f88d49efb8118"
    }
  },
  "tunnel": "DIRECT",
  "freeIpa": {
    "create": true,
    "instanceCountByGroup": 2
  },
  "tags": {
    "project": "freeipa-ha"
  }
}
```



![Screenshot from 2021-03-01 18-32-38](https://user-images.githubusercontent.com/67844271/109578381-b2f87600-7abc-11eb-9eaf-878a7315c1dd.png)

2021-03-02 11:01 UTC, lacikaaa requested changes

2021-03-02 22:13 UTC, christmasferret commented on freeipa/src/main/java/com/sequenceiq/freeipa/converter/cloud/StackToCloudStackConverter.java
> +                throw new RuntimeException(String.format("User-provided logging %s and backup %s file system views are conflicting",
- replaced RuntimeException with BadRequestException. 
- fixed log message for aws instance profile, azure managed identity and gcp service account email.  
- cover the cases with unit tests now. 

@lacikaaa @jamisonbennett

2021-03-03 09:16 UTC, lacikaaa approved these changes
thanks for the changes

2021-03-03 09:16 UTC, merged