CB-11419 Fix waiting edge cases in integration tests
hortonworks/cloudbreak pull request #10203
Opened 2021-03-08 10:59 UTC by Bajzathd

While WaitService waits for a certain criteria to be met (depedning on StatusChecker implementation), it should refresh its data only once per round. This way we can not encounter an edge case where a check runs on different data then the check before it, causing changes to not handled properly.

See detailed description in the commit message.

2021-03-08 17:09 UTC, aszegedi approved these changes

2021-03-08 17:10 UTC, aszegedi approved these changes

2021-03-09 16:22 UTC, aszegedi approved these changes

2021-03-10 08:32 UTC, topolyai5 requested changes

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitFailedChecker.java
> +            failed = false;
why do you set it to false?

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
>                  LOGGER.debug("Exception occurred during waiting: {}", ex.getMessage(), ex);
could you please change the error message to `Exception occurred during refresh`

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitService.java
> +            success = statusChecker.checkStatus(t);
you can do this after the failure check

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitTerminationChecker.java
> +            deleted = true;
maybe it better if store this in the wait object

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitFailedChecker.java
> +            failed = true;
is it failed or deleted? maybe it better if store in the wait object

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/WaitTerminationChecker.java
> +        return deleted ? waitObject.getDesiredStatuses() : waitObject.actualStatuses();
what will happen in the test if this method gives back the desires statuses? In the catch clause, we used the `DELETE_COMPLETED`

2021-03-10 08:32 UTC, topolyai5 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/wait/service/instance/InstanceFailedChecker.java
> +            failed = true;
is it failed or deleted?

2021-03-17 12:18 UTC, topolyai5 approved these changes

2021-03-17 12:18 UTC, merged