CB-11568 We use the same boilerplate code in every freeipa creation. …
hortonworks/cloudbreak pull request #10253
Opened 2021-03-12 13:21 UTC by topolyai5

…Easier if we do this in valid() method and we set the image catalog URL at the mock provider, and set null at the other providers

See detailed description in the commit message.

2021-03-12 14:46 UTC, aszegedi requested changes
Could you run all the tests on this with the `aws_e2e_test` and `real_ums_test` labels that has recently been included?
There are related tests for `authorization` suite and the E2E is going to be affected also.

2021-03-12 19:35 UTC, topolyai5 commented
retest pls

2021-03-16 08:29 UTC, topolyai5 commented
retest this please

2021-03-17 09:50 UTC, aszegedi approved these changes

2021-03-17 09:51 UTC, merged