CB-9504 Replace FreeIPA error page
hortonworks/cloudbreak pull request #10269
Opened 2021-03-16 08:33 UTC by daszabo

See detailed description in the commit message.

2021-03-17 08:34 UTC, pdarvasi approved these changes

2021-03-17 11:35 UTC, lacikaaa requested changes
replicas are missing this fix

2021-03-17 11:35 UTC, lacikaaa commented on freeipa/src/main/resources/freeipa-salt/salt/freeipa/patch-error-page.sls
> +      - name: ipa
I think restarting `pki-tomcatd@pki-tomcat.service` should be enough

2021-03-17 11:35 UTC, lacikaaa commented on freeipa/src/main/resources/freeipa-salt/salt/freeipa/patch-error-page.sls
> +                <location>/error.jsp</location>
is this page exists?

2021-04-07 07:27 UTC, pdarvasi commented
@daszabo could you finish the testing or would you need some help? Thanks

2021-04-13 09:40 UTC, daszabo commented
Tested with FreeIPA HA, it works properly. Also made sure multiple runs yields the same result.

2021-04-13 09:59 UTC, lacikaaa approved these changes

2021-04-13 09:59 UTC, merged