CB-11170 EDH integration to measure how many customers used Data Hub repair
hortonworks/cloudbreak pull request #10277
Opened 2021-03-16 17:48 UTC by schfeca75

CB-11170 EDH integration to measure how many customers used Data Hub repair

2021-03-19 17:52 UTC, akanto approved these changes

2021-03-22 11:02 UTC, nadamdb requested changes
Besides the display names LGTM

2021-03-22 11:02 UTC, nadamdb commented on flow/src/main/java/com/sequenceiq/flow/core/chain/finalize/config/FlowChainFinalizeFlowConfig.java
> +        return "Hello world";
Display name should be more descriptive

2021-03-22 11:02 UTC, nadamdb commented on flow/src/main/java/com/sequenceiq/flow/core/chain/init/config/FlowChainInitFlowConfig.java
> +        return "Hello world";
Same here

2021-03-22 15:01 UTC, schfeca75 commented
Retest this please

2021-03-22 15:20 UTC, nadamdb approved these changes

2021-03-22 15:20 UTC, merged