CB-12065: Fix FreeIPA HA repair to update cached kerberos config
hortonworks/cloudbreak pull request #10503
Opened 2021-04-19 16:10 UTC by jamisonbennett

Fix FreeIPA HA repair so that the cached kerberos configuration is
updated. Specifically the DNS nameservers were stale which caused
DataLakes and DataHubs to have DNS break after all of the original
FreeIPA servers have been repaired.

This was tested by validating the cached kerberos configuration is
updated during downscale and upscale operations.

See detailed description in the commit message.

2021-04-19 19:11 UTC, christmasferret approved these changes
LGTM

2021-04-20 08:50 UTC, lacikaaa requested changes

2021-04-20 08:50 UTC, lacikaaa commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/config/KerberosConfigUpdateService.java
> +        KerberosConfig kerberosConfig = kerberosConfigService.get(environmentCrn);
this won't return all. you have to use `kerberosConfigRepository.findByAccountIdAndEnvironmentCrnAndArchivedIsFalse` on repository level, and this is not exposed on service level right now

2021-04-20 19:05 UTC, lacikaaa approved these changes

2021-04-20 19:08 UTC, lacikaaa commented
this LGTM. but there are old LDAP configs, for old FreeIPA installation where we don't have the CNAME. see: `LdapConfigRegisterService#addServerHost`
we might need to handle those if there is any. we should check that before making any changes

2021-04-20 19:09 UTC, merged

2021-04-20 19:18 UTC, jamisonbennett commented
@lacikaaa Thanks for mentioning this. `LdapConfigRegisterService#addServerHost` was supported from 2.20 and later. The repair flow only is possible for HA configurations which are much later (2.31?). So this shouldn't be a problem because we can't repair something that old anyway.

2021-04-21 07:52 UTC, lacikaaa commented
@jamisonbennett thanks for the clarification
what about upscale, when we are migrating from single to HA in the foreseeable future?