CB-13067:Add Entitlement for AWS CMK cli
hortonworks/cloudbreak pull request #10912
Opened 2021-06-15 06:30 UTC by satyabollineni

2021-06-15 08:13 UTC, satyabollineni commented
Associated Thunderhead PR: https://github.infra.cloudera.com/thunderhead/thunderhead/pull/5052

2021-06-15 08:57 UTC, juhi-09 requested changes

2021-06-15 08:57 UTC, juhi-09 commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
> +        return  isEntitlementRegistered(accountId, CDP_CB_AWS_DISK_ENCRYPTION_WITH_CMK); }
Please fix the spacing (2 spaces after `return`) and move closing brace on new line.

2021-06-15 09:50 UTC, lajosrodek commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
>  import static com.sequenceiq.cloudbreak.auth.altus.model.Entitlement.CDP_CB_DATABASE_WIRE_ENCRYPTION;
Wrong import order

2021-06-15 09:50 UTC, lajosrodek commented on mock-thunderhead/src/main/java/com/sequenceiq/thunderhead/grpc/service/auth/MockUserManagementService.java
>  import static com.sequenceiq.cloudbreak.auth.altus.model.Entitlement.OJDBC_TOKEN_DH;
Wrong import order. (See other static imports as well; the whole `Entitlement.*` part seems to be messed up.)

2021-06-16 06:22 UTC, juhi-09 commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
> +        return  isEntitlementRegistered(accountId, CDP_CB_AWS_DISK_ENCRYPTION_WITH_CMK); }
LGTM.

2021-06-16 06:23 UTC, juhi-09 approved these changes

2021-06-16 19:21 UTC, lajosrodek approved these changes
Thanks, LGTM

2021-06-21 06:11 UTC, merged