CB-12755: Validating custom template to contains all only allowed services for upgrade.
hortonworks/cloudbreak pull request #10947
Opened 2021-06-21 20:48 UTC by tiborpopovics

2021-06-22 09:09 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/BlueprintUpgradeOptionValidator.java
> +        return !blueprint.getStatus().isDefault() && customTemplateUpgradeValidator.isValid(blueprint);
the first half of this seems to be always true

2021-06-22 09:15 UTC, lacikaaa requested changes
could you rephrase your commit message and maybe add some more details?
`contains all only allowed services for upgrade` is a bit ambiguous

2021-06-23 07:05 UTC, lacikaaa approved these changes

2021-06-23 07:33 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CustomTemplateUpgradeValidator.java
> +            return permittedServicesForUpgrade.containsAll(services);
minor: we should log the result of the validation, too

2021-06-23 07:33 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/BlueprintUpgradeOptionValidator.java
> +        return isDefaultBlueprint(blueprint) ? isEnabledForDefaultBlueprint(lockComponents, blueprint) : isEnabledForCustomBlueprint(blueprint);
this is a follow-up question, but don't we want to indicate why the blueprint is not valid for an upgrade to the end-user? cc: @keyki

2021-06-23 11:32 UTC, keyki commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CustomTemplateUpgradeValidator.java
> +    @Value("${cb.upgrade.permittedServicesForUpgrade:}")
Can you please remove the `:`

2021-06-23 11:33 UTC, keyki commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/CustomTemplateUpgradeValidator.java
> +    private Set<String> getServiceFromBlueprint(Blueprint blueprint) {
getService`s`

2021-06-23 11:37 UTC, keyki commented on core/src/main/resources/application.yml
> +    permittedServicesForUpgrade: DAS,HDFS,HIVE,HIVE_ON_TEZ,HUE,KNOX,LIVY,LIVY_FOR_SPARK3,OOZIE,QUEUEMANAGER,SPARK3_ON_YARN,SPARK_ON_YARN,SQOOP_CLIENT,TEZ,YARN,ZEPPELIN,ZOOKEEPER
For better visibility, can we separate the services with new line?

2021-06-25 09:46 UTC, merged