CB-12971 Make freeipa backup work for GCP environment with log bucket…
hortonworks/cloudbreak pull request #10962
Opened 2021-06-23 06:03 UTC by cegganesh84

… path root location already exists in operating system

1. To avoid storage.objects.list permission for logger we were syncing backups to the bucket instead of the object by staging it in a similar folder structure locally.
2. This is a dangerous idea to begin with because if the root location already exists in operating system then it will sync the entire OS system content.
3. In this change we avoid this mistake by checking if the folder already exists and do a cp instead of mv.
4. But this needs a new permission for logger service account which needs to be documented.
5. We keep the old behaviour as is in the normal scenarios for backward compatibility purposes.

2021-06-23 07:24 UTC, lacikaaa requested changes
there is already a storage validation in FMS, like a preflight check, before we start installing and configuring the FreeIPA. I think it should validate if the backup script has to use the new logic and it has the necessary permissions.
Also please file a documentation jira for this new permission and when it is necessary. thanks

2021-06-23 21:12 UTC, cegganesh84 commented
> I think it should validate if the backup script has to use the new logic and it has the necessary permissions.

Agreed. One trouble in doing that. In the bash script, it is easy to check for preexisting folders. If we have to do it outside the VM then we need to know what folders are preexisting apriori based on the image baking process it could differ (our centos image vs customer custom rhel image for example). I believe it can go in as an additional enhancement.

Yes documentation is part of this jira itself.

2021-06-24 10:33 UTC, lacikaaa commented
> If we have to do it outside the VM then we need to know what folders are preexisting apriori based on the image baking process it could differ

This validation is run when the VM is already up, but before we are installing and configuring freeipa. It would still take a few minutes to fail, and it won't fail in request time but at least the customer won't have to wait until the freeipa is installed and configured.
see: https://github.com/hortonworks/cloudbreak/blob/master/freeipa/src/main/java/com/sequenceiq/freeipa/flow/freeipa/provision/action/FreeIpaProvisionActions.java#L100-L115

2021-06-24 13:50 UTC, jamisonbennett commented
The cloud storage validation fails after about 5 minutes if there are not permissions. But it is a much faster failure message than waiting 35 minutes for the install to fail due to permissions issues.

2021-06-25 00:36 UTC, cegganesh84 commented
Ah, I see where the check is https://github.com/hortonworks/cloudbreak/commit/e4fdf4eae35e1e9a83673ed926154d18b15f1919, I confused myself by thinking it is along the lines of DL IAM storage permissions check.

2021-06-26 01:12 UTC, cegganesh84 commented
All I can tell is when I execute the backup validation shell script it works, that is fails for invalid permission and succeeds for correct permission. But the validation is not kicking in after 2.44 release. No "Completed validating cloud storage" after 21st June https://logs-dev-7x.sre.cloudera.com/_plugin/kibana/goto/906378e35df478da5f706a4580e3bef0?security_tenant=global

2021-06-28 06:29 UTC, lacikaaa commented
does it mean that the current validation logic covers the new use case too?

2021-07-06 23:40 UTC, cegganesh84 commented
@lacikaaa yes, it should work automatically after this issue is fixed CB-13309

2021-07-09 12:51 UTC, lacikaaa approved these changes

2021-07-09 12:51 UTC, merged