CB-11740: Integrate with Telemetry solution.
hortonworks/cloudbreak pull request #10968
Opened 2021-06-24 11:30 UTC by juhi-09

CB-11740: Integrate with Telemetry solution
Adding a new property to CDPEnvironmentAzureDetails, bool resourceEncryptionEnabled, this is set only when encryptionKeyUrl is present.
As encryptionKeyUrl is present only when "CDP_CB_AZURE_DISK_SSE_WITH_CMK" is enabled and encryptionKey is provided during environment creation, checking its presence is sufficient to know if user is using "Azure SSE with CMK".

**When encryptionKeyUrl was provided :**
<img width="482" alt="Screenshot 2021-06-24 at 4 42 21 PM" src="https://user-images.githubusercontent.com/32215750/123255540-9968b780-d50d-11eb-9b8a-e2c01e13d21d.png">

**When encryptionKeyUrl was NOT provided :**
![Uploading Screenshot 2021-06-24 at 4.53.03 PM.png…]()

2021-06-25 09:06 UTC, nadamdb requested changes
Please add the descriptive comment in usage.proto, otherwise LGTM

2021-06-28 12:54 UTC, lajosrodek approved these changes
I agree with Adam's comments, please fix them. Otherwise looks okay.

2021-06-28 12:54 UTC, lajosrodek commented on structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/EnvironmentDetailsToCDPEnvironmentDetailsConverter.java
> +                if (encryptionKeyUrl.isPresent()) {
+1

2021-06-28 12:54 UTC, lajosrodek commented on usage-collection/src/main/proto/usage.proto
> +  bool resourceEncryptionEnabled = 2;
+1

2021-06-29 10:17 UTC, lajosrodek commented on usage-collection/src/main/proto/usage.proto
> +  // True if user provides encryption key url to encrypt Azure disk with CMK
Nit:

- url -> URL
- disk -> managed disks

2021-06-29 12:58 UTC, nadamdb approved these changes

2021-06-30 08:22 UTC, lajosrodek commented
As per Bryan's comment in the [thunderhead PR](https://github.infra.cloudera.com/thunderhead/thunderhead/pull/5132):
> While you are at it would you mind also adding a comment above the `singleResourceGroup` field?

So one more change needed, please. 😄

2021-07-07 04:20 UTC, merged