CB-13493 Fix Datahub HA repair, remove primary gateway change
hortonworks/cloudbreak pull request #11152
Opened 2021-07-26 07:22 UTC by lacikaaa

Primary gateway change messes up the salt roles and PGW on CB side. As CM is non HA, PGW doesn't make any sense, similarly to DL.

See detailed description in the commit message.

2021-07-28 14:11 UTC, pdarvasi requested changes

2021-07-28 15:13 UTC, lacikaaa commented on cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsDownscaleService.java
> +            List<String> existingInstances = instances.stream().map(com.amazonaws.services.ec2.model.Instance::getInstanceId).collect(Collectors.toList());
right

2021-07-28 15:19 UTC, lacikaaa commented on core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
> +    public List<InstanceMetaData> getReachableGatewayInstanceMetadata() {
no, it's not in scope for this PR

2021-07-29 05:52 UTC, sodre90 approved these changes

2021-07-29 05:54 UTC, merged

2021-07-29 10:00 UTC, pdarvasi commented
@sodre90 next time if I've made the effort to do a review, pls wait for my approval before you'd merge, thank you!

2021-07-29 10:01 UTC, pdarvasi commented on core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
> +    public List<InstanceMetaData> getReachableGatewayInstanceMetadata() {
ok, are you confident if we need both methods?

2021-07-30 07:53 UTC, lacikaaa commented on core-model/src/main/java/com/sequenceiq/cloudbreak/domain/stack/Stack.java
> +    public List<InstanceMetaData> getReachableGatewayInstanceMetadata() {
yes, I'm pretty sure sometimes we need all GWs which are not terminated, while when creating connectors/clients it doesn't make sense to try to reach a GW which is stopped