CB-13422 adding policy validation endpoint for experiences. This can …
hortonworks/cloudbreak pull request #11190
Opened 2021-08-02 18:37 UTC by doktoric

…be only called with internal actor yeet.

See detailed description in the commit message.

2021-08-17 11:23 UTC, bergerdenes requested changes

2021-08-17 11:23 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/credential/service/ServiceProviderCredentialAdapter.java
> +            String message = FAILED_POLICY_VERIFICATION_MESSAGE;
move into the `if` below (smallest scope visibility principle)

2021-08-18 05:37 UTC, doktoric commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsCredentialConnector.java
> +        } else if (isEmpty(accessKey) || isEmpty(secretKey)) {
on the public api we do not but keybased still works

2021-08-18 06:41 UTC, bergerdenes approved these changes

2021-08-18 06:41 UTC, merged