DISTX-679: Turn off hive.privilege.synchronizer by default in templates
hortonworks/cloudbreak pull request #11211
Opened 2021-08-05 15:18 UTC by juhi-09

This change turns off "hive.privilege.synchronizer" by default. This property is used mainly for information schema population which users are not using actively. This can be enabled by users, in case they want to use information_schema.

The attached screenshot mentions the "hive.privilege.synchronizer" property set as false.
<img width="1331" alt="Screenshot 2021-08-05 at 8 47 56 PM" src="https://user-images.githubusercontent.com/32215750/128375465-56f384e0-ea50-45a2-8b58-7abfb68122ae.png">

2021-08-05 16:39 UTC, amitagarwal06 commented
@rbalamohan Juhi is setting this in a safety valve of Hive service. But should this config go to HMS service or Hive service?

2021-08-07 01:01 UTC, rbalamohan commented
Setting is for HMS service trying to communicate with DB in native SQL mode.



On Thu, 5 Aug, 2021, 22:09 amitagarwal06, ***@***.***> wrote:

> @rbalamohan <https://github.com/rbalamohan> Juhi is setting this in a
> safety valve of Hive service. But should this config go to HMS service or
> Hive service?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hortonworks/cloudbreak/pull/11211#issuecomment-893602669>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4ZXMLQHUXG5XBIGYBCN5DT3K5C7ANCNFSM5BUCIZMQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-09 19:16 UTC, sidseth commented
@juhi-09  - could you please change this to be HMS specific, similar to the directsql change.

2021-08-10 07:32 UTC, rbalamohan commented
I guess my comment got mixed up for direct SQL. 

Priv sync should be in HS2 setting. Sorry about the confusion.

2021-08-17 05:02 UTC, juhi-09 commented
> Priv sync should be in HS2 setting. 

@rbalamohan I have updated the property to be present in config of `hive-HIVESERVER2-BASE`, however it is not visible in UI. Please review.

2021-08-18 09:58 UTC, amitagarwal06 requested changes
@juhi-09 Pls make the changes as suggested in the review and re-submit.

2021-08-18 09:58 UTC, amitagarwal06 commented on core/src/main/resources/defaults/blueprints/7.2.11/cdp-data-engineering-ha.bp
> +                "name": "hive.privilege.synchronizer",
Setting it this way is not correct. Its not applied to HS2. If you open hive-site.xml from UI, you wont see it getting set anywhere. You wont see it getting set via beeline either

0: jdbc:hive2://perf-test2-master0.perf-aws.x> set hive.privilege.synchronizer;
+-----------------------------------+
|                set                |
+-----------------------------------+
| hive.privilege.synchronizer=true  |
+-----------------------------------+

Right way to set this is as you did it first time. Add this property to hive_service_config_safety_valve

2021-08-20 01:28 UTC, cegganesh84 commented
@juhi-09 Please pull in the recent changes to these files, otherwise, you will not be able to merge the changes.

2021-08-20 05:11 UTC, amitagarwal06 approved these changes
Have approved it. Not sure of whether failing swagger tests matter.

2021-08-20 16:15 UTC, cegganesh84 commented
I guess it will go away if the code is rebased with the latest changes in the master.

2021-08-23 07:11 UTC, merged