CB-11741: Nigthly e2e Azure tests should use encryption.
hortonworks/cloudbreak pull request #11308
Opened 2021-08-26 09:35 UTC by juhi-09

CB-11741: Nigthly e2e Azure tests should use encryption
  
This PR adds the tests for Azure cloud SSE with CMK feature. 
Encryption key **https://cloud-jenkins-secrets.vault.azure.net/keys/key-azure-cmk-e2e/c1a1df3097f441b4a10cfcb7c8a3bcd9** is created in **cloud-daily** resource group, which needs to have access policy configured for the credential app used to create test environments. For details, Please refer - [Azure cmk permissions](https://docs.google.com/document/d/1DTIB2Wb-CX4HBFOjyWGnvHNteOwTx3TL3608LFUDxEc/edit#heading=h.s0bspwrofjfh) and
[Access policies required](https://docs.google.com/document/d/1DTIB2Wb-CX4HBFOjyWGnvHNteOwTx3TL3608LFUDxEc/edit#heading=h.fkbtsx9frdiu)

2021-09-21 11:42 UTC, doktoric commented
@juhi-09 we need to setup the jenkins side of the story. Do you need help ?

2021-09-22 04:38 UTC, juhi-09 commented
> @juhi-09 we need to setup the jenkins side of the story. Do you need help ?

@doktoric We would need jenkins to setup the EnvironmentTestDto, right? Yes, I would need some guidance on it.

2021-11-22 16:01 UTC, afarsang requested changes

2021-11-30 15:27 UTC, juhi-09 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/environment/EnvironmentWithCustomerManagedKeyTests.java
> +        deleteResourceGroupCreatedForEnvironment("azure-test-des-rg");
Updated the tests, to delete the resource group as part of afterMethod.

2021-12-06 09:13 UTC, afarsang approved these changes

2021-12-07 08:21 UTC, horadla23 commented
> > > @juhi-09 we need to setup the jenkins side of the story. Do you need help ?
> > 
> > 
> > @doktoric We would need jenkins to setup the EnvironmentTestDto, right? Yes, I would need some guidance on it.
> 
> lets schedule a meeting for this

@juhi-09 Have you discussed this? Have you executed this e2e test locally?

2021-12-07 08:42 UTC, juhi-09 commented
> > > > @juhi-09 we need to setup the jenkins side of the story. Do you need help ?
> > > 
> > > 
> > > @doktoric We would need jenkins to setup the EnvironmentTestDto, right? Yes, I would need some guidance on it.
> > 
> > 
> > lets schedule a meeting for this
> 
> @juhi-09 Have you discussed this? Have you executed this e2e test locally?

@horadla23 Yes Adam, this is covered. We can merge the PR. e2e tests are executed locally and jenkins setup is done to create a encryption key -  https://cloud-jenkins-secrets.vault.azure.net/keys/key-azure-cmk-e2e/c1a1df3097f441b4a10cfcb7c8a3bcd9 is created in cloud-daily resource group

2021-12-07 09:28 UTC, merged

2021-12-07 09:29 UTC, lnardai commented
FYI: If the test fails for some reason in the next 1 week, we are going to disable it and mark it as unstable.