CB-14021 - fix polling upon successful experience deletion
hortonworks/cloudbreak pull request #11352
Opened 2021-09-08 11:50 UTC by gregito

2021-09-10 14:52 UTC, doktoric approved these changes

2021-09-12 20:48 UTC, bergerdenes requested changes

2021-09-12 20:48 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentExperienceDto.java
> +        public EnvironmentExperienceDto fromEnvironment(Environment environment) {
is this function needed?

2021-09-12 20:48 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/EnvironmentExperienceDeletionAction.java
> +            }
test?

2021-09-15 07:59 UTC, gregito commented on environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentExperienceDto.java
> +        public EnvironmentExperienceDto fromEnvironment(Environment environment) {
now it is. forgot to call :)

2021-09-15 08:00 UTC, gregito commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/deletion/handler/experience/EnvironmentExperienceDeletionAction.java
> +            }
done. pls check if it is suffucient

2021-09-15 09:18 UTC, bergerdenes approved these changes

2021-09-16 13:20 UTC, merged