CB-14234: Remove unnecessary components from the database in the begining of the upgrade
hortonworks/cloudbreak pull request #11475
Opened 2021-09-27 13:51 UTC by tiborpopovics

2021-09-28 07:06 UTC, keyki approved these changes
Tested, but haven't checked the code.

2021-09-28 08:43 UTC, gergopapi2 requested changes

2021-09-28 08:43 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdaterTest.java
> +        verify(clusterComponentConfigProvider).deleteClusterComponents(any());
Here testing that the correct component is deleted could be useful

2021-09-28 08:43 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdaterTest.java
> +        verify(clusterComponentConfigProvider).deleteClusterComponents(any());
It could make sense to check that the right ClusterComponent is removed.

2021-09-28 10:38 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ClusterComponentUpdater.java
> +            LOGGER.debug("There is no cluster component to delete.");
nit: to be deleted

2021-09-29 06:27 UTC, gergopapi2 approved these changes

2021-09-29 07:57 UTC, keyki commented
@tiborpopovics can you please extend the commit message with more details about why this change is needed and how does it fix the problem?

2021-09-30 09:05 UTC, lnardai approved these changes
LGTM!

2021-09-30 09:05 UTC, merged