CB-14701: Remove unnecessary parcels from the database and the cluster before starting to install services to the new hosts during upscale.
hortonworks/cloudbreak pull request #11705
Opened 2021-11-03 14:58 UTC by tiborpopovics

2021-11-03 15:29 UTC, sodre90 approved these changes

2021-11-04 07:23 UTC, gergopapi2 requested changes
Just annoying, nit-picking comments.

2021-11-04 07:23 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
> +    public Blueprint getBlueprint() {
can be private

2021-11-04 07:23 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
> +    public void mockManifestResponse(String parcelUrl, Response.Status status, Optional<String> manifest) {
can be private

2021-11-04 07:23 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
> +    public static String getManifestJson(String... componentNames) {
can be private

2021-11-04 07:23 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
> +    public void test(String description, String parcelUrl, Response.Status status, String serviceNameInTheBlueprint, Optional<String> manifest,
Nit: since junit5 is used, it is not necessary to use public, can be package private.

2021-11-04 07:23 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterServiceTest.java
> +    public static Collection<Object[]> data() {
Nit: since junit5 is used, it can be package private

2021-11-04 10:10 UTC, gergopapi2 approved these changes

2021-11-04 11:10 UTC, pdarvasi requested changes

2021-11-04 11:10 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/cluster/ClusterUpscaleService.java
> +        parcelService.removeUnusedParcelComponents(stack);
is it ok, if we proceed here even if there are "failed" parcel removals?

2021-11-04 11:10 UTC, pdarvasi commented on core/src/test/java/com/sequenceiq/cloudbreak/service/parcel/ParcelServiceTest.java
> +        PowerMockito.when(clusterApi.removeUnusedParcels(any())).thenReturn(new ParcelOperationStatus());
why do you need PowerMockito here?

2021-11-04 15:47 UTC, pdarvasi approved these changes

2021-11-08 10:42 UTC, keyki approved these changes

2021-11-08 14:40 UTC, merged