CB-14825 Increase wait timeouts for SDX backup and restore
hortonworks/cloudbreak pull request #11800
Opened 2021-11-23 13:06 UTC by aszegedi

Our [MOW-Dev API E2E projects](http://ci-cloudbreak.eng.hortonworks.com/job/mow-dev-e2e/) are failing, because of [CB-14825 Datalake backup flow has been finalized with failed status](https://jira.cloudera.com/browse/CB-14825).

While this issue is going to be investigated then fix, I'm increased the CM service wait timeout as a possible workaround. We had similar solution previously at [CB-13322 Data Lake database backup request failed: 409, Could not connect to Solr OR ATLAS_ENTITY_AUDIT_EVENTS_TABLE: HBase failure: Failed to take snapshot](https://jira.cloudera.com/browse/CB-13322)

2021-11-24 14:28 UTC, horadla23 requested changes
all of these actions have the same sleep method? Can you refactor that into an util class, or something, and use it everywhere?

2021-11-29 10:02 UTC, lnardai commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/action/sdx/SdxBackupAction.java
> +        sleep(3, sdxName);
Also code might be more readable with passing in a TimeUnit or updatating the refactored method name to `sleepForMinutes(...)`

2021-11-29 10:02 UTC, lnardai requested changes
Please do the sleep method refactors.

2021-12-01 15:39 UTC, horadla23 approved these changes

2021-12-09 13:29 UTC, lnardai approved these changes

2021-12-09 13:29 UTC, merged