CB-13472 - Validate for stopped/unreachable FreeIPA
hortonworks/cloudbreak pull request #11835
Opened 2021-11-30 22:14 UTC by pdarvasi

This commit
- refactors FreeIpaService to use `freeipa.getAvailabilityStatus().isAvailable()` instead of former status which is not indicative in all cases.

2021-12-06 08:56 UTC, horadla23 requested changes
please use only one if statement here

2021-12-06 08:56 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaService.java
>              }
please use 1 if statement here

2021-12-06 10:55 UTC, horadla23 approved these changes

2021-12-06 10:55 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaService.java
>              }
nvm, @gergopapi2 helped me to understand why there are 2 if statements.. :)

2021-12-06 11:28 UTC, gergopapi2 requested changes

2021-12-06 11:28 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaServiceTest.java
> +    void testCheckFreeipaRunningWhenFreeIpaStoppedThenReturnsFalse() {
nit: here one could test all not available Statuses that freeipa availability checker returns false for all of them.

2021-12-06 12:49 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/service/freeipa/FreeipaService.java
> +    @Retryable(value = CloudbreakServiceException.class, maxAttempts = 3, backoff = @Backoff(delay = 200))
Yes, indeed, it won't cause any extra delay if called in request time from e.g SDX service.

2021-12-07 11:59 UTC, gergopapi2 approved these changes

2021-12-07 12:13 UTC, merged