CB-15407 Cannot attach disk during the retry if the disk attachment f…
hortonworks/cloudbreak pull request #11899
Opened 2021-12-08 14:32 UTC by topolyai5

…ailed in the previous run. The AZ missed in the Resource to CloudResource converter.

See detailed description in the commit message.

2021-12-09 14:33 UTC, doktoric approved these changes

2021-12-10 15:55 UTC, sodre90 requested changes

2021-12-10 15:55 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +    private Optional<CloudResource> fetchCloudResourceFromDBIfAvailable(long privateId, AuthenticatedContext auth, Group group,
Can you please unit test this?

2021-12-10 15:58 UTC, sodre90 commented
Otherwise it looks good for me.

2021-12-13 10:19 UTC, biharitomi approved these changes

2021-12-14 07:24 UTC, topolyai5 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +    private Optional<CloudResource> fetchCloudResourceFromDBIfAvailable(long privateId, AuthenticatedContext auth, Group group,
done

2021-12-17 07:44 UTC, sodre90 approved these changes

2021-12-17 07:45 UTC, merged