CB-13498 Consume new CM api to bulk decommission hosts (hosts/removeH…
hortonworks/cloudbreak pull request #11907
Opened 2021-12-09 12:04 UTC by lturcsanyi

…ostsFromCluster).

The new API is available from 7.2.13 (CM version 7.5.3), before that it will use the old approach.

See detailed description in the commit message.

2021-12-09 14:44 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/reactor/DecommissionHandler.java
> +                return singleHostsRemoval(request, hostNames, forced, stack, clusterDecomissionService, hostsToRemove);
may worth to throw a specific exception for this case and catch it within different catch block

2021-12-10 13:55 UTC, horadla23 approved these changes
I had just one minor comment regarding logging

2021-12-10 13:55 UTC, horadla23 commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerDecomissioner.java
> +                LOGGER.debug("Hosts remove request sent.");
I would extend this log message with some information (like hosts list)

2021-12-13 19:43 UTC, lajosrodek commented
Achievement unlocked: Commit over 100K changed lines. :smile:

2021-12-14 08:31 UTC, topolyai5 requested changes

2021-12-14 09:14 UTC, lturcsanyi commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionService.java
> +            LOGGER.error("Client init failed for V45 client, thus bulk host removal is not supported");
I would like to see if something went wrong and CB could not init v45 client, thus I would stick with error or at least warn log level.

2021-12-14 09:19 UTC, topolyai5 commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionService.java
> +            LOGGER.error("Client init failed for V45 client, thus bulk host removal is not supported");
If you don't throw an error it must be maximum a warn. But it does not affect the running and you throw the exception during the bulk hist method. It is enough debug level for this message

2021-12-14 09:27 UTC, lturcsanyi commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionService.java
> +            LOGGER.error("Client init failed for V45 client, thus bulk host removal is not supported");
If we cannot init the client it means something definitely went wrong, I'll change this to warn.

2021-12-14 09:28 UTC, horadla23 approved these changes

2021-12-14 13:54 UTC, topolyai5 commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerClusterDecommissionService.java
> +            LOGGER.error("Client init failed for V45 client, thus bulk host removal is not supported");
ok, warn will be good

2021-12-15 08:55 UTC, topolyai5 approved these changes

2021-12-16 13:55 UTC, merged