CB-14577 add CCM upgrade endpoint to distrox and core service
hortonworks/cloudbreak pull request #12032
Opened 2022-01-10 15:31 UTC by afarsang

See detailed description in the commit message.

2022-01-11 09:24 UTC, horadla23 requested changes

2022-01-11 09:24 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
> +    public FlowIdentifier upgradeCcmByCrnInternal(Long workspaceId, String name, String initiatorUserCrn) {
missing annotation from parameter (https://github.com/hortonworks/cloudbreak/tree/master/authorization-common#how-to-make-an-api-internally-callable)

2022-01-11 09:24 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
> +    public DistroXCcmUpgradeV1Response upgradeCcmByCrnInternal(String crn) {
missing annotation from parameter (https://github.com/hortonworks/cloudbreak/tree/master/authorization-common#how-to-make-an-api-internally-callable)

2022-01-11 09:26 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/ccm/StackCcmUpgradeService.java
> +public class StackCcmUpgradeService {
missing `@Service` annotation

2022-01-13 19:07 UTC, lajosrodek requested changes

2022-01-13 19:07 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
> +    }
Change method body to
```
        return stackCcmUpgradeService.upgradeCcm(NameOrCrn.ofCrn(crn), restRequestThreadLocalService.getRequestedWorkspaceId());
```

2022-01-13 19:51 UTC, lajosrodek requested changes

2022-01-13 19:51 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
> +    public FlowIdentifier upgradeCcmByCrnInternal(Long workspaceId, String name, String initiatorUserCrn) {
Please add UT.

2022-01-13 19:51 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
> +    public DistroXCcmUpgradeV1Response upgradeCcmByCrnInternal(String crn) {
Please add UT.

2022-01-14 10:14 UTC, bergerdenes commented
Could not add more comments.

2022-01-18 18:29 UTC, lajosrodek commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
> +            @QueryParam("initiatorUserCrn") String initiatorUserCrn);
Copying from my previous review, these are still unresolved:

* Add `@NotEmpty` (from `javax.validation.constraints`) to `name` and `initiatorUserCrn`.
* `initiatorUserCrn` should be annotated with `@ValidCrn(resource = CrnResourceDescriptor.USER)`.

2022-01-18 18:29 UTC, lajosrodek commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
> +            @QueryParam("initiatorUserCrn") String initiatorUserCrn);
Still unresolved.

2022-01-18 19:20 UTC, lajosrodek requested changes

2022-01-18 19:20 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
> +    public DistroXCcmUpgradeV1Response upgradeCcmByCrnInternal(@NotEmpty @ResourceCrn String crn,  @InitiatorUserCrn @NotEmpty String initiatorUserCrn) {
Please annotate `crn` with `@ValidCrn(resource = CrnResourceDescriptor.DATAHUB)` as well. Validation annotations must appear in both the endpoint and the controller.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/controller/DistroXUpgradeV1Controller.java
> +    public DistroXCcmUpgradeV1Response upgradeCcmByCrnInternal(@NotEmpty @ResourceCrn String crn,  @InitiatorUserCrn @NotEmpty String initiatorUserCrn) {
* Please annotate `initiatorUserCrn` with @ValidCrn(resource = CrnResourceDescriptor.USER) as well.
* Nit: Extra space before `@InitiatorUserCrn`.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/StackV4ControllerTest.java
> +        ThreadBasedUserCrnProvider.doAs(USER_CRN, () -> underTest.upgradeCcmByNameInternal(STACK_NAME, USER_CRN));
Note: Impersonating the user and executing as `USER_CRN` is indeed carried out in the real implementation, but is not strictly necessary for the UT that uses stubbing for `stackCcmUpgradeService.upgradeCcm()`. :smile: No need to change, just a note.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/StackV4ControllerTest.java
> +        ThreadBasedUserCrnProvider.doAs(USER_CRN, () -> underTest.upgradeCcmByNameInternal(STACK_NAME, USER_CRN));
Please verify the return value of `underTest.upgradeCcmByNameInternal()` that it matches the `FlowIdentifier` instance created above.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroxUpgradeV1ControllerTest.java
> +        ThreadBasedUserCrnProvider.doAs(USER_CRN, () -> underTest.upgradeCcmByCrnInternal(CLUSTER_NAME, USER_CRN));
Please verify the return value of `underTest.upgradeCcmByCrnInternal()`:
* Is not `null`
* Its `flowIdentifier` property matches the `FlowIdentifier` instance created above.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/cloudbreak/controller/v4/StackV4ControllerTest.java
> +        when(stackCcmUpgradeService.upgradeCcm(any(), any())).thenReturn(new FlowIdentifier(FlowType.FLOW, "1"));
Please use explicit argument matching with the right values instead of `any()`.

2022-01-18 19:20 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroxUpgradeV1ControllerTest.java
> +        when(stackCcmUpgradeService.upgradeCcm(any(), any())).thenReturn(new FlowIdentifier(FlowType.FLOW, "1"));
Please use explicit argument matching with the right values instead of `any()`.

2022-01-18 20:28 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
> +    public FlowIdentifier upgradeCcmByNameInternal(@NotEmpty String name, @NotEmpty @InitiatorUserCrn String initiatorUserCrn) {
Optionally annotate `name` with `@ResourceName` as well.

2022-01-19 15:03 UTC, afarsang commented on core-api/src/main/java/com/sequenceiq/distrox/api/v1/distrox/model/upgrade/DistroXCcmUpgradeV1Response.java
> +public class DistroXCcmUpgradeV1Response {
I couldn't decide yet

2022-01-20 16:59 UTC, lajosrodek approved these changes
Thanks for the fixes! LGTM. Only one minor comment, up to you whether it gets corrected or not. :smile:

2022-01-20 16:59 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/distrox/v1/distrox/controller/DistroxUpgradeV1ControllerTest.java
>  class DistroxUpgradeV1ControllerTest {
Nit: The class tested is `DistroXUpgradeV1Controller`, so ideally this should be renamed to use an uppercase `X`.

2022-01-28 09:05 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-01-28 10:41 UTC, horadla23 approved these changes

2022-01-28 10:44 UTC, merged