CB-15299: freeipa e2etest for cleanup, CB-12300: freeipa e2etest for createBindUser
hortonworks/cloudbreak pull request #12048
Opened 2022-01-11 16:58 UTC by schfeca75

* CB-15299: freeipa e2etest for cleanup
* CB-12300: freeipa e2etest for createBindUser

2022-01-12 09:59 UTC, lacikaaa commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
> +            operationStatus = ipaClient.getOperationV1Endpoint().getOperationStatus(operationStatus.getOperationId(), accountId);
please don't reassign values to method parameters

2022-01-13 08:28 UTC, schfeca75 commented
Retest this please

2022-01-13 11:24 UTC, horadla23 reviewed
from authz/API point of view, it LGTM

2022-01-14 09:27 UTC, lacikaaa requested changes

2022-01-19 11:09 UTC, lacikaaa approved these changes

2022-01-20 08:30 UTC, doktoric approved these changes

2022-01-20 08:31 UTC, doktoric commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/freeipa/FreeIpaUpgradeTests.java
> +        BindUserCreateRequest bindUserCreateRequest = new BindUserCreateRequest();
any loG ?

2022-01-25 08:45 UTC, merged