CB-8807: Refactor cluster upgrade image filtering
hortonworks/cloudbreak pull request #12043
Opened 2022-01-11 11:39 UTC by tiborpopovics

In this commit I made the following changes:

- Refactor the filtering logic in ClusterUpgradeImageFilter. The filters are extracted into separate classes. These filters are using a common interface: UpgradeImageFilter
- Refactor the ImageFilterResult class. This contains a List<Image> instead of the Images object.
- Refactor the ImageFilterParams class. This class was extended with the cloudPlatform variable.

2022-01-12 09:24 UTC, topolyai5 requested changes
did you check the optimistic lock in the failed test?
http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-pull-request-builder-integration-test/22833/

2022-01-12 11:12 UTC, lacikaaa requested changes

2022-01-12 11:12 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CurrentImageUpgradeImageFilter.java
> +        return filteredImages.isEmpty() ? "There are no newer compatible images available." : EMPTY_REASON;
this message is ok for `ImageCreationBasedUpgradeImageFilter` but doesn't seem right here

2022-01-12 11:12 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageFilterUpgradeService.java
> +        for (UpgradeImageFilter imageFilter : upgradeImageFilters) {
I have some concerns with this solution:
- it seems to me the filtering order is depending on Spring injection order, which could be different for every startup of the service, at least theoretically, which means 2 filtering could have different results depending which is the last filter. I think the filters should have some ordering, as we had previously.
- we still won't have any idea at least about which images made to the last round of filtering if no images available for upgrade. Most of our questions from customer are like: `Why the upgrade for version X is not possible` I think this refactor should also focus on helping us to answer this question.

2022-01-12 11:13 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/ImageFilterUpgradeService.java
> +public class ImageFilterUpgradeService {
and also, no unit tests for this one

2022-01-13 10:56 UTC, tiborpopovics commented
> I've checked the failed IT and It's not related to my changes. I cannot reproduce in my local environment.

2022-01-13 13:20 UTC, topolyai5 commented
> > @topolyai5 I've checked the failed IT and It's not related to my changes. I cannot reproduce in my local environment.

What was the root cause?

2022-01-13 14:04 UTC, topolyai5 commented
> 

Could you please create a jira with the build artifact? We must investigate an optimistic lock to avoid the unnecessary ENGESCs

2022-01-13 15:06 UTC, tiborpopovics commented
> > 
> 
> Could you please create a jira with the build artifact? We must investigate an optimistic lock to avoid the unnecessary ENGESCs

Sure, but unfortunately, the artifact is not available anymore. I can only attach the stacktrace.

2022-01-13 17:01 UTC, topolyai5 approved these changes

2022-01-20 13:53 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/image/filter/CloudPlatformBasedUpgradeImageFilter.java
> +@Component()
nit: no need for parenthesis

2022-01-20 14:04 UTC, lacikaaa approved these changes

2022-01-21 08:44 UTC, lacikaaa approved these changes

2022-01-21 08:45 UTC, merged