Cb 15528 - E2E test for upgrade with custom catalog on Data Hub cluster
hortonworks/cloudbreak pull request #12041
Opened 2022-01-11 08:43 UTC by mhalmy

See detailed description in the commit message.Today we have a single DistroX upgrade test for CDP upgrade http://ci-cloudbreak.eng.hortonworks.com/job/api-longrunning-e2e-aws/1389/testngreports/com.sequenceiq.it.cloudbreak.testcase.e2e.distrox/DistroXUpgradeTests/testDistroXUpgrade/ . We need to extend our testing to 3rd party image catalogs as well.

We should use the prod catalog for this purpose to avoid maintaining a new catalog. Prod catalog can be found here: https://cloudbreak-imagecatalog.s3.amazonaws.com/v3-prod-cb-image-catalog.json. Let's use this in the test with a random name and initiate an upgrade from any to any version using this catalog.
Jira link:
[https://jira.cloudera.com/browse/CB-15528](url)

2022-01-12 09:25 UTC, aszegedi requested changes
Beyond these at least one of the E2E suite should contains the test to run along with E2E tests; for example in case of the existing `com.sequenceiq.it.cloudbreak.testcase.e2e.distrox.DistroXUpgradeTests` at [aws-longrunning-e2e-tests.yaml](https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/resources/testsuites/e2e/aws-longrunning-e2e-tests.yaml).

2022-01-12 09:32 UTC, aszegedi requested changes

2022-01-12 09:32 UTC, aszegedi commented on integration-test/src/main/resources/application.yml
> +    imageCatalogUrl3rdParty: https://cloudbreak-imagecatalog.s3.amazonaws.com/v3-prod-cb-image-catalog.json
We should introduce this new variable to the [cloudbreak-ansible-playbooks/jenkins/build-scripts/cloudbreak-e2e-tests.sh](https://github.com/hortonworks/cloudbreak-ansible-playbooks/blob/master/jenkins/build-scripts/cloudbreak-e2e-tests.sh) and the related Jenkins jobs (longrunning ones and the PR AWS ones).

2022-01-27 12:26 UTC, aszegedi approved these changes

2022-01-27 12:26 UTC, aszegedi commented on integration-test/src/main/resources/application.yml
> +    imageCatalogUrl3rdParty: https://cloudbreak-imagecatalog.s3.amazonaws.com/v3-prod-cb-image-catalog.json
Based on our conversation, we won't make external parameters for these actually. So this comment is out of the scope right now.

2022-02-01 18:02 UTC, lajosrodek requested changes

2022-02-04 11:11 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
> +        return String.format(internalSdxBlueprintName, runtimeVersion); }
Possibly it's git diff problem only, here is fine:
https://github.com/hortonworks/cloudbreak/blob/1336a71d21b4adc35830876419a8c9c4e2413532/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java#L53

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +        String prodCatalogName = resourcePropertyProvider().getName();
Done

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +                .await(STACK_AVAILABLE, key(distroXProdCatName))
Done

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +    private DistroXTestDto checkImageId(DistroXTestDto testDto, String imageId) {
Done

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +            throw new TestFailException(" The selected image ID is: " + testDto.getResponse().getImage().getId() + " instead of: "
Done

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +            throw new TestFailException(" The selected image ID is: " + testDto.getResponse().getImage().getId() + " instead of: "
Done

2022-02-04 12:46 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +    private String uuid;
Done

2022-02-04 12:49 UTC, mhalmy commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +                        .equals(testContext.commonCloudProperties().getCloudProvider().toLowerCase())).iterator().next().getUuid();
Won't do because findfirst() produces NoSuchElementException. 
With .iterator().next() works correctly.

2022-02-04 19:26 UTC, lajosrodek commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java
> +        return String.format(internalSdxBlueprintName, runtimeVersion); }
No, it is not. It is clearly a source code formatting error even here https://github.com/hortonworks/cloudbreak/blob/1336a71d21b4adc35830876419a8c9c4e2413532/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/cloud/v4/CommonClusterManagerProperties.java#L51.

2022-02-04 19:26 UTC, lajosrodek commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +                        .equals(testContext.commonCloudProperties().getCloudProvider().toLowerCase())).iterator().next().getUuid();
Sorry, I do not really get this. `Stream.findFirst()` returns an `Optional<>`, it cannot ever throw `NoSuchElementException`. 

Anyway, I was originally referring to the trailing `.iterator().next().getUuid()` to be potentially replaced with `.findFirst().map(img -> img.getUuid()).orElse(null)`, but up to you skip this refactoring.

2022-02-04 19:37 UTC, lajosrodek approved these changes
Thanks for the fixes, LGTM. I had just one comment to eliminate the `AtomicReference` as it is not required anymore with the revised code, but it is also OK to leave this as is.

2022-02-04 19:37 UTC, lajosrodek commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXUpgradeTests.java
> +        uuid.set(getUuid(testContext, thirdPartyCatalogName, currentRuntimeVersion3rdParty));
Oh, so the `getUuid()` invocation is not inside of a lambda? Maybe I was delusional seeing it in a lambda last time. :smile: Anyway, with the present approach, it is not even necessary to employ an `AtomicReference<String>`; `uuid` could be a regular `String`. (I suggested the `AtomicReference` as I thought the value would be calculated & set by a lambda.)

2022-02-17 14:46 UTC, merged