CB-15404 Introduce Cloudera Runtime 7.2.15
hortonworks/cloudbreak pull request #12053
Opened 2022-01-12 14:35 UTC by pkedvessy

See detailed description in the commit message.

2022-01-12 14:44 UTC, horadla23 requested changes

2022-01-12 14:44 UTC, horadla23 commented on datalake/src/main/resources/application.yml
> +    advertised: "7.1.0,7.2.0,7.2.1,7.2.2,7.2.6,7.2.7,7.2.8,7.2.9,7.2.10,7.2.11,7.2.12,7.2.13,7.2.147.2.15"
`,` is missing

2022-01-12 14:46 UTC, horadla23 commented
is it required for 7.2.15 to be in 2.51? we are about to release it, I guess it should go only in master

2022-01-12 14:50 UTC, lnardai commented
Yes, we've discussed this with @TheTinkerDad and that this will only be merged, after 2.51 is released.

2022-01-12 14:55 UTC, pkedvessy commented on datalake/src/main/resources/application.yml
> +    advertised: "7.1.0,7.2.0,7.2.1,7.2.2,7.2.6,7.2.7,7.2.8,7.2.9,7.2.10,7.2.11,7.2.12,7.2.13,7.2.147.2.15"
Ahh, thanks.

2022-01-12 15:04 UTC, horadla23 approved these changes

2022-01-13 08:23 UTC, closed without merging

2022-01-13 08:24 UTC, pkedvessy commented
Support for 7.2.15 has been moved to CB 2.52. It should be available on mow-dev by Monday (02.18) or so.