CB-15837 Fix single resource group test teardown
hortonworks/cloudbreak pull request #12156
Opened 2022-01-27 11:32 UTC by aszegedi

The recent changes of [CB-15688](https://jira.cloudera.com/browse/CB-15688) / [PR 12097](https://github.com/hortonworks/cloudbreak/pull/12097) override `DistroXEncryptedVolumeTest.tearDown()` in order to clean up Azure RG and tested resources.

The problem is, this method uses the:
```
onlyForGroups = { "azure_singlerg" }
```
condition and so it will not be invoked in case of AWS test case. Hence running that test class on AWS will likely leave behind cluster resources instead of cleaning them up.

2022-01-27 11:40 UTC, lajosrodek approved these changes
LGTM

2022-01-27 12:23 UTC, horadla23 requested changes

2022-01-27 12:23 UTC, horadla23 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
> +    public void singleResourceGroupTearDown(Object[] data) {
same here: in this case cleanup will triggered twice, since parent class also calling this

2022-01-27 12:24 UTC, horadla23 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXEncryptedVolumeTest.java
> +    public void singleResourceGroupTearDown(Object[] data) {
so cleanupTestContext call should be removed from this method

2022-01-28 14:01 UTC, horadla23 approved these changes

2022-02-01 07:52 UTC, merged