CB-15909 Change rootVolume to 100GB for all types of nodes. Updated r…
hortonworks/cloudbreak pull request #12193
Opened 2022-02-01 21:12 UTC by vbrodetskyi

…ootVolume from 50 GB to 100 GB for Yarn to unblock tests. If rootVolume lower than 100 GB then cluster deploy fails.

See detailed description in the commit message.

2022-02-01 21:14 UTC, vbrodetskyi commented
@lnardai @doktoric we need this change for 7.2.14, could you please review it?

2022-02-02 07:34 UTC, lnardai commented
Can you link any details what changed? Why do we need to double the volumeSize?

2022-02-02 10:22 UTC, lajosrodek requested changes
Changes look okay. Could you please apply them to the 7.2.15 cluster definitions as well?

2022-02-02 12:18 UTC, vbrodetskyi commented
> Can you link any details what changed? Why do we need to double the volumeSize? Does this needed for prod? Why can't this be targeted to master?

@lnardai @lajosrodek we need that because cluster deploy fails in case rootVolume size is lower than 100GB. For AWS, GCP and Azure this issue is already fixed, so i decided to fix it for YCloud too. I will also commit that to master in separate PR for 7.2.14 and 7.2.15.

2022-02-02 13:47 UTC, lnardai commented
ycloud is only supported internally. If this is needed for mow-int, might worth to consider CB-2.52.0 as it's the next release branch.
"we need that because cluster deploy fails in case rootVolume size is lower than 100GB." - ok, so, let me rephrase the question. Have you checked what takes up so much additional space that we need to double these values? How much do we actually use of the extra 50GB?

2022-02-02 14:05 UTC, closed without merging