CB-16073 - Freeipa scaling api rename
hortonworks/cloudbreak pull request #12261
Opened 2022-02-10 11:00 UTC by pdarvasi

See detailed description in the commit message.

2022-02-10 12:31 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/AvailabilityType.java
> +    private static final Map<Integer, AvailabilityType> FORM_FACTOR_MAP_BY_INSTANCE_COUNT;
I would also rename the const FORM_FACTOR_MAP....

2022-02-10 12:32 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleRequestBase.java
> +                ", targetFormFactor=" + targetAvailabilityType +
also here I would rename targetFormFactor=

2022-02-10 12:33 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleResponseBase.java
> +    public AvailabilityType getOriginalFormFactor() {
I would rename the method to getOriginalAvailabilityType

2022-02-10 12:33 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleResponseBase.java
> +    public void setOriginalFormFactor(AvailabilityType originalAvailabilityType) {
I would rename the method to setOriginalAvailabilityType

2022-02-10 12:34 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleResponseBase.java
> +    public AvailabilityType getTargetFormFactor() {
Also, I would rename to get/setTargetAvailabilityType

2022-02-10 12:35 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScaleResponseBase.java
> +                ", originalFormFactor=" + originalAvailabilityType +
I would also rename the toString to original/targetAvailabilityType=

2022-02-10 12:45 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScalingPath.java
> +                "originalFormFactor=" + originalAvailabilityType +
I would rename the toString lines to original/targetAvailabilityType=

2022-02-10 12:46 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/service/api/doc/ModelDescriptions.java
> +    public static final String AVAILABILITY_TYPE = "Availability type or form factor of the resource reflecting the number of instances and the presence or absence of high availability";
I would delete the "or form factor"

2022-02-10 12:47 UTC, gergopapi2 commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaScalingService.java
> +        LOGGER.debug("{} request received with original form factor {} and request {}", operationType, originalAvailabilityType, request);
I would change the log message: form factor to availability type.

2022-02-11 13:40 UTC, pdarvasi commented
Swagger failure is expected, can be ignored: 
![image](https://user-images.githubusercontent.com/19725708/153601542-4787f214-24a3-494a-9c1f-55d4be3a1415.png)

2022-02-15 18:44 UTC, gergopapi2 requested changes

2022-02-15 18:44 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScalingPath.java
> +    public AvailabilityType getOriginalFormFactor() {
I would rename it to getOriginalAvailabilityType()

2022-02-15 18:44 UTC, gergopapi2 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/scale/ScalingPath.java
> +    public AvailabilityType getTargetFormFactor() {
Please rename to getTargetAvailabilityType()

2022-02-17 11:21 UTC, merged