CB-14421 hosts pillar should be removed in order to support targeted …
hortonworks/cloudbreak pull request #12273
Opened 2022-02-11 13:01 UTC by horadla23

…upscale

See detailed description in the commit message.

2022-02-15 12:32 UTC, oleewere commented
for me highstate does not work after an upscale.

hosts pillar before upscale:
```bash
oszabo-de-worker1.oszabo-l.xcu2-8y8x.wl.cloudera.site:
    ----------
    10.112.24.13:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker1.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker1
        instance_id:
            i-012af315c5e208cd7
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.24.170:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-master0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-master0
        instance_id:
            i-0e2a9fd7720e03244
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.169:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-compute0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-compute0
        instance_id:
            i-030360a2a40fbfafb
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.57:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker2.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker2
        instance_id:
            i-0cbf93650da2c44cd
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.27.199:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker0
        instance_id:
            i-09cbd57beaa11812f
        instance_type:
            m5.2xlarge
        public_address:
            False
oszabo-de-master0.oszabo-l.xcu2-8y8x.wl.cloudera.site:
    ----------
    10.112.24.13:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker1.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker1
        instance_id:
            i-012af315c5e208cd7
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.24.170:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-master0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-master0
        instance_id:
            i-0e2a9fd7720e03244
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.169:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-compute0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-compute0
        instance_id:
            i-030360a2a40fbfafb
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.57:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker2.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker2
        instance_id:
            i-0cbf93650da2c44cd
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.27.199:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker0
        instance_id:
            i-09cbd57beaa11812f
        instance_type:
            m5.2xlarge
        public_address:
            False
oszabo-de-worker0.oszabo-l.xcu2-8y8x.wl.cloudera.site:
    ----------
    10.112.24.13:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker1.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker1
        instance_id:
            i-012af315c5e208cd7
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.24.170:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-master0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-master0
        instance_id:
            i-0e2a9fd7720e03244
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.169:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-compute0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-compute0
        instance_id:
            i-030360a2a40fbfafb
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.57:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker2.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker2
        instance_id:
            i-0cbf93650da2c44cd
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.27.199:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker0
        instance_id:
            i-09cbd57beaa11812f
        instance_type:
            m5.2xlarge
        public_address:
            False
oszabo-de-worker2.oszabo-l.xcu2-8y8x.wl.cloudera.site:
    ----------
    10.112.24.13:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker1.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-worker1
        instance_id:
            i-012af315c5e208cd7
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.24.170:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-master0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-master0
        instance_id:
            i-0e2a9fd7720e03244
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.169:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-compute0.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostname:
            oszabo-de-compute0
        instance_id:
            i-030360a2a40fbfafb
        instance_type:
            m5.2xlarge
        public_address:
            False
    10.112.26.57:
        ----------
        custom_domain:
            True
        domain:
            oszabo-l.xcu2-8y8x.wl.cloudera.site
        fqdn:
            oszabo-de-worker2.oszabo-l.xcu2-8y8x.wl.cloudera.site
        hostn [...]

2022-02-15 21:01 UTC, horadla23 commented
I have changed the logic, hosts pillar is complete in case of targeted upscale too

2022-02-16 13:36 UTC, horadla23 commented
changes: 
- `hosts` pillar should be updated completely in case of targeted upscale too
- pillar save in case of `hosts` pillar uses different call (instead of various Set<Node> parameters) to get all nodes of related stack (cb stack or freeipa stack)
- ensure that there is no duplicated db query for stack to get all nodes and generate nodes list for pillar save as input
- minor refactors in order to make such logic possible
- improvement: cover targeted upscale feature with e2e

2022-02-17 11:48 UTC, oleewere approved these changes
lgtm, highstate is not failing now on DH

2022-02-17 15:05 UTC, lacikaaa commented
@horadla23 please resolve conflicts

2022-02-17 15:06 UTC, horadla23 commented
> @horadla23 please resolve conflicts

sure, I am waiting for you to finish merging PRs to master :D

2022-02-17 16:01 UTC, lacikaaa requested changes

2022-02-17 17:55 UTC, horadla23 commented
need to retest

2022-02-21 12:01 UTC, lacikaaa commented on orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
> +        Set<Node> allNodes = allNodesForOrchestration.stream().map(OrchestrationNode::getNode).collect(Collectors.toSet());
this stream could be a default implementation in the `OrchestratorAware` interface as  see it's used in multiple places

2022-02-21 13:41 UTC, lacikaaa approved these changes

2022-02-21 13:49 UTC, horadla23 commented
![Screenshot from 2022-02-21 14-49-01](https://user-images.githubusercontent.com/26329499/154967694-fba8029c-a9fc-410a-a246-e73a1a7ac6ed.png)

2022-02-21 16:52 UTC, horadla23 commented
(the only reason I re-requested review from Oliver is because re-request makes this PR visible of approved master PR list)

2022-02-21 18:39 UTC, merged