CB-16159 Replace STACK_GATEWAY_CERTIFICATE_CREATE_FAILED to SKIPPED
hortonworks/cloudbreak pull request #12306
Opened 2022-02-17 13:04 UTC by agov

Since it's a non-fatal failure, eventType should not include FAILED.

See detailed description in the commit message.

2022-02-22 10:42 UTC, lnardai commented on common/src/main/java/com/sequenceiq/cloudbreak/event/ResourceEvent.java
> +    STACK_GATEWAY_CERTIFICATE_CREATE_SKIPPED("stack.gateway.certificate.create.skipped"),
Since it's an enum I would rather go with an extension and remove it after the next release.

2022-02-22 10:49 UTC, lnardai requested changes
Please create a new enum just to be safe and mark the previous as deprecated.

2022-02-22 11:10 UTC, biharitomi approved these changes

2022-02-24 09:38 UTC, lnardai approved these changes

2022-02-24 09:38 UTC, merged