DISTX-731 Propagate telemetry metrics for custom configurations
hortonworks/cloudbreak pull request #12367
Opened 2022-03-02 08:15 UTC by aakashshankar

#### Changes
 - Added new column to `CDPClusterShape` to determine if custom configurations was used for the DH cluster or not
 - New field `customConfigurationsUsed` in `StackDetails`

#### Testing
 - UT for the relevant converters.

See detailed description in the commit message.

2022-03-14 06:11 UTC, juhi-09 approved these changes
LGTM

2022-03-16 10:40 UTC, nadamdb approved these changes
LGTM

2022-03-16 11:27 UTC, aakashshankar commented
Rebasing to resolve merge conflicts

2022-03-22 16:19 UTC, lajosrodek requested changes
Only a minor ask:

2022-03-22 16:32 UTC, aakashshankar commented on core/src/test/java/com/sequenceiq/cloudbreak/structuredevent/converter/StackToStackDetailsConverterTest.java
> +        Assertions.assertNotNull(actual.getCustomConfigurations());
Added a more specific assertion

2022-03-24 09:21 UTC, merged