Enable backup on upgrade entitlement in UMS mock
hortonworks/cloudbreak pull request #12403
Opened 2022-03-08 10:14 UTC by keyki

See detailed description in the commit message.

2022-03-08 11:49 UTC, gergopapi2 approved these changes

2022-03-08 12:59 UTC, pdarvasi approved these changes

2022-03-08 13:57 UTC, lnardai requested changes
We've checked our internal cloud-eng environment, there is no running datalake backuo service configured there.

I would advise to move this testcase to the mow-dev suite, where the entitlement can be enabled through UMS.
cc: @aszegedi

2022-03-08 13:59 UTC, keyki commented
> We've checked our internal cloud-eng environment, there is no running datalake backuo service configured there.
> 
> I would advise to move this testcase to the mow-dev suite, where the entitlement can be enabled through UMS. cc: @aszegedi

We've already configured our E2E tests to use the `skipBackup` flag. I just want to make sure it's tested properly that we indeed skip it.

2022-03-09 10:14 UTC, lnardai approved these changes
Based on @keyki comment this is ok.

2022-03-09 10:14 UTC, merged