CB-16316: Improve the performance of the retrieval of the required parcels
hortonworks/cloudbreak pull request #12429
Opened 2022-03-10 09:37 UTC by tiborpopovics

This change contains the following improvements:
- Added cache for parcel metadata retrieval
- Added 5 sec timeout for getting the metadata xml
- Improved ParcelFilterService to not get all parcels manifest if the required parcels are found.

2022-03-17 17:33 UTC, pdarvasi requested changes

2022-03-21 08:48 UTC, tiborpopovics commented on core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelFilterService.java
> +        if (!serviceNamesInBlueprint.isEmpty()) {
I've added some logs for this logic. Is it better now?

2022-03-24 08:36 UTC, merged

2022-03-24 08:38 UTC, doktoric commented on core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ManifestRetrieverService.java
> +            WebTarget target = client.target(StringUtils.stripEnd(baseUrl, "/") + "/manifest.json");
can we use URI for this join ? In that case we dont need this stripend

2022-03-24 08:38 UTC, doktoric commented on core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ManifestRetrieverService.java
> +            return ImmutablePair.of(ManifestStatus.COULD_NOT_PARSE, null);
maybe we should populate the error as a structured event ?