CB-15857 Add EDH feature tracking capability to FreeIPA service and t…
hortonworks/cloudbreak pull request #12452
Opened 2022-03-16 18:15 UTC by nadamdb

…rack FreeIPA up and downscaling actions.

Previously the EDH feature tracking was only implemented in the core and environment services. With this change the tracking also becomes available in the freeipa service. The implemetation is based on the existing implementations in the other two services. The flow state mapping is similar to the mapping in the legacy structuredevent service, because the capability to differentiate single flows from flows in a flowchain is necessary for the distinction of a standalone freeipa scaling action from scaling during a freeipa upgrade (tracking will be added later).

See detailed description in the commit message.

2022-03-21 07:28 UTC, lnardai commented
Is this essential for 2.54? Looks like a new feature to me. If so, please retarged this to master.

2022-03-21 09:12 UTC, keyki commented
> Is this essential for 2.54? Looks like a new feature to me. If so, please retarged this to master.

It's not essential to 2.54, we will need it to track the feature in EDH. We can do this as a hotfix, don't block the release because of this, but we eventually need this in 2.54.

2022-03-23 09:33 UTC, lnardai commented
@keyki should we wait for a review from your team?

2022-03-23 10:13 UTC, keyki commented
> @keyki should we wait for a review from your team?

Yes, @pdarvasi will review today

2022-03-23 23:03 UTC, pdarvasi requested changes

2022-03-23 23:03 UTC, pdarvasi commented on usage-collection/src/main/java/com/sequenceiq/cloudbreak/usage/UsageReporter.java
> +     * Reports that an CDP FreeIPA status has been changed.
minor typo: `an` -> `a`. Pls replace all occurrences

2022-03-24 14:32 UTC, nadamdb commented on structuredevent-service-cdp/src/main/java/com/sequenceiq/cloudbreak/structuredevent/service/telemetry/converter/CDPEnvironmentStructuredFlowEventToCDPEnvironmentRequestedConverter.java
> +
The payload in CDPStructuredEvent class is generic type and operationDetailsConverter.convert() converts only the CDPStructuredEvent class. The payload in the converter previously was only used to get the cloud provider, but before the change the converter was not converting CDPStructuredEvent but the child class CDPEnvironmentStructuredFlowEvent so the payload type was known. By making the converter more generic the type is not known anymore. I tried making a separate abstract Payload class that has a getCloudProvider() function, but in the datalake service SdxClusterDto (in datalake module) is used as payload and making that class extend the Payload class (in structuredeventmodel module) was causing cyclic dependency. 
Addig it as parameter to the converter was the next best thing that i could think of, but i'm open to suggestions for a better solution.

2022-03-24 22:34 UTC, pdarvasi approved these changes

2022-03-24 22:35 UTC, pdarvasi commented
LGTM, nicely done, @nadamdb

2022-03-25 08:35 UTC, keyki approved these changes

2022-03-25 08:36 UTC, keyki approved these changes

2022-03-28 08:26 UTC, merged