CB-15392 add flow to handle ephemeral datahubs to pick up changes from SDX resize operation
hortonworks/cloudbreak pull request #12453
Opened 2022-03-16 22:10 UTC by yg-gd

**Here is the summary of the change**
1. Created two flows, one in cloudbreak to trigger cluster refresh the changes and another from datalake to wait on the CB flow.
2. Made changes to avoid stopping DH when DL is resized.
Added [CB-16637](https://jira.cloudera.com/browse/CB-16637) for E2E test.

2022-03-22 08:17 UTC, foldik requested changes

2022-03-22 08:17 UTC, foldik commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/mock/MockSdxResizeTests.java
> +    //@Test(dataProvider = TEST_CONTEXT_WITH_MOCK)
Can you enable this test?

2022-03-22 20:05 UTC, yg-gd commented
@kkalvagadda1 could you ensure that ClouderaManagerClientActions.getCmServiceResourceHiveHost is checking the correct thing?

2022-03-23 07:28 UTC, foldik approved these changes
LGTM

2022-03-23 16:23 UTC, kkalvagadda1 requested changes

2022-03-26 03:13 UTC, kkalvagadda1 approved these changes

2022-03-26 07:27 UTC, foldik approved these changes
LGTM

2022-03-28 22:29 UTC, sxxgrc approved these changes

2022-03-29 13:05 UTC, gregito requested changes
small and fast requests left

2022-03-29 14:08 UTC, kkalvagadda1 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterServicesRestartService.java
> +        return blueprintProcessor.isCMComponentExistsInBlueprint("HIVEMETASTORE");
adddressed.

2022-03-29 14:09 UTC, kkalvagadda1 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterServicesRestartService.java
> +                apiConnectors.getConnector(dataHubStack).updateServiceConfig(service, getRdsConfigMap(rdsConfig.get()));
addressed.

2022-03-29 14:09 UTC, kkalvagadda1 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/ClusterServicesRestartService.java
> +            updateDatabaseConfiguration(datalakeStack, stack, HIVE_SERVICE, DatabaseType.HIVE);
addressed.

2022-03-29 17:03 UTC, merged