CB-16542 Improve logging in the role count validator
hortonworks/cloudbreak pull request #12462
Opened 2022-03-21 13:57 UTC by topolyai5

2022-03-21 14:44 UTC, foldik approved these changes
Looks good.

2022-03-21 15:13 UTC, lajosrodek requested changes

2022-03-21 15:13 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java
> +                                    requiredCount, role));
* `role` this should come right after `groupNames`.
* `%s remained instances but %s the required` -> `%s remaining instances but %s are required`

2022-03-22 11:29 UTC, lajosrodek requested changes

2022-03-22 11:29 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java
> +                            LOGGER.debug("There are {} node(s) has in group of {} with role: {}", nodeCount, instanceGroup.getGroupName(), role);
Nit: delete `has`.

2022-03-22 11:29 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java
> +                        LOGGER.debug("There are {} node(s) has in group of {} with role: {}, adjusted node count: {}", instanceGroup.getNodeCount(),
Nit: delete `has`.

2022-03-22 11:29 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/CmTemplateValidator.java
> +                                    role, requiredCount));
* Argument `role` should come right after `groupNames`.
* `%s remaining instances but %s are required` both placeholders should be replaced with `%d`.

2022-03-23 07:36 UTC, topolyai5 commented
@foldik integrated into https://github.com/hortonworks/cloudbreak/pull/12473

2022-03-23 07:36 UTC, closed without merging