CB-16458 E2E tests for Resilient Scaling with percentage option
hortonworks/cloudbreak pull request #12477
Opened 2022-03-22 22:52 UTC by aszegedi

See detailed description in the commit message.

2022-03-24 12:58 UTC, bbihari requested changes

2022-03-24 12:58 UTC, bbihari commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXScaleTestParameters.java
> +        adjustmentType = Arrays.stream(AdjustmentType.values())
It's a bit complicated, why not just Enum.valueOf(AdjustmentType.class, adjustmentTypeName)?

2022-03-24 15:54 UTC, bbihari approved these changes

2022-03-25 12:36 UTC, afarsang approved these changes

2022-03-28 07:49 UTC, merged