CB-15833 Database engine version setting was missing from DistroX converters
hortonworks/cloudbreak pull request #12472
Opened 2022-03-22 13:30 UTC by daszabo

2022-03-23 07:26 UTC, lacikaaa approved these changes

2022-03-23 13:13 UTC, gregito requested changes

2022-03-23 13:13 UTC, gregito commented on core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/stacks/database/ExternalDatabaseToDatabaseResponseConverter.java
>          return response;
I suppose we should send back the result as null when both input fields are null

2022-03-24 10:06 UTC, gregito approved these changes

2022-03-24 10:35 UTC, merged