CB-16384 Introduce quartz scheduler metrics
hortonworks/cloudbreak pull request #12471
Opened 2022-03-22 13:21 UTC by lturcsanyi

- actual job count by job group
- trigger count by trigger group
- scheduled trigger count by trigger group
- scheduler error count

See detailed description in the commit message.

2022-03-24 09:31 UTC, sodre90 requested changes

2022-03-24 09:31 UTC, sodre90 commented on common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricType.java
> +    TRIGGER_COUNT("quartz.trigger.count"),
TRIGGER_COUNT -> can't see any usage

2022-03-24 09:53 UTC, lturcsanyi commented on common/src/main/java/com/sequenceiq/cloudbreak/quartz/metric/QuartzMetricType.java
> +    TRIGGER_COUNT("quartz.trigger.count"),
Good catch, thanks

2022-03-25 09:17 UTC, biharitomi approved these changes

2022-03-25 14:57 UTC, merged