DISTX-681: Switch DE templates to use temporaryStorage as ephemeral volumes
hortonworks/cloudbreak pull request #12507
Opened 2022-03-25 10:55 UTC by juhi-09

DISTX-681: Switch DE templates to use temporaryStorage as ephemeral volumes

This commit changes the instance type for compute and worker nodes of Data engineering cluster templates for AWS.

2022-03-25 14:26 UTC, nadamdb reviewed
Shouldn't these changes be added to the 7.2.15 templates as well?

2022-03-28 06:25 UTC, juhi-09 commented
> Shouldn't these changes be added to the 7.2.15 templates as well?

Will be adding to other templates going forward.

2022-03-28 17:30 UTC, sidseth reviewed
How does this show up on the UI?
The default for the 'compute' group for these templates will be r5d.4xlarge, and ephemeral? OR does it still end up attaching some EBS volumes?

2022-03-28 23:03 UTC, shwethags commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering.json
> +          "instanceType": "r5d.4xlarge"
Replace m5.2xlarge with r5d.2xlarge for non-HA templates

2022-03-30 16:13 UTC, juhi-09 commented
> How does this show up on the UI? The default for the 'compute' group for these templates will be r5d.4xlarge, and ephemeral? OR does it still end up attaching some EBS volumes?

On UI Defaults for 'compute' will show "r5d.2xlarge"/"r5d.4xlarge" for non-ha/ha respectively with "ephemeral" Storage Type. EBS will not be attached.
On UI Defaults for 'worker' will show "r5d.2xlarge"/"r5d.4xlarge" for non-ha/ha respectively with "General Purpose (SSD)" Storage Type. EBS will be attached.

2022-04-04 07:22 UTC, nadamdb approved these changes
LGTM

2022-04-05 07:03 UTC, doktoric commented
are you sure that this is the right ephemeral config ?

2022-04-05 07:06 UTC, juhi-09 commented
> are you sure that this is the right ephemeral config ?

Yes, @doktoric

2022-04-05 07:10 UTC, doktoric commented
<img width="593" alt="Screenshot 2022-04-05 at 09 10 06" src="https://user-images.githubusercontent.com/1117088/161698477-de9c8d49-0c5d-41c8-9790-11abbec6ee5c.png">
This is what I see on aws

2022-04-05 07:15 UTC, juhi-09 commented
> <img alt="Screenshot 2022-04-05 at 09 10 06" width="593" src="https://user-images.githubusercontent.com/1117088/161698477-de9c8d49-0c5d-41c8-9790-11abbec6ee5c.png">
> This is what I see on aws

Yes, this was discussed with @shwethags and @rbalamohan

2022-04-06 05:55 UTC, rbalamohan reviewed
LGTM

2022-04-07 07:14 UTC, lacikaaa commented
@doktoric @nadamdb  could you review? I don't see any current approval

2022-04-11 08:12 UTC, nadamdb requested changes

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-ha.json
>              "count": 1,
Please correct these to reflect the ephemeral volume properties of r5d.4xlarge

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-spark3.json
>                "size": 100,
Same here, with r5d.2xlarge

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering.json
>                "size": 100,
same

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-ha.json
>              "count": 1,
same

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-spark3.json
>                "size": 100,
same

2022-04-11 08:12 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering.json
>                "size": 100,
same

2022-04-11 11:17 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-ha.json
> +            "size": 100
Why is the root volume size changed?

2022-04-11 11:17 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.15/aws/dataengineering-ha.json
>              "size": 150
Why is the root volume size changed in the 7.2.14 template but not in the 7.2.15?

2022-04-11 11:17 UTC, nadamdb commented on core/src/main/resources/defaults/clustertemplates/7.2.14/aws/dataengineering-ha.json
> +            "size": 100,
Why is the EBS volume size changed?

2022-04-12 08:42 UTC, nadamdb requested changes

2022-04-12 09:31 UTC, nadamdb approved these changes
LGTM

2022-04-14 09:07 UTC, merged