CB-16783 eliminate CVE-2022-22965 vulnerability
hortonworks/cloudbreak pull request #12562
Opened 2022-04-05 13:35 UTC by horadla23

See detailed description in the commit message.

2022-04-05 13:38 UTC, bergerdenes approved these changes

2022-04-06 18:07 UTC, horadla23 commented
retest this please

2022-04-08 08:19 UTC, lacikaaa requested changes
could you add a bit more descriptive commit message and if you have a CB jira id?

2022-04-08 08:57 UTC, lnardai approved these changes

2022-04-08 09:13 UTC, lacikaaa approved these changes

2022-04-08 11:06 UTC, merged