[Hue] - CDPD-32891 - Cloud Break Template change for QP
hortonworks/cloudbreak pull request #12582
Opened 2022-04-06 17:00 UTC by Amlesh1902

See detailed description in the commit message.

2022-04-08 13:05 UTC, topolyai5 requested changes

2022-04-08 13:05 UTC, topolyai5 commented on core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
> +                "QUERY_PROCESSOR");
intention error

2022-04-09 10:37 UTC, doktoric commented
is this required for 7.2.14 ? You mentioned it only requires 7.2.15

2022-04-11 14:30 UTC, Amlesh1902 commented
@sreenaths , I think it should be for 7.2.15, please confirm about 7.2.14.
@doktoric we will get back in sometime with the answer about 7.2.14. I hope thereafter we are good to merge this in CB-2.55.0.

2022-04-12 01:16 UTC, sreenaths commented on core-api/src/test/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollectorTest.java
> +                "QUERY_PROCESSOR");
Done

2022-04-12 01:25 UTC, sreenaths commented
@Amlesh1902 @doktoric 
As you can see in the CSD, the service is supported from CDH v7.2.13 and above. https://github.infra.cloudera.com/Starship/cmf/blob/cdpd-master/csd/QUERY_PROCESSOR/src/descriptor/service.sdl#L13
As 7.2.13 was scrapped, we went with 7.2.14.
But other than that there is no hard requirement for for 7.2.14.

Support from 7.2.15 is good enough.

2022-04-19 08:26 UTC, topolyai5 commented
Could you please squash the commits and resolve the conflicts?

2022-07-25 14:47 UTC, doktoric commented
please rebase

2022-11-07 13:18 UTC, closed without merging

2022-11-07 13:19 UTC, lnardai commented
Close the PR since it looks abandoned. Please reopen and rebase it if it's still required.