CB-16541 Enable scaling when the cluster is in NODE_FAILURE state, ad…
hortonworks/cloudbreak pull request #12580
Opened 2022-04-06 14:50 UTC by bbihari

…d e3e test

The first scale up operation is starting from NODE_FAILURE state.

2022-04-07 08:10 UTC, horadla23 commented on cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCloudFormationSetup.java
> +        if (entitlementService.targetedUpscaleSupported(accountId) && entitlementService.isUnboundEliminationSupported(accountId)) {
please use `TargetedUpscaleSupportService#targetedUpscaleEntitlementsEnabled`

2022-04-07 08:10 UTC, horadla23 commented on cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsUpscaleService.java
> +        if (entitlementService.isUnboundEliminationSupported(accountId) && entitlementService.targetedUpscaleSupported(accountId)) {
please use `TargetedUpscaleSupportService#targetedUpscaleEntitlementsEnabled`

2022-04-07 08:32 UTC, horadla23 approved these changes
LGTM

2022-04-07 10:34 UTC, aszegedi approved these changes

2022-04-08 08:22 UTC, lacikaaa requested changes

2022-04-08 12:06 UTC, bbihari commented on cloud-aws-cloudformation/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCloudFormationSetup.java
>                  String errorMessage = "Not all the existing instances are in [Started] state, upscale is not possible!";
sure

2022-04-08 12:14 UTC, lacikaaa approved these changes

2022-04-11 07:01 UTC, merged