CDPSDX-3491: Modified use of stack name for stack termination and status checking when the stack is detached to avoid multiple issues.
hortonworks/cloudbreak pull request #12602
Opened 2022-04-08 22:04 UTC by sxxgrc

Jira: https://jira.cloudera.com/browse/CDPSDX-3491

Main issue here is that for certain cloud providers (specifically Azure and the Mock Cloud Provider), in some cases the stack name is used to define important resources.
For Azure this includes the name of the resource group created where the stack instances are located (this is only for cases where the environment is created without a pre-specified resource group.

It's very clear that after a detach, when the stack name is modified, that these resources will no longer be located resulting in errors.

Specifically, we see errors in two places:

- The `StackStatusCheckerJob` as it attempts to verify the health of the stack instances using an incorrect resource name
- The termination of the stack, where it attempts to terminate the stack and its instances using an incorrect resource name

My main goal with this work was to provide a way for the 2 cases above to use the _original_ stack name, instead of the detached one. I hope it is clear how this fixes the issue.

As such, my changes consist of the following:

- Adding a new `detached` field to the stack object
- Using the `displayName` field, which in most cases contains the original stack name, in the 2 cases I mentioned above
- During updating of the stack name/crn, I now update the `detached` field and ensure the `displayName` field is what we expect if the stack is being detached

That's literally all I changed. I unfortunately have not been able to test this yet, but am doing so now. However, as this is a pretty important issue, I would appreciate as many eyes on it as possible.

2022-04-08 23:01 UTC, RokolyA94 approved these changes

2022-04-08 23:03 UTC, sxxgrc commented
Apparently Mock provider uses Stack CRN instead of stack name for whatever reason, so I modified that too.

One other thing I could do if anyone thinks this is too intrusive, is introduce new fields in the CloudContext object. I could then use those specifically in the specific actions which have issues.

However I have looked through the code and do not see any alarming places where this may be an issue.

2022-04-08 23:14 UTC, sxxgrc commented
Giving up on fixing Mock, see Jira for issues. Azure is more important and easier to fix.

2022-04-10 06:49 UTC, sxxgrc commented
I have finished verifying that this works as desired.

2022-04-11 06:57 UTC, bergerdenes approved these changes

2022-04-11 15:59 UTC, yg-gd requested changes

2022-04-11 15:59 UTC, yg-gd commented on core/src/main/resources/schema/app/20220408210524_CDPSDX-3491:_Adding_detach_field_to_stack.sql
> +ALTER TABLE stack ADD COLUMN IF NOT EXISTS detached boolean default false;
I don't think there is meaning to a non-datalake stack that has been detached, no? 

If you're going to add a field either way adding the actual originalName seems more straight forward.

2022-04-11 15:59 UTC, yg-gd commented on core/src/main/java/com/sequenceiq/cloudbreak/service/stack/StackInstanceStatusChecker.java
> +                    .withName(stack.isDetached() ? stack.getDisplayName() : stack.getName())
I don't like this for 2 reasons, you'll need to know do this in any new locations you're building a CloudContext and when I think of functionality around a DisplayName field, I would not expect it to change any behavior outside of what the customer ends up seeing.

2022-04-11 21:20 UTC, sxxgrc commented
Made a few changes:

- Instead of a new `detached` boolean field, `Stack` now has an `originalName` field
- When the stack is detached, `originalName` is the first name the stack had, otherwise this field is `null`
- `CloudContext` now has an `originalName` field as well which is only used in the problematic case I discovered

I hope that these changes make this a lot cleaner and apparent.

2022-04-11 21:37 UTC, yg-gd commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
> +            @QueryParam("detached") @DefaultValue("false") boolean detached);
references detached

2022-04-11 21:38 UTC, yg-gd approved these changes

2022-04-12 11:39 UTC, kkalvagadda1 requested changes

2022-04-12 11:39 UTC, kkalvagadda1 commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
> +            @QueryParam("detached") @DefaultValue("false") boolean detached);
There is no need for a detached variable.

Whenever updateNameAndCrn is invoked, the originalCrn field can be initialized to retain the old name.

2022-04-12 16:51 UTC, sxxgrc commented
Small update:

- Renamed the `detached` field to `retainOriginalName` field in order to keep the stack update method agnostic to the resize process.

2022-04-13 12:02 UTC, kkalvagadda1 approved these changes

2022-04-20 19:45 UTC, sxxgrc commented
I have now pointed this at being merged into the master branch. Please merge it in as soon as possible so we can start testing with it.

2022-04-21 23:40 UTC, sxxgrc commented
Pointed this at 2.56.0 instead of master.

2022-04-22 18:36 UTC, RokolyA94 approved these changes

2022-04-26 14:08 UTC, merged