CB-16497. Usersync retrieve credentials separately from bulk ums model
hortonworks/cloudbreak pull request #12627
Opened 2022-04-14 04:27 UTC by handavid

GRPC requests have a 1 minute timeout. The UMS bulk user sync state rpc
spends a long time decrypting credentials and may exceed the 1 minute timeout
when retrieving 2500+ actors.

A flag was added to the request to skip credentials retrieval in the bulk rpc.
This commit adds the flag to the GrpcUmsClient and modifies the
BulkUmsUsersStateProvider to retrieve the credentials separately.

See detailed description in the commit message.

2022-04-19 09:53 UTC, lacikaaa requested changes
can this change cause any issues during usersync? if yes I think an entitlement might be useful

2022-04-19 17:19 UTC, handavid commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BulkUmsUsersStateProvider.java
> +    @VisibleForTesting
removed and inlined instead

2022-04-19 17:20 UTC, handavid commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BulkUmsUsersStateProvider.java
> +                // membership.
moved to log

2022-04-19 17:21 UTC, handavid commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/ums/BulkUmsUsersStateProvider.java
> +    static final boolean SKIP_CREDENTIALS = true;
we use many usability constants in the thunderhead repo. I know that IDEA does include the parameter name in the method calls so I removed this.

2022-04-19 17:27 UTC, handavid commented
> can this change cause any issues during usersync? if yes I think an entitlement might be useful

This change will not cause any change in usersync. The resulting `UmsUsersStateModel` from the `BulkUmsUsersStateProvider` will be unchanged comparred to the previous code and compared to the `DefaultUmsUsersStateProvider`. The `BulkUmsUsersStateProviderTest` ensures that the output is correct by using the same test data and verification code as the `DefaultUmsUsersStateProviderTest`.

2022-04-19 17:38 UTC, lacikaaa approved these changes
thanks for the fixes and clarification. lgtm

2022-04-19 22:11 UTC, handavid commented
retest this please

2022-04-20 08:34 UTC, horadla23 approved these changes

2022-04-20 08:34 UTC, merged