CB-16851 CB should not find out role and resource role CRNs but query…
hortonworks/cloudbreak pull request #12635
Opened 2022-04-14 19:32 UTC by horadla23

… them from UMS

See detailed description in the commit message.

2022-04-18 15:02 UTC, bergerdenes requested changes

2022-04-18 15:02 UTC, bergerdenes commented on auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/service/RoleCrnGeneratorTest.java
> +        assertThrows(InternalServerErrorException.class, () -> ThreadBasedUserCrnProvider.doAs(ACTOR, () -> underTest.getRoleCrn("whatever")));
I would put the negative test to a separate method

2022-04-18 15:02 UTC, bergerdenes commented on auth-connector/src/test/java/com/sequenceiq/cloudbreak/auth/altus/service/RoleCrnGeneratorTest.java
> +        assertThrows(InternalServerErrorException.class, () ->
I would put the negative test to a separate method

2022-04-19 07:26 UTC, foldik requested changes
I requested a few changes otherwise it looks good.

2022-04-19 07:26 UTC, foldik commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
> +            response = newStub(requestId).listResourceRoles(UserManagementProto.ListResourceRolesRequest.newBuilder()
Please extract the stub into a local variable and not create a new one every time in a loop.

2022-04-19 07:26 UTC, foldik commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/UmsClient.java
> +            response = newStub(requestId).listRoles(UserManagementProto.ListRolesRequest.newBuilder()
Extract the stub here too.

2022-04-19 07:26 UTC, foldik commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/cache/UmsRolesCache.java
> +    @Value("${altus.ums.roles.cache.ttl:5}")
Please remove the deprecated field and use just `ttlSeconds` with 300 seconds.

2022-04-19 08:28 UTC, bergerdenes approved these changes

2022-04-19 09:16 UTC, foldik approved these changes
LGTM

2022-04-20 05:12 UTC, merged