CB-15964: Validate the availability of the parcel before the upgrade
hortonworks/cloudbreak pull request #12651
Opened 2022-04-20 18:39 UTC by tiborpopovics

Add a new validator for the upgrade validation step to test the availability of the parcels.

The validator should check the following items:
- CDH parcel
- required non CDH parcels
- CM repo files
- CSD files
If the validation fails then the upgrade flow should not be started.

2022-04-25 07:51 UTC, lacikaaa requested changes

2022-04-25 07:51 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeValidationActions.java
> +        return new AbstractClusterUpgradeValidationAction<>(ClusterUpgradeDiskSpaceValidationEvent.class) {
this change would break ongoing flows

2022-04-25 07:51 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/event/ClusterUpgradeDiskSpaceValidationEvent.java
> +    public ClusterUpgradeDiskSpaceValidationEvent(Long resourceId, long requiredFreeSpace) {
this is not used

2022-04-25 07:51 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/event/ClusterUpgradeDiskSpaceValidationEvent.java
> +public class ClusterUpgradeDiskSpaceValidationEvent extends StackEvent {
missing `toString` implementation

2022-04-25 07:51 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/upgrade/validation/ParcelSizeService.java
>                  .filter(size -> !size.equals(0L))
why is this filter necessary?

2022-04-25 07:51 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/service/parcel/ParcelAvailabilityService.java
> +    private Predicate<Map.Entry<String, Optional<Response>>> removeCmRpmFile(String cmRpmUrl) {
misleading name, it doesn't remove anything

2022-04-29 09:09 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/ClusterUpgradeValidationActions.java
> +                super.initPayloadConverterMap(payloadConverters);
why is this call necessary?

2022-04-29 09:10 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/config/ClusterUpgradeValidationEventToClusterUpgradeDiskSpaceValidationEventConverter.java
> +public class ClusterUpgradeValidationEventToClusterUpgradeDiskSpaceValidationEventConverter
please add ut

2022-05-02 12:43 UTC, lacikaaa approved these changes

2022-05-04 08:23 UTC, lnardai commented
Please either fix the job issues or move it back to draft.
Otherwise we'll close it.

2022-05-09 11:13 UTC, oleewere approved these changes
lgtm

2022-05-11 08:35 UTC, merged