CB-16795: Allow encryption at host for FreeIPA and DataLake VM disks in Azure
hortonworks/cloudbreak pull request #12671
Opened 2022-04-24 06:32 UTC by juhi-09

CB-16795: Allow encryption at host for FreeIPA and DataLake VM disks in Azure

If Encryption at Host is enabled for a VM, data stored on the VM host is encrypted at rest and flows encrypted to the Storage service.
This commit would ensure encryption at VM.
Customer needs to enable "encryptionAtHost" feature for all of their subscriptions to use this feature.

See detailed description in the commit message.

2022-05-04 08:22 UTC, lnardai commented
Please either fix the job issues or move it back to draft. 
Otherwise we'll close it.

2022-05-05 11:57 UTC, lajosrodek requested changes

2022-05-05 11:57 UTC, lajosrodek commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/instance/DefaultInstanceGroupProvider.java
> +                        entry(AzureInstanceTemplate.ENCRYPTION_AT_HOST_ENABLED, Boolean.TRUE)));
Can be simplified as
```
attributesJson.put(AzureInstanceTemplate.ENCRYPTION_AT_HOST_ENABLED, Boolean.TRUE);
```

2022-05-10 13:08 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-05-11 08:35 UTC, horadla23 approved these changes

2022-05-11 08:37 UTC, merged