[Hue] - CDPD-32891 - Cloud Break Template change for QP
hortonworks/cloudbreak pull request #12735
Opened 2022-05-10 07:36 UTC by Amlesh1902

Testing: I have done end-to-end testing and found that it's working as expected.

2022-05-10 14:17 UTC, lajosrodek requested changes

2022-05-10 14:17 UTC, lajosrodek commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        Map<String, String> paramToVariable =
Nit: Rename to `configToValue`.

2022-05-10 14:17 UTC, lajosrodek commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        when(mockTemplateProcessor.isRoleTypePresentInService(anyString(), any(List.class))).thenReturn(true);
Like above.

2022-05-11 08:49 UTC, horadla23 commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +import org.junit.Test;
+1

2022-05-12 08:32 UTC, Amlesh1902 commented on core/src/main/resources/defaults/blueprints/7.2.15/cdp-data-engineering.bp
> +        "serviceType": "QUERY_PROCESSOR",
1) "cdp-data-engineering-spark3" - The QP is related to DAS and Hue service, but cdp-data-engineering-spark3 does not have the DAS service. So this is not applicable.
2) "data-engineering-ha.bp" - I will make the change to include QP in this blueprint.

2022-05-12 09:13 UTC, Amlesh1902 commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        Map<String, String> paramToVariable =
acknowledged

2022-05-12 09:13 UTC, Amlesh1902 commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        when(mockTemplateProcessor.isRoleTypePresentInService(anyString(), any(List.class))).thenReturn(true);
acknowledged

2022-05-12 09:13 UTC, Amlesh1902 commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        when(mockTemplateProcessor.isRoleTypePresentInService(anyString(), any(List.class))).thenReturn(false);
acknowledged

2022-05-12 09:14 UTC, Amlesh1902 commented on template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/queryprocessor/QueryProcessorConfigProviderTest.java
> +        when(mockTemplateProcessor.isRoleTypePresentInService(anyString(), any(List.class))).thenReturn(true);
acknowledged

2022-05-12 19:24 UTC, lajosrodek approved these changes
Thanks, LGTM.

2022-05-13 09:23 UTC, biharitomi commented
Please rebase your branch @Amlesh1902 to the latest master.

2022-05-16 07:40 UTC, Amlesh1902 commented
> Please rebase your branch @Amlesh1902 to the latest master.

Done!

2022-05-17 08:09 UTC, lajosrodek commented
@Amlesh1902 Please do not merge `master` into your branch but rather rebase on top of `master`. GitHub still does not allow merging this as of now. Furthermore, the typical preferred approach in this repo is to have only a single commit per PR; this one has 3 due to the 2 extra merge commits. Could you please fix these issues so that this can be finally merged?

2022-05-17 14:58 UTC, Amlesh1902 commented
> @Amlesh1902 Please do not merge `master` into your branch but rather rebase on top of `master`. GitHub still does not allow merging this as of now. Furthermore, the typical preferred approach in this repo is to have only a single commit per PR; this one has 3 due to the 2 extra merge commits. Could you please fix these issues so that this can be finally merged?

Done!

2022-05-17 16:30 UTC, lajosrodek commented
Note: Basically a resubmit of the former #12611.

2022-05-17 16:30 UTC, merged