Cb 16678
hortonworks/cloudbreak pull request #12747
Opened 2022-05-11 15:13 UTC by RokolyA94

JIRA: https://jira.cloudera.com/browse/CB-16678

Refresh DataHub endpoint created. The endpoint can handle specific dataHub by name. If the data hub name is not provided, the API will refresh all datahubs. 

Tested:
DataHub refresh endpoint
DataLake resize flow.

All local tests passed.

2022-05-11 17:34 UTC, kkalvagadda1 requested changes
I have asked you not to use use the datalake flow.  Instead, trigger the DistroxService :: restartAttachedDistroxClusters API and be done. There is no need for a flow in this case.

Customers will track the status of a refresh by checking the status of the DH clusters.

The return value of the new API you introduced will return void.

2022-05-11 17:34 UTC, kkalvagadda1 commented on datalake-api/src/main/java/com/sequenceiq/sdx/api/endpoint/SdxEndpoint.java
> +    SdxClusterResponse refresh(@PathParam("name") String name, @QueryParam("datahubName") String datahubName);
We are not refreshing datalake. We should make it clear here.

Can you change it to refreshDataHubs?
Change the name to datalakeName?

2022-05-11 17:34 UTC, kkalvagadda1 commented on datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
> +    public Pair<SdxCluster, FlowIdentifier> refreshSdx(String clusterName, String datahubName) {
refreshDataHub will be accurate

2022-05-16 08:55 UTC, lnardai commented on datalake/src/main/java/com/sequenceiq/datalake/flow/refresh/event/DatahubRefreshStartEvent.java
> +
Please setup correct code formatting rules described in the README.md

2022-05-16 08:56 UTC, lnardai commented on datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxService.java
> +                        sdxCluster.getInitiatorUserCrn()));
Code formatting here as well.

2022-05-23 21:24 UTC, kkalvagadda1 approved these changes
looks good.

2022-05-25 16:01 UTC, lnardai approved these changes

2022-05-26 06:59 UTC, lacikaaa requested changes
What is refresh? the endpoint doesn't have any description explaining what does this operation do, neither the commit message explains what the purpose of the refresh is and what it should do

2022-05-31 12:03 UTC, lacikaaa approved these changes

2022-06-07 07:08 UTC, merged