CB-17193. Recipes should run only on targeted hosts (during upscale).
hortonworks/cloudbreak pull request #12782
Opened 2022-05-18 16:07 UTC by oleewere

details:
- as we can attach/detach recipes now, it's a possible use case that we have a new recipe that was originally not attached to a host group, but it has been attached later
- in that case a recipe has been attached after deployment, and a scale happens on that host group, the recipe will run on every node on that host group, not only against the scaled one
- without attach/detach recipe feature that did not happened, as recipes have been there already on the nodes, and could not be removed, so on an upscale, recipes only run against the new nodes (as they have been run already on the other nodes during deployment)

See detailed description in the commit message.

2022-05-23 08:23 UTC, lnardai commented
Should be targeted for master.

2022-06-08 10:21 UTC, sodre90 requested changes

2022-06-09 08:29 UTC, oleewere commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
> +                    : stackUtil.collectReachableAndUnreachableCandidateNodes(stack, candidateAddresses.keySet()).getReachableNodes();
i think both collecting the reachable nodes here, see the getReachableNodes() at the end of the longer line

2022-06-14 11:37 UTC, sodre90 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/flow/recipe/OrchestratorRecipeExecutor.java
> +                    : stackUtil.collectReachableAndUnreachableCandidateNodes(stack, candidateAddresses.keySet()).getReachableNodes();
I see! I missed it

2022-06-20 07:33 UTC, oleewere commented
the problem:
- attach a new recipe
- upscale
- new recipe will run on every node
upscale can fail if recipe fails on existing nodes, although you can also assume as a feature to run on every node

2022-06-23 08:25 UTC, sodre90 approved these changes

2022-06-24 07:34 UTC, foldik approved these changes
LGTM

2022-06-24 08:26 UTC, merged