CB-17162: Show warning message when we are unable to read details of the Azure Marketplace image.
hortonworks/cloudbreak pull request #12817
Opened 2022-05-26 19:47 UTC by tiborpopovics

At the beginning of the cluster provision, we're validating that the Terms and Conditions are accepted for the Azure Marketplace image.
To perform this validation we need the Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read permission.
Sometimes the customers are not providing this permission. After this change, we're sending an error message to the customer to make sure that the Terms and Conditions are accepted.

2022-05-31 14:39 UTC, gergopapi2 requested changes

2022-05-31 14:39 UTC, gergopapi2 commented on cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandlerTest.java
> +    void testAcceptShouldSendEventWhenAllValidationWereSuccessfulWhenTheValidatorThrowsWarningMessage() {
I would make this name shorter and leave part  "WhenAllValidationWereSuccessful"

2022-05-31 14:39 UTC, gergopapi2 commented on cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandlerTest.java
> +        underTest.accept(new Event<>(request));
I would add a blank line above.

2022-05-31 14:39 UTC, gergopapi2 commented on cloud-reactor/src/test/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandlerTest.java
> +        underTest.accept(new Event<>(request));
Please add a blank line above.

2022-05-31 14:39 UTC, gergopapi2 commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
> +            String message = String.format(MISSING_READ_PERMISSION_MESSAGE_TEMPLATE, azureMarketplaceImage);
Also, is there anything specific in the AzureRestResponseException that helps find out that there is not enough permission to read the terms and conditions of the image?

2022-05-31 14:39 UTC, gergopapi2 commented on cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/ProvisionValidationHandler.java
> +                }
The try-catch could go into a separate method.

2022-05-31 14:39 UTC, gergopapi2 commented on common/src/main/resources/messages/messages.properties
> +cluster.provider.validation.warning=Some warnings were found during cloud platform validation: {0}
I would reformulate to match the above error message:
"Cloud platform validation succeeded with the following warnings: {0}"

2022-05-31 18:24 UTC, tiborpopovics commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
> +            String message = String.format(MISSING_READ_PERMISSION_MESSAGE_TEMPLATE, azureMarketplaceImage);
There is no specific in the exception. Only the message contains the `403 Forbidden` snippet and the details of the error.

2022-06-01 18:47 UTC, pdarvasi commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
> +    private static final String READ_PROBLEM_MESSAGE_TEMPLATE = "Failed to get the status of the Terms and Conditions for image %s. " +
Ideally, this should be in `messages.properties` instead

2022-06-02 07:35 UTC, keyki approved these changes

2022-06-02 07:36 UTC, sodre90 approved these changes

2022-06-02 07:36 UTC, merged