CB-17308 Adapt SSB DB setup to the new architecture
hortonworks/cloudbreak pull request #12821
Opened 2022-05-31 17:20 UTC by ferenc-csaky

Recently the architecture of `SQL_STREAM_BUILDER` changed and we are bringing this change to Public Cloud with the 7.2.16 release.

The relevant change is the `STREAMING_SQL_CONSOLE` role got removed from the product. Although the rest of the roles are intact. I pointed the Admin DB config condition to `STREAMING_SQL_ENGINE` instead, which will be backward compatible.

Open question is: I renamed the default users and databases for both SSB DB. Could that cause problems for existing environments? My guess was it would not bother already existing workloads and only applied to new cluster provisions, which should work. On our end, definitely but I am not a CB expert.

2022-06-01 07:24 UTC, danmagyar reviewed
LGTM, but I'll leave the approval to someone from @hortonworks/cloudbreak-wolf

2022-06-01 07:33 UTC, bergerdenes requested changes
This change works for 7.2.16 _only_

2022-06-01 07:33 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderSnapperRdsConfigProvider.java
> +        return blueprintProcessor.isCMComponentExistsInBlueprint(SqlStreamBuilderRoles.MATERIALIZED_VIEW_ENGINE);
7.2.16 only. More comment above.

2022-06-01 07:33 UTC, bergerdenes commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/ssb/SqlStreamBuilderAdminDatabaseConfigProvider.java
> +        return List.of(SqlStreamBuilderRoles.STREAMING_SQL_ENGINE, SqlStreamBuilderRoles.MATERIALIZED_VIEW_ENGINE);
7.2.16 only. More comment above.

2022-06-01 07:33 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderSnapperRdsConfigProvider.java
> +    @Value("${cb.ssb.database.mve.db:ssb_mve}")
7.2.16 only. More comment above.

2022-06-01 10:44 UTC, ferenc-csaky commented on core/src/main/java/com/sequenceiq/cloudbreak/service/rdsconfig/SqlStreamBuilderAdminRdsConfigProvider.java
> +        return blueprintProcessor.isCMComponentExistsInBlueprint(SqlStreamBuilderRoles.STREAMING_SQL_ENGINE);
This won't break backward compatibility, the "STREAMING_SQL_ENGINE" role is there since 7.2.11, where we added the service.

2022-06-21 12:38 UTC, ferenc-csaky commented
IMO it is not necessary to introduce a CR version check for the `@Value` fields in the config providers. I just changed the default value, which will work with older versions as well.

2022-06-21 12:39 UTC, bergerdenes commented
I still think your change is not backward compatible, i.e. removed/renamed some config properties without any condition regarding the runtime version.

2022-06-22 15:18 UTC, ferenc-csaky commented
> I still think your change is not backward compatible, i.e. removed/renamed some config properties without any condition regarding the runtime version.

In the latest version only the default value of the properties changed and some spring component class names. Latter should not make any difference.

For the props, I think for any existing cluster will not be harmed by that (it was already populated) and saved to CM. And any new cluster will be able to spin up with the new values as well, after this code will be applied.

The only other change I made was replacing the `STREAMING_SQL_CONSOLE` with the `STREAMING_SQL_ENGINE` role. The latter role existis since the beginning of this product, so this should not make a difference as well.

I would try to avoid to introduce complexity if it is not necessary.

2022-07-25 20:12 UTC, bergerdenes approved these changes
As discussed please test cluster creation with 7.2.11 Flink cluster. If your test fails at any point with root cause of this current change, please revert.

2022-07-25 20:12 UTC, merged