CB-17223 deleteVolumes flag should be introduced for SDX repair
hortonworks/cloudbreak pull request #12830
Opened 2022-06-02 09:14 UTC by horadla23

See detailed description in the commit message.

2022-06-03 07:39 UTC, foldik approved these changes
LGTM

2022-06-07 07:16 UTC, lacikaaa requested changes

2022-06-07 07:16 UTC, lacikaaa commented on datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
> +            nodes.setDeleteVolumes(sdxRepairSettings.isDeleteVolumes());
I would expect some unit test changes

2022-06-07 07:28 UTC, horadla23 commented on datalake/src/main/java/com/sequenceiq/datalake/service/sdx/SdxRepairService.java
> +            nodes.setDeleteVolumes(sdxRepairSettings.isDeleteVolumes());
done

2022-06-07 07:29 UTC, lacikaaa approved these changes

2022-06-07 08:32 UTC, merged