CB-14886. Run metering checks as part of preflight checks during depl…
hortonworks/cloudbreak pull request #12847
Opened 2022-06-07 11:46 UTC by oleewere

…oyment/diagnostics

details:
- update usage.proto and regenerate java classes
- extends diagnostics flow service to run metering checks
- outputs are gathered and logged, also a cdp diagnostics usage is sent based on the results

See detailed description in the commit message.

2022-06-07 12:19 UTC, oleewere commented
retest

2022-06-09 00:45 UTC, vaibhavgandhi12 reviewed
Looks like a great start. I would love to see this run periodically, eventually.

2022-06-09 00:45 UTC, vaibhavgandhi12 commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
> +                        diagnosticsEventBuilder.setResult(UsageProto.CDPDiagnosticResult.Value.UNSET);
Don't send this if there is no issue.

2022-06-09 14:32 UTC, lnardai approved these changes

2022-06-09 19:15 UTC, vaibhavgandhi12 approved these changes
lgtm!

2022-06-10 07:29 UTC, nadamdb approved these changes
LGTM

2022-06-10 08:35 UTC, merged

2022-06-10 08:41 UTC, lacikaaa requested changes

2022-06-10 08:41 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
> +            }
please don't do empty returns, use else and refactor your code please

2022-06-10 08:41 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/diagnostics/DiagnosticsFlowService.java
> +                            "DataBus test response", errorSet);
this seems a bit C style, would be more object oriented if you would have like an interface/abstract class with multiple implementation all of which would be called and could be injected by spring framework

2022-06-10 08:42 UTC, lacikaaa commented
as this is merged please fix these in a followup