CB-15512 Set DeleteOnTermination to false on repair explicitly for AWS
hortonworks/cloudbreak pull request #12853
Opened 2022-06-08 12:15 UTC by bbihari

DeleteOnTermination default value is false for attached disks.
BUT if somebody sets DeleteOnTermination to true by mistake, then the repair will fail because it will delete the original instance with volumes.

This change sets the DeleteOnTermination flag to false with an explicit AWS call.

2022-06-09 08:25 UTC, sodre90 approved these changes

2022-06-10 07:17 UTC, tiborpopovics approved these changes

2022-06-10 08:45 UTC, lacikaaa requested changes
looks like this change doesn't involve any UT changes. could you add some UT?

2022-06-10 13:14 UTC, lacikaaa approved these changes

2022-06-13 15:12 UTC, merged