CB-17184 Extend already existing FreeIPA provisioning testcase with recipes
hortonworks/cloudbreak pull request #12868
Opened 2022-06-10 10:07 UTC by aszegedi

Extending already existing FreeIPA provisioning E2E test cases with recipe related steps and validations.

2022-06-16 09:19 UTC, sodre90 requested changes

2022-06-16 12:04 UTC, aszegedi commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
> +            LOGGER.info("Checking generated file(s) by recipe at datalake instance(s) ({}) on '{}' path by '{}' name!", testDto.getCrn(), filePath,
Actually these are not duplicates. 
- `Log.log`: appears only in HTML result reports and wont appear on the Console logs
- `LOGGER.info`: appears only on Console logs

2022-06-16 12:40 UTC, sodre90 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
> +            LOGGER.info("Checking generated file(s) by recipe at datalake instance(s) ({}) on '{}' path by '{}' name!", testDto.getCrn(), filePath,
As I checked the code it should log also on console.

2022-06-16 13:40 UTC, aszegedi commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
> +            LOGGER.info("Checking generated file(s) by recipe at datalake instance(s) ({}) on '{}' path by '{}' name!", testDto.getCrn(), filePath,
Actually this is going on the https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java#L44 path. So after this https://github.com/hortonworks/cloudbreak/blob/master/integration-test/src/main/java/com/sequenceiq/it/cloudbreak/log/Log.java#L44 here is the https://www.javadoc.io/doc/org.testng/testng/7.3.0/org/testng/Reporter.html#log(java.lang.String) log.

2022-06-16 15:13 UTC, aszegedi commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/assertion/datalake/RecipeTestAssertion.java
> +            LOGGER.info("Checking generated file(s) by recipe at datalake instance(s) ({}) on '{}' path by '{}' name!", testDto.getCrn(), filePath,
You were right! So I've fixed this.

2022-06-17 07:43 UTC, sodre90 approved these changes

2022-06-21 07:43 UTC, merged