CB-17454 The GCP image discover was not work properly.
hortonworks/cloudbreak pull request #12889
Opened 2022-06-15 12:16 UTC by topolyai5

We fetch all image but the Google respond with the first 500. If the image was not in the list we copied even if the image already exists. Now we try to fetch by image name and project id

See detailed description in the commit message.

2022-06-16 09:51 UTC, lajosrodek requested changes
Actually, perhaps it would be beneficial to update the associated UT as well. :stuck_out_tongue:

2022-06-20 11:04 UTC, biharitomi approved these changes

2022-06-20 12:32 UTC, lajosrodek approved these changes
Only one minor comment. Approving in advance, it is also okay to be fixed in a later PR. LGTM

2022-06-20 12:32 UTC, lajosrodek commented on cloud-gcp/src/test/java/com/sequenceiq/cloudbreak/cloud/gcp/setup/GcpProvisionSetupTest.java
>  import org.junit.Assert;
Should be migrated to its JUnit 5 equivalent (`org.junit.jupiter.api.Assertions` that is already imported above statically).

2022-06-21 08:00 UTC, merged