CB-17474: Added flow to beginning of DL resize which validates if Atlas is up to date.
hortonworks/cloudbreak pull request #12917
Opened 2022-06-21 22:39 UTC by sxxgrc

Jira: https://jira.cloudera.com/browse/CB-17474

The objective is to use the salt changes from CB-17112 to have an automatic flow step at the beginning of resize, which will verify if Atlas is up to date before continuing with the resize.
In the case that Atlas is not up to date, the flow will wait for a specified time until it is up to date or the process times out.

This change consists of:

1. Flow changes within the Datalake code which is accompanied by the expected addition to the resize flow chain
2. Flow changes in the Cloudbreak core code, which is exposed via a stackv4endpoint method
3. New logic in cloudbreak core which generates the salt configuration needed for the Atlas salt changes to run

Please note that I am new to these changes and am making a lot of assumptions, specifically basing all of my changes off the backup/restore changes. So if there is anything incorrect or something that could be better, please let me know and I will make the modification.

2022-06-30 19:53 UTC, sxxgrc commented
Local testing has been successful so I am moving this to a real PR.

2022-07-11 15:59 UTC, kkalvagadda1 commented on core-api/src/main/java/com/sequenceiq/cloudbreak/doc/OperationDescriptions.java
> +        public static final String CHECK_ATLAS_UPDATED = "Checks if the Atlas service on the cluster is up to date with recent lineage changes.";
How about "Checks if the Atlas service on the cluster is up to date with the lineage.";

2022-07-19 08:26 UTC, horadla23 commented
please use draft PR instead of "waiting-for-test" label if it is not ready to merge

2022-07-19 15:26 UTC, sxxgrc commented
I apologize @horadla23 that label should have been removed over a week ago. This is ready to be reviewed although an ongoing conversation about this is occurring within the Jira comments.
Feel free to look at the comments to better understand the discussion before making a review.

2022-07-22 18:33 UTC, RokolyA94 approved these changes
LGTM

2022-07-25 10:48 UTC, lnardai requested changes
See discussion on CB ticket

2022-07-25 10:48 UTC, doktoric requested changes
[CB-17474](https://jira.cloudera.com/browse/CB-17474) where this discussion happening

2022-09-12 14:38 UTC, akanto requested changes
I don't understand this pull request, I think we have clearly explained in the jira that we will not accept this and this should be part of the CM, since Atlas management is not the task of Cloudbreak and we deal with infra only.

https://jira.cloudera.com/browse/CB-17474?focusedCommentId=5343564&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-5343564

2022-09-12 15:57 UTC, closed without merging