CDPCP-7442. Usersync set crn in metadata on user_add
hortonworks/cloudbreak pull request #12991
Opened 2022-07-06 08:36 UTC by handavid

Each actor's CRN is stored in the title field of the FreeIPA user
as part of the metadata that is updated when credentials are set. This
process left a time gap between user creation and when the CRN was
added to the user.

This commit elimiates that time gap by setting the CRN in thte title
field upon user creation in FreeIPA.

See detailed description in the commit message.

2022-07-06 12:22 UTC, lacikaaa requested changes

2022-07-06 12:22 UTC, lacikaaa commented on freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserAddOperation.java
> +        if (title.isPresent()) {
nit: you could use `ifpresent`

2022-07-06 12:22 UTC, lacikaaa commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
> +        if (userMetadata.isPresent()) {
nit: you could use `ifpresent`

2022-07-07 01:01 UTC, handavid commented on freeipa-client/src/main/java/com/sequenceiq/freeipa/client/operation/UserAddOperation.java
> +        if (title.isPresent()) {
done

2022-07-07 01:01 UTC, handavid commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/FreeIpaUsersStateProvider.java
> +        if (userMetadata.isPresent()) {
done

2022-07-07 01:01 UTC, handavid commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/freeipa/user/conversion/FmsUserConverter.java
> +                umsUser.getCrn());
updated unit tests

2022-07-11 09:37 UTC, horadla23 approved these changes

2022-07-11 09:37 UTC, merged