CB-16558 - Reduce the size of structuredevent and cdp_structured_event tables
hortonworks/cloudbreak pull request #12990
Opened 2022-07-06 03:49 UTC by gregito

2022-07-08 10:14 UTC, bergerdenes commented on cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
> +import org.apache.commons.codec.binary.Base64;
Please set a correct formatter, see for example line 35 should not be after these imports.
Please use the one included with the project itself

2022-07-08 10:27 UTC, bergerdenes requested changes
some small items

2022-07-08 10:27 UTC, bergerdenes commented on cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/common/TestUtil.java
> +        //        network.setAddressPrefixCIDR(DUMMY_ADDRESS_PREFIX_CIDR);
dead code

2022-07-08 10:27 UTC, bergerdenes commented on cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/service/clustercomponent/ClusterComponentConfigProviderTestBase.java
> +        MockitoAnnotations.openMocks(this);
Please use @ExtendWith on class if possible

2022-07-08 10:27 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpService.java
> +                    String.join(",", idsForChecking.stream().map(Object::toString).collect(toSet())));
I think (but you an experiment as well) that if you have a Set type variable and you call toString() on it, that will produce the same (or similar) result, good enough for logging.

2022-07-08 10:27 UTC, bergerdenes commented on core/src/test/java/com/sequenceiq/cloudbreak/service/cluster/flow/ClusterTerminationServiceTest.java
> +    void testCleanUpClusterComponentsWhen() throws TransactionExecutionException {
when? ...

2022-07-21 06:48 UTC, topolyai5 requested changes

2022-07-21 06:48 UTC, topolyai5 commented on cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
> +        Set<ClusterComponentHistory> detachedEntries = clusterComponentHistoryRepository.findDetachedEntries();
unnecessary to fetch the all of the cluster component to check the count. Could you please refactor this?

2022-07-21 08:13 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
> +        List<StructuredEventEntity> events = repository.findByWorkspaceAndEventType(workspace, StructuredEventType.getByClass(eventClass));
why do you rename it?

2022-07-21 08:53 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
> +    private static final int THREE_MONTHS = 86400 * 30 * 3;
Could you please try this with Duration(3, MONTH) or stuff like this

2022-07-21 10:35 UTC, topolyai5 commented on cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
> +            long deleted = clusterComponentHistoryRepository.deleteByClusterIsNullOrCluster_StatusIs(DELETE_COMPLETED);
we don't use the underscore, could you please replace it with `And`?

2022-07-26 11:43 UTC, bergerdenes requested changes

2022-07-26 11:43 UTC, bergerdenes commented on cluster-api/src/main/java/com/sequenceiq/cloudbreak/cluster/service/ClusterComponentConfigProvider.java
> +import org.apache.commons.codec.binary.Base64;
the import order is _still_ incorrect. please update your format for jJava as attached in the project under `config/idea/idea_settings.jar`

2022-07-26 11:43 UTC, bergerdenes commented on cluster-api/src/test/java/com/sequenceiq/cloudbreak/cluster/service/clustercomponent/ClusterComponentConfigProviderTestBase.java
> +        underTest = new ClusterComponentConfigProvider(mockComponentRepository, mockComponentViewRepository, mockClusterComponentHistoryRepository,
`@InjectMocks` ?

2022-07-26 11:43 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
> +    private Long getTimestampThatThreeMonthsFromNow() {
Misleading naming as the returned value is 3 months _before_ now

2022-07-26 11:43 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
> +    public void deleteEntriesForTenantThatIsOlderThanThreeMonths(String tenantName) {
Misleading naming: the `tenantName` is actually the `accountId`

2022-07-26 11:43 UTC, bergerdenes commented on core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpServiceTest.java
> +        MockitoAnnotations.openMocks(this);
@ExtendWith

2022-07-26 11:43 UTC, bergerdenes commented on core/src/test/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpServiceTest.java
> +    private FinalizationCleanUpService underTest;
@InjectMocks

2022-07-26 11:43 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/stack/flow/FinalizationCleanUpService.java
> +    public void cleanUpStructuredEventsForTenant(String tenantName) {
`tenantName` is misleading here, it should be `accountId`

2022-07-26 11:43 UTC, bergerdenes commented on cluster-api/src/main/java/com/sequenceiq/cloudbreak/repository/ClusterComponentHistoryRepository.java
> +public interface ClusterComponentHistoryRepository extends CrudRepository<ClusterComponentHistory, Long> {
I don't really get this class, neither the ClusterComponentHistory.
It is a brand new entity, what is going to fill it? If it did not exist before, why is it needed to clean it up?

2022-07-26 15:54 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/structuredevent/db/LegacyStructuredEventDBService.java
> +        List<StructuredEventEntity> events = repository.findByWorkspaceAndEventType(workspace, StructuredEventType.getByClass(eventClass));
I guess it looks more reasonable :)

2022-07-26 15:54 UTC, bergerdenes approved these changes

2022-07-27 07:12 UTC, merged