CB-17714 Support in Persister to allocate the Resources in batch inst…
hortonworks/cloudbreak pull request #13014
Opened 2022-07-11 18:44 UTC by topolyai5

…ead of one by one

See detailed description in the commit message.

2022-07-12 07:18 UTC, bergerdenes requested changes

2022-07-12 07:18 UTC, bergerdenes commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
> +        verify(persistenceNotifier, times(2)).notifyAllocations(
should be `times(1)`?

2022-07-12 07:18 UTC, bergerdenes commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
> +        verify(persistenceNotifier, times(2)).notifyAllocations(
should be `times(1)`?

2022-07-12 07:18 UTC, bergerdenes commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsRepairTest.java
> +        verify(resourceNotifier, times(2)).notifyUpdates(updatedCloudResourceArgumentCaptor.capture(), any());
should be `times(1)`?

2022-07-12 07:18 UTC, bergerdenes commented on cloud-reactor-api/src/main/java/com/sequenceiq/cloudbreak/cloud/event/resource/LaunchLoadBalancerResult.java
> +public class  LaunchLoadBalancerResult extends CloudPlatformResult {
extra space

2022-07-12 07:18 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java
> +            LOGGER.debug("There are {} resource(s) which won't save", cloudResources.size() - resources.size());
won't be saved

2022-07-12 07:18 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java
> +        LOGGER.debug("There are deleted {} resource(s)", deleted.get());
There are {} deleted resource(s)

2022-07-12 07:18 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/eventbus/CloudResourcePersisterService.java
> +            LOGGER.debug("{} and {} is already exists in DB for stack.", id, cloudResource.getType());
~~is~~

2022-07-12 07:18 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/resourcepersister/CloudResourcePersisterService.java
> +        LOGGER.debug("There are deleted {} resource(s)", deleted.get());
There are {} deleted resource(s)

2022-07-12 07:18 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/resourcepersister/ResourceRepository.java
> +    @Query("DELETE FROM Resource r WHERE  r.resourceReference = :resourceReference AND r.resourceType = :type")
extra space

2022-07-12 07:18 UTC, bergerdenes commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/CloudResourcePersisterService.java
> +            LOGGER.debug("There are {} resource(s), these will not save", cloudResources.size() - resources.size());
will not be saved

2022-07-12 07:18 UTC, bergerdenes commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/CloudResourcePersisterService.java
> +        LOGGER.debug("There are deleted {} resource(s)", deleted.get());
There are {} deleted resource(s)

2022-07-12 07:18 UTC, bergerdenes commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/cloud/CloudResourcePersisterService.java
> +            LOGGER.debug("{} and {} is already exists in DB for stack.", id, cloudResource.getType());
~~is~~

2022-07-12 07:18 UTC, bergerdenes commented on redbeams/src/main/java/com/sequenceiq/redbeams/service/cloud/CloudResourcePersisterService.java
> +                        LOGGER.debug("{} and {} is already exists in DB for stack.", cr.getName(), cr.getType());
~~is~~

2022-07-12 07:18 UTC, bergerdenes commented on redbeams/src/main/java/com/sequenceiq/redbeams/service/cloud/CloudResourcePersisterService.java
> +            LOGGER.debug("There are {} resource(s), these will not save", cloudResources.size() - resources.size());
will not be saved

2022-07-12 08:54 UTC, topolyai5 commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/component/AwsLaunchTest.java
> +        verify(persistenceNotifier, times(2)).notifyAllocations(
nope, it is green

2022-07-13 14:06 UTC, bergerdenes approved these changes

2022-07-13 14:06 UTC, merged