CB-17735: Generate event when resize is complete.
hortonworks/cloudbreak pull request #13026
Opened 2022-07-12 22:14 UTC by kkalvagadda1

See detailed description in the commit message.

2022-07-13 13:21 UTC, RokolyA94 approved these changes

2022-07-14 06:56 UTC, bergerdenes requested changes

2022-07-14 06:56 UTC, bergerdenes commented on flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java
> +    public boolean isFlowTriggeredByFlowChain(String flowChainType, FlowLogWithoutPayload lastFlowLog) {
test?

2022-07-22 13:16 UTC, lnardai approved these changes
unit test then we are good to go.

2022-07-25 18:10 UTC, kkalvagadda1 commented on flow/src/main/java/com/sequenceiq/flow/service/flowlog/FlowChainLogService.java
> +    public boolean isFlowTriggeredByFlowChain(String flowChainType, FlowLogWithoutPayload lastFlowLog) {
Added unit test for the same

2022-07-25 19:49 UTC, bergerdenes requested changes

2022-07-25 19:49 UTC, bergerdenes commented on flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowChainLogServiceTest.java
> +        lenient().when(flowLog.getFlowChainId()).thenReturn("chainId");
why lenient? it is a concrete test

2022-07-26 13:08 UTC, kkalvagadda1 commented on flow/src/test/java/com/sequenceiq/flow/service/flowlog/FlowChainLogServiceTest.java
> +        lenient().when(flowLog.getFlowChainId()).thenReturn("chainId");
fixed.

2022-07-26 13:16 UTC, bergerdenes approved these changes

2022-07-26 14:12 UTC, merged