CB-17571 - Implement core RDS upgrade flow skeleton required on Azure
hortonworks/cloudbreak pull request #13039
Opened 2022-07-14 15:27 UTC by pdarvasi

This commit:
 - implements the wire of the core RDS upgrade flow
 - implements the business logic of the `backupRds` and `restoreRds` actual flow steps
 - implements stackV4 and distroX upgradeRds endpoints

What is yet to come
 - business logic of the `stop` and `start` and `upgradeRds` actual flow steps
 - Return RDS engine version via Redbeams API

The related tasks:
[CB-17761](https://jira.cloudera.com/browse/CB-17761)	Implement database upgrade by replacing the RDS	
[CB-17762](https://jira.cloudera.com/browse/CB-17762)	Return RDS engine version via Redbeams API	
[CB-17763](https://jira.cloudera.com/browse/CB-17763)	Implement stop and start flow steps	

<img width="508" alt="FD499299-ECA0-477A-A0E8-DC33D1862AAB" src="https://user-images.githubusercontent.com/19725708/179019217-0bb850f7-8388-4317-9e6e-bb4d1c502335.png">

2022-07-15 09:01 UTC, horadla23 requested changes

2022-07-15 09:01 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
> +public class UpgradeRdsService {
UT would be nice for this

2022-07-15 20:42 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
> +    }
These are not intended for public consumption.

2022-07-15 21:23 UTC, horadla23 commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/rds/upgrade/UpgradeRdsService.java
> +    }
👍

2022-07-15 21:24 UTC, horadla23 approved these changes

2022-07-19 07:08 UTC, doktoric commented on core/src/main/java/com/sequenceiq/cloudbreak/service/database/DatabaseService.java
> +    public StackDatabaseServerResponse getDatabaseServer(NameOrCrn nameOrCrn) {
unit test would be great here

2022-07-19 08:01 UTC, bergerdenes requested changes
Minor stuff

2022-08-02 07:44 UTC, bergerdenes commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/endpoint/v4/stacks/StackV4Endpoint.java
> +            @NotEmpty @ValidCrn(resource = CrnResourceDescriptor.USER) @QueryParam("initiatorUserCrn") String initiatorUserCrn);
@horadla23 do you think MACHINE_USER is needed here, too?

2022-08-02 07:44 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/v4/StackV4Controller.java
> +            TargetMajorVersion targetMajorVersion, @InitiatorUserCrn @NotEmpty @ValidCrn(resource = CrnResourceDescriptor.USER) String initiatorUserCrn) {
@horadla23 same here

2022-08-02 07:50 UTC, bergerdenes approved these changes

2022-08-02 07:50 UTC, merged