CB-17788. Add new remote_exec api for utils API.
hortonworks/cloudbreak pull request #13094
Opened 2022-07-20 18:29 UTC by oleewere

details:
- add remote_exec api to both core and freeipa
- disable feature by flag, that setting should be the default
- this featue should be only used for testing purposes in order to run specific commands on all or filtered hosts (filter by host or host group)

See detailed description in the commit message.

2022-07-21 13:16 UTC, bergerdenes commented
I am not sure this would pass a security review...

2022-07-21 13:19 UTC, aszegedi approved these changes

2022-07-21 13:21 UTC, oleewere commented
> I am not sure this would pass a security review...

you can read in the commit message -> that is something that is used for qe / testing environments (+ the api is not open btw)

2022-07-21 15:10 UTC, aszegedi requested changes
Is the use of `CRN` is possible instead of the `Long stackId`? 

For example:
- in case of FreeIpa: `String environmentCrn`
- in other cases: `String resourceCrn`

2022-07-21 15:27 UTC, aszegedi approved these changes

2022-07-25 09:40 UTC, biharitomi requested changes

2022-07-25 09:40 UTC, biharitomi commented on common-model/src/main/java/com/sequenceiq/common/api/command/RemoteCommandsExecutionRequest.java
> +public class RemoteCommandsExecutionRequest {
There is no ApiModelProperty and validator annotations on the request object. Could you please add them?

2022-07-25 09:40 UTC, biharitomi commented on orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
> +        Target<String> hosts = new HostList(nodes.stream().map(Node::getHostname).collect(Collectors.toSet()));
Can we have logs that we trying to execute what commands on which nodes?

2022-07-25 09:40 UTC, biharitomi commented on orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/SaltOrchestrator.java
> +            LOGGER.info("Error occurred during command execution: " + command, e);
This could be on `WARN` level

2022-07-26 08:54 UTC, biharitomi approved these changes

2022-07-26 08:54 UTC, merged