CB-17836 - Roll forward sync fails after upgrade because of cloudera-…
hortonworks/cloudbreak pull request #13106
Opened 2022-07-22 10:04 UTC by pdarvasi

…manager-server version consistency validation

This commit:
 - removes CM server and agent consistency check as there might be
different server versions in the CM Server and the other nodes
 - introduces parameter for multiple version consistency check for the
same reason

See detailed description in the commit message.

2022-07-22 15:03 UTC, nadamdb requested changes

2022-07-22 15:31 UTC, pdarvasi commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/PackageName.java
>      public String toString() {
I've left it out on purpose as it is quite an implementation detail, do you insist on putting it there?

2022-07-22 15:40 UTC, nadamdb commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/PackageName.java
>      public String toString() {
If it was intentional it's fine by me

2022-07-22 15:41 UTC, nadamdb approved these changes
LGTM

2022-07-25 13:59 UTC, lnardai commented
Change is unrelated to the test failure, going to merge this.

Failed Tests: 1 (+1)
mock-tests / newway mock testcases
[com.sequenceiq.it.cloudbreak.testcase.mock.EnvironmentStartStopTest.testCreateStopStartEnvironment](http://ci-cloudbreak.eng.hortonworks.com/job/cloudbreak-pull-request-builder-integration-test/26424/testngreports/com.sequenceiq.it.cloudbreak.testcase.mock/EnvironmentStartStopTest/testCreateStopStartEnvironment)

2022-07-25 14:00 UTC, merged