[CB-17903] check that that the instance being added to an AWS target
hortonworks/cloudbreak pull request #13212
Opened 2022-08-08 21:58 UTC by yg-gd

group is actually a member of that group before assignment

note the previous dead parameter in getInstanceIdsForGroups

2022-08-09 21:14 UTC, kkalvagadda1 commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtilTest.java
> +        //when(underTest.getCfStackName(authenticatedContext)).thenReturn("teststack-12");
Let's delete the commented code.

2022-08-09 21:14 UTC, kkalvagadda1 requested changes

2022-08-09 21:14 UTC, kkalvagadda1 commented on cloud-aws-cloudformation/src/test/java/com/sequenceiq/cloudbreak/cloud/aws/CloudFormationStackUtilTest.java
> +
Can you add a success case as well?

2022-08-09 21:15 UTC, kkalvagadda1 approved these changes

2022-08-15 09:05 UTC, topolyai5 approved these changes

2022-08-15 13:03 UTC, merged