CB-18041 : Removed vmagent related code
hortonworks/cloudbreak pull request #13224
Opened 2022-08-10 09:05 UTC by szabolcs-horvath

See detailed description in the commit message.

2022-08-10 11:47 UTC, foldik approved these changes
LGTM

2022-08-10 13:50 UTC, oleewere approved these changes

2022-08-10 20:07 UTC, oleewere requested changes

2022-08-10 20:07 UTC, oleewere commented on common/src/main/java/com/sequenceiq/cloudbreak/telemetry/TelemetryUpgradeConfiguration.java
> -    private TelemetryComponentUpgradeConfiguration cdpVmAgent;
sorry one thing that i have missed, this config is referenced here as well: https://github.com/hortonworks/cloudbreak/blob/master/common/src/main/resources/common-config.yml#L88

2022-08-11 08:09 UTC, oleewere approved these changes

2022-08-12 08:45 UTC, lacikaaa requested changes
could you please elaborate in the commit message a bit more? the jira task has a good description, you can copy that one

2022-08-12 14:30 UTC, lacikaaa commented
Editing github pr description is not the same as commit message. Please override your commit message with the `git --amend` command and then force push your branch

2022-08-15 07:51 UTC, lacikaaa approved these changes

2022-08-15 07:51 UTC, merged