CB-18057 Aggregate storage consumption collection jobs
hortonworks/cloudbreak pull request #13243
Opened 2022-08-15 16:21 UTC by nadamdb

See detailed description in the commit message.

2022-08-18 18:21 UTC, lajosrodek commented
Was not this rather supposed to be for [CB-18043](https://jira.cloudera.com/browse/CB-18043)? :smile:

2022-08-19 07:52 UTC, nadamdb commented
> Was not this rather supposed to be for [CB-18043](https://jira.cloudera.com/browse/CB-18043)? 😄

Good catch, thanks, I corrected the PR title and commit message 😄

2022-08-19 08:35 UTC, horadla23 reviewed
regarding controller change, lgtm

2022-08-19 14:54 UTC, doktoric commented on cloud-consumption/src/main/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializer.java
> +            LOGGER.info("Starting stoage consumption collection job initialization.");
stoage -> storage

2022-08-19 14:56 UTC, doktoric approved these changes

2022-08-22 14:47 UTC, lajosrodek requested changes

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/main/java/com/sequenceiq/consumption/service/ConsumptionService.java
> +            LOGGER.info("Could not determine bucket name from '{}'.", storageLocation);
Why not use the same log from lines 133-134?

```
            LOGGER.error("Cannot extract bucket name from storage location '{}' as it's not a valid S3 location. Reason: {}",
                    storageLocation, e.getMessage(), e);
```

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/flow/consumption/storage/handler/StorageConsumptionCollectionHandlerTest.java
> +        doNothing().when(cloudStorageLocationUtil).validateCloudStorageType(FileSystemType.S3, VALID_STORAGE_LOCATION);
Nit: `doNothing()` is usually not needed because it is the default behavior for `void` return type methods.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobInitializerTest.java
> +        verify(jobService, times(2)).schedule(longCaptor.capture());
Perhaps rename `longCaptor` to `jobIdCaptor`.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
> +        lenient().when(storageConsumptionConfig.getIntervalInMinutes()).thenAnswer(invocation -> 30);
Why not `thenReturn()`? `thenAnswer()` is typically employed when the answer depends on the actual arg values of the called method, or when the answer is constructed dynamically.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
> +        assertEquals("2", jobDetailCaptor.getValue().getKey().getName());    }
Closing `}` should be put into a separate line with the right indentation.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
> +        when(jobResource.getLocalId()).thenAnswer(invocation -> id.toString());
Again, `thenReturn()` would be sufficient.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/job/storage/StorageConsumptionJobServiceTest.java
> +        doReturn(null).when(scheduler).getJobDetail(argThat((JobKey jobkey) -> id.toString().equals(jobkey.getName())));
I think `doReturn(null)` is the default behavior when the return type is not a primitive type, array or collection.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/service/ConsumptionServiceTest.java
> +        doNothing().when(cloudStorageLocationUtil).validateCloudStorageType(FileSystemType.S3, "s3_location");
Like above, this is typically the default behavior for `void` return type methods.

2022-08-22 14:47 UTC, lajosrodek commented on cloud-consumption/src/test/java/com/sequenceiq/consumption/service/ConsumptionServiceTest.java
> +    public void testFindAllConsumption() {
Possibly to be renamed if `underTest.findAllConsumption()` gets renamed. :smile:

2022-08-22 16:17 UTC, nadamdb commented on cloud-consumption/src/main/java/com/sequenceiq/consumption/configuration/repository/ConsumptionRepository.java
> +    List<Consumption> findAllConsumption();
consumption type filtering was left in the query by mistake

2022-08-22 16:21 UTC, nadamdb commented on cloud-consumption/src/main/java/com/sequenceiq/consumption/service/ConsumptionService.java
> +                    .filter(consumption -> environmentCrn.equals(consumption.getEnvironmentCrn()))
Good catch, removed the filtering.

2022-08-23 09:38 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-08-23 09:40 UTC, merged