CB-18121. Refactor salt pillar generation for telemetry related compo…
hortonworks/cloudbreak pull request #13280
Opened 2022-08-22 18:46 UTC by oleewere

…nents.

details:
- instead of passing more and more parameters for configuration services, pass only a global telemetry context
- telemetry context contains other contexts (used as config service inputs) and can be filled with the config view output
- salt decorator is moved to telemetry-common, the decorator has a new reference called telemetry context provider which needs to be implemented on core/freeipa side (that's the main logic to generate the input for the decorators)
- config view generation can be skipped for different states based on the isEnabled method implementation of the telemetry context provider
- refactor TelemetryDecorator and TelemetryConfigService based on the new changes
- added UTs
Also including a few new changes as config generation was refactored:
- consider cm auto tls feature for SMON prometheus settings (default will be true if the value empty in the pillar)
- added paas url + internal url options - these will fallback to the original monitoring urls (fallback happens on metricsClient side as well)
- pass access key type to monitoring + diagnostics (it has been already passwd for databus) - also add access key type field for Databus/Monitoring credentials
- create CdpCredential object that will be the parent of DataBusCredential and MonitoringCredential (helps for refactor or for future refactor)

See detailed description in the commit message.

2022-08-23 13:00 UTC, horadla23 approved these changes

2022-08-23 13:25 UTC, oleewere commented
retest this

2022-08-25 09:18 UTC, foldik approved these changes
LGTM

2022-08-25 10:01 UTC, lacikaaa requested changes

2022-08-25 10:11 UTC, foldik commented on orchestrator-salt/src/main/resources/salt-common/salt/filecollector/settings.sls
> +{% endif %}
+1

2022-08-25 10:33 UTC, oleewere commented on metrics-client/src/main/java/com/sequenceiq/cloudbreak/metrics/processor/MetricsRecordRequest.java
> +    private final boolean saas;
no but inputs logged so skipping that in the fix

2022-08-25 10:46 UTC, oleewere commented
review changes done but i put back this to draft as logic is not really changed but the the change is so critical i need to manually retest every use case

2022-08-31 14:06 UTC, lacikaaa approved these changes

2022-09-06 08:28 UTC, merged