CB-18495 Fix unfinished FreeIPA statuReason
hortonworks/cloudbreak pull request #13386
Opened 2022-09-09 10:45 UTC by agov

Do not append comma and space to status, unless there is a second part to be added.

Fixes statusReason to be returned as below:
`statusReason: "FreeIpa is UNREACHABLE, "`

2022-09-09 10:53 UTC, lacikaaa requested changes

2022-09-09 10:53 UTC, lacikaaa commented on freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
> +            if (statusCheckPair.getSecond() != null && statusCheckPair.getSecond() != "") {
you should use `StringUtils#isNotBlank`

2022-09-12 08:16 UTC, agov commented on freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
> +            if (statusCheckPair.getSecond() != null && statusCheckPair.getSecond() != "") {
Thanks for the tip, updated

2022-09-12 08:36 UTC, lacikaaa approved these changes

2022-09-13 08:24 UTC, merged