CB-18482 Create flow in environment service for proxy edit
hortonworks/cloudbreak pull request #13464
Opened 2022-09-21 10:22 UTC by Bajzathd

Currently the only meaningful step is to save the new proxy association to the db, additional steps will be added in subsequent tickets.

See detailed description in the commit message.

2022-09-22 14:15 UTC, pkedvessy approved these changes

2022-09-23 12:29 UTC, bergerdenes requested changes

2022-09-23 12:29 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/config/EnvProxyModificationFlowConfig.java
> +                    .event(EnvProxyModificationStateSelectors.MODIFY_PROXY_START_EVENT).defaultFailureEvent()
Please be conform with other flow configs and do a fully qualified import for these enum values.

2022-09-23 12:29 UTC, bergerdenes commented on environment/src/test/java/com/sequenceiq/environment/proxy/v1/service/ProxyConfigServiceTest.java
> +    void shouldModifySameProxies() {
naming can be misleading as it should _not_ modify

2022-09-23 12:29 UTC, bergerdenes commented on environment/src/test/java/com/sequenceiq/environment/proxy/v1/service/ProxyConfigServiceTest.java
> +    void shouldModifyNoProxies() {
naming can be misleading as it should _not_ modify

2022-09-23 13:14 UTC, Bajzathd commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationSaveAssociationHandler.java
> +        EnvironmentDto environmentDto = environmentService.updateProxyConfig(eventData.getEnvironmentDto().getId(), eventData.getProxyConfig());
AbstractEnvProxyModificationAction.getFailurePayload should create a failed event in that case, that is handled by ProxyConfigModificationFailedStateAction

2022-09-23 13:33 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationSaveAssociationHandler.java
> +        EnvironmentDto environmentDto = environmentService.updateProxyConfig(eventData.getEnvironmentDto().getId(), eventData.getProxyConfig());
ok

2022-09-23 13:56 UTC, Bajzathd commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/modify/proxy/handler/EnvProxyModificationSaveAssociationHandler.java
> +        EnvironmentDto environmentDto = environmentService.updateProxyConfig(eventData.getEnvironmentDto().getId(), eventData.getProxyConfig());
fixed it with the other comments

2022-09-23 14:32 UTC, bergerdenes approved these changes

2022-09-27 08:33 UTC, merged