CB-18699 adding vertical scale recommendation endpoint
hortonworks/cloudbreak pull request #13502
Opened 2022-09-27 11:36 UTC by doktoric

See detailed description in the commit message.

2022-09-28 07:17 UTC, lacikaaa commented
FMS part LGTM

2022-09-28 11:41 UTC, bergerdenes requested changes

2022-09-28 11:41 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/VerticalScalingValidatorService.java
> +        if (!stack.isStopped() && !stack.isStopInProgress()) {
Will vertical scale wait for full stop in case it is just in progress?

2022-09-28 11:41 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/service/VerticalScalingValidatorService.java
> +            throw new BadRequestException(String.format("Define a group which exists in FreeIpa. It can be [%s].",
It is the core module

2022-09-28 11:41 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/platformresource/PlatformParameterService.java
> +        //CHECKSTYLE:ON
not needed

2022-09-28 11:41 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/platformresource/v1/EnvironmentPlatformResourceController.java
> +        LOGGER.info("Get /platform_resources/machine_types_for_vertical_scaling, request: {}", request);
debug

2022-09-28 11:41 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/platformresource/v1/EnvironmentPlatformResourceController.java
> +        LOGGER.info("Resp /platform_resources/machine_types_for_vertical_scaling, request: {}, cloudVmTypes: {}, response: {}", request, cloudVmTypes, response);
debug

2022-09-28 11:41 UTC, bergerdenes commented on environment-common/src/main/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProvider.java
> +                    }
candidate for a boolean function

2022-09-28 11:41 UTC, bergerdenes commented on environment-common/src/main/java/com/sequenceiq/cloudbreak/service/verticalscale/VerticalScaleInstanceProvider.java
> +    }
Code smell: repeating same logic for the same type: `VolumeParameterConfig`

2022-09-28 16:11 UTC, bergerdenes approved these changes

2022-09-29 06:52 UTC, bergerdenes approved these changes

2022-09-29 12:41 UTC, tiborpopovics approved these changes

2022-09-29 13:46 UTC, merged