CB-18752 Allow multiAz when StackType is TEMPLATE
hortonworks/cloudbreak pull request #13531
Opened 2022-09-30 06:35 UTC by balassai

See detailed description in the commit message.

2022-09-30 07:13 UTC, urbandan approved these changes

2022-09-30 08:29 UTC, balassai commented
retest this please

2022-09-30 08:30 UTC, benyoka approved these changes

2022-09-30 11:47 UTC, lajosrodek requested changes

2022-09-30 11:47 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/kafka/KafkaMultiAzConfigProvider.java
> +            StackType.TEMPLATE.equals(source.getStackType()))
Sorry but this does not make sense. The stack of clusters cannot be of `StackType.TEMPLATE`. The latter represents a customer cluster definition, that is called a "cluster template" in the CB repo for historical reasons (Ambari times). The stack is either `DATALAKE` or `WORKLOAD` (for DH clusters), even if they are launched from a custom cluster definition (that is internally stored as a stack of `StackType.TEMPLATE`). Adding this extra condition will not solve your issues.

2022-09-30 11:48 UTC, lajosrodek commented
CC @biharitomi

2022-10-03 13:20 UTC, balassai commented
Closing.

2022-10-03 13:20 UTC, closed without merging