CB-18759 Add Salt Update flow as the first in the upgrade CCM flowchain
hortonworks/cloudbreak pull request #13557
Opened 2022-10-05 12:17 UTC by bergerdenes

As it turned out, only the Salt states were pushed + _only_ the gateway pillar. If recent Salt states would require new pillar data then those states would fail. Typically, at calling `highstate`.

Adjusted integration tests. Removed refactored service which is not in use anymore.

2022-10-05 12:43 UTC, lajosrodek requested changes

2022-10-05 12:43 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/chain/UpgradeCcmFlowEventChainFactory.java
>                  new UpgradeCcmTriggerRequest(UPGRADE_CCM_EVENT.event(), event.getResourceId(), event.getClusterId(), event.getOldTunnel(), event.accepted()));
Is `event.accepted()` still needed here?

2022-10-05 16:57 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-10-05 17:27 UTC, merged

2022-10-06 07:58 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmService.java
> +        }
why is this necessary? usually stack state changes does the same

2022-10-06 08:38 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/ccm/upgrade/UpgradeCcmService.java
> +        }
I haven't asked to remove and retest. Although I see now it was moved from another class, which was deleted. I just don't understand why is it necessary at all.