CB-19018 Stop the cluster even if CM stop failed
hortonworks/cloudbreak pull request #13668
Opened 2022-10-19 15:13 UTC by lturcsanyi

See detailed description in the commit message.

2022-10-20 08:53 UTC, szabolcs-horvath approved these changes

2022-10-21 09:14 UTC, lajosrodek requested changes
Sanity check: Are we sure no data loss/corruption occurs if CM & cluster services are not stopped successfully?

2022-10-21 09:17 UTC, lturcsanyi commented
This just restores the original logic that was accidentally changed in a previous commit.
The same happens if someone stops the VM from the provider side.

2022-10-21 12:47 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-10-21 12:48 UTC, merged