CB-18993 Improve salt password rotation fallback implementation
hortonworks/cloudbreak pull request #13667
Opened 2022-10-19 14:53 UTC by Bajzathd

Simplified the rebootstrap step by refactoring it out from the bootstrap step - this way the salt states will not be uploaded, and only the gateway nodes have to be rebootstrapped.

See detailed description in the commit message.

2022-10-21 13:26 UTC, lacikaaa requested changes
so on non-gw nodes the salt user password won't be rotated. wouldn't this defeat the purpose of the whole password rotation?

2022-10-21 13:35 UTC, Bajzathd commented
> so on non-gw nodes the salt user password won't be rotated. wouldn't this defeat the purpose of the whole password rotation?

saltuser is only present on gateway nodes, as it is only needed for salt masters

2022-10-24 12:11 UTC, lacikaaa approved these changes

2022-10-25 09:05 UTC, biharitomi requested changes

2022-10-25 10:02 UTC, Bajzathd commented on orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
> +        List<String> targetIps = targets.stream().map(Node::getPrivateIp).collect(Collectors.toList());
Great idea, but how about logging the submitted SaltAction in sc.action() ?

2022-10-25 11:25 UTC, biharitomi commented on orchestrator-salt/src/main/java/com/sequenceiq/cloudbreak/orchestrator/salt/states/SaltStateService.java
> +        List<String> targetIps = targets.stream().map(Node::getPrivateIp).collect(Collectors.toList());
Thanks, that would be great also, resolving this.

2022-10-25 11:28 UTC, biharitomi approved these changes
LGTM, thanks for resolving my review items!

2022-10-25 12:17 UTC, merged