CB-18344: Extend nameserver ip validation with null check
hortonworks/cloudbreak pull request #13670
Opened 2022-10-19 20:21 UTC by tiborpopovics

In this commit I added validation to prevent the nameserver settings in the service pillar from null values. Sometimes we set the nameserver address in the unbound config to null and this causes cluster creation failures.

2022-10-20 09:43 UTC, lacikaaa requested changes

2022-10-20 09:43 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecorator.java
> +    private static Predicate<String> filterValidIps() {
nit: why is this static?

2022-10-20 09:43 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecorator.java
> +        return ip -> StringUtils.hasText(ip) && !"null".equals(ip);
you could use an IPv4 matcher which would be more safe then just checking for `null`

2022-10-20 09:43 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/host/decorator/NameserverPillarDecorator.java
> +    private static List<String> getKerberosNameServerIps(KerberosConfig kerberosConfig) {
why is this static?

2022-10-20 09:44 UTC, lacikaaa commented
as 2.63 in prod, could you move this pr too?

2022-10-24 12:06 UTC, lacikaaa approved these changes

2022-10-25 08:18 UTC, merged

2022-10-25 08:18 UTC, lnardai commented
@keyki 
Hmm. Without the branch guardians approval?
Sounds like a revert