CB-15764 Freeipa should implement ApplicationFlowInformation.handleFlowFail
hortonworks/cloudbreak pull request #13679
Opened 2022-10-21 08:13 UTC by sodre90

2022-10-21 08:31 UTC, lturcsanyi commented on freeipa/src/main/java/com/sequenceiq/freeipa/FreeIpaFlowInformation.java
> +        LOGGER.info("Handling failed freeipa flow {} for {}", flowLog, stack);
stack -> stack.getId()?

2022-10-21 09:10 UTC, lturcsanyi approved these changes

2022-10-25 08:29 UTC, lajosrodek requested changes
Only some minor bits.

2022-10-25 08:29 UTC, lajosrodek commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java
> +    //CHECKSTYLE:OFF: CyclomaticComplexity
Sanity check: Is this needed? If so, there is no corresponding comment to re-enable the rule validation.

2022-10-25 08:29 UTC, lajosrodek commented on freeipa-api/src/test/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/StatusTest.java
> +                if (!status.isInProgress()) {
Nit: Possibly collapse the two `if` statements into a single one.

2022-10-26 11:35 UTC, sodre90 commented on freeipa-api/src/main/java/com/sequenceiq/freeipa/api/v1/freeipa/stack/model/common/Status.java
> +    public boolean isInProgress() {
Thanks, I missed it!

2022-10-27 11:49 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-12-01 10:28 UTC, tiborpopovics approved these changes

2022-12-07 13:52 UTC, akanto commented
Isn't it related to: https://jira.cloudera.com/browse/CB-19969

2022-12-08 12:23 UTC, merged