CB-18976 Changing network causes failure in PG upgrade
hortonworks/cloudbreak pull request #13681
Opened 2022-10-21 11:40 UTC by schfeca75

CB-18976 Changing network causes failure in PG upgrade

In case of azure we will update the database subnets before executing the database upgrade in redbeams.

2022-10-24 08:44 UTC, horadla23 approved these changes

2022-10-24 10:00 UTC, gergopapi2 commented
The commit message describes the remedy introduced in this commit. Please add a short description of the problem, why the remedy is needed?

2022-10-24 11:12 UTC, gergopapi2 commented on redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
> +            networkAttributes.putAll(envSubnets);
As discussed in person, this is not the case, so the code is ok.

2022-10-24 11:40 UTC, gergopapi2 requested changes

2022-10-24 11:40 UTC, gergopapi2 commented on redbeams/src/main/java/com/sequenceiq/redbeams/service/stack/RedbeamsUpgradeService.java
> +            return dbStackService.save(dbStack);
Please add a log line that network attributes were updated with env subnets, and the names could also be listed.

2022-10-25 12:38 UTC, gergopapi2 approved these changes

2022-10-25 12:48 UTC, schfeca75 commented
> The commit message describes the remedy introduced in this commit. Please add a short description of the problem, why the remedy is needed?

Commit message has been updated

2022-10-25 17:48 UTC, merged