CB-18823 - add s3guard validation
hortonworks/cloudbreak pull request #13748
Opened 2022-11-03 16:32 UTC by vivprabu

See detailed description in the commit message.

2022-11-04 11:09 UTC, lturcsanyi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandler.java
> +        return new ClusterUpgradeS3guardValidationFinishedEvent(START_CLUSTER_UPGRADE_IMAGE_VALIDATION_EVENT.name(),
Please move the selector into the constructuor.

2022-11-04 11:09 UTC, lturcsanyi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandler.java
> +            return new ClusterUpgradeS3guardValidationEvent(getNextSelector(), request.getResourceId(), request.getImageId());
It should be `new ClusterUpgradeS3guardValidationFinishedEvent(...)`

2022-11-04 11:09 UTC, lturcsanyi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandler.java
> +            return new ClusterUpgradeS3guardValidationEvent(getNextSelector(), request.getResourceId(), request.getImageId());
It should be `new ClusterUpgradeS3guardValidationFinishedEvent(...)`

2022-11-04 14:15 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandlerTest.java
> +        when(stackService.findEnvironmentCrnByStackId(STACK_ID)).thenReturn("1");
It makes sense to give name to constants.

2022-11-04 14:18 UTC, gergopapi2 commented on core/src/test/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandlerTest.java
> +        when(stackService.findEnvironmentCrnByStackId(STACK_ID)).thenReturn("1");
Also, please add tests for the selector and defaultFailureEvent.

2022-11-04 16:41 UTC, akanto requested changes
As it was explained in the jira ticket, this should not be in CB but in CM, therefore this pull request can't be approved or merged.

2022-11-09 09:19 UTC, keyki commented
As discussed, the PR will be merged once the commands are addressed.

2022-11-09 12:38 UTC, akanto commented
> As it was explained in the jira ticket, this should not be in CB but in CM, therefore this pull request can't be approved or merged.

We have clarified with Shwetha, the validation part can be merged, however we need to make sure that the code does not have any CM-related interaction feature (e.g CM API call) or anything that should be done in CM upgrade handler.

2022-11-09 14:20 UTC, vivprabu commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/datalake/upgrade/validation/handler/ClusterUpgradeS3guardValidationHandler.java
> +                "Please disable it by following: https://docs.cloudera.com/cdp-public-cloud-preview-features/cloud/disable-s3-guard/disable-s3-guard.pdf"));
done

2022-11-10 07:16 UTC, gergopapi2 approved these changes

2022-11-10 09:57 UTC, lturcsanyi approved these changes

2022-11-10 11:38 UTC, gergopapi2 approved these changes

2022-11-11 13:22 UTC, akanto approved these changes

2022-11-11 13:25 UTC, doktoric approved these changes

2022-11-14 09:24 UTC, merged