CB-19114:Add validation for custom templates to ensure correct knox placement
hortonworks/cloudbreak pull request #13754
Opened 2022-11-04 15:43 UTC by juhi-09

CB-19114:Add validation for custom templates to ensure correct knox placement

This commit adds a validation that knox can't be in a hostgroup where type!=GATEWAY

-     nginx is configured only on host group with type=GATEWAY
-     LB is configured with all the nodes where knox is installed
-     If knox is deployed on 2 hostgroups, but only one hostgroup will have type=GATEWAY and only that node will have nginx

So the ask is, to add a validation that knox can't be in a hostgroup where type!=GATEWAY

2022-11-04 16:33 UTC, yg-gd requested changes

2022-11-04 16:33 UTC, yg-gd commented on core/src/test/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigServiceTest.java
> +        InstanceGroup instanceGroup = new InstanceGroup();
Can you include a test case for the expected Exception?

2022-11-04 16:33 UTC, yg-gd commented on core/src/main/java/com/sequenceiq/cloudbreak/service/LoadBalancerConfigService.java
> +            throw new CloudbreakServiceException("KNOX can only be installed on instance group where type is GATEWAY." + groupNames + "---" +
Can you include a reference back to the blueprint name?

2022-11-07 17:28 UTC, yg-gd approved these changes

2022-11-21 06:58 UTC, lnardai approved these changes

2022-11-21 07:28 UTC, merged