CB-18947 Environment API changes for Targeting Subnets for Load Balan…
hortonworks/cloudbreak pull request #13771
Opened 2022-11-08 16:02 UTC by bergerdenes

…cers

Added new DeploymentRestriction set to the CloudSubnet that recommends the usage of the given subnet.

Added checking for the new entitlement for targeting subnets.

When subnets are provided then those are for non-LB usage. If endpoint gateway subnets are provided then those are for LB usage.

Similarly if new network is requested, public ones are for LB and private ones are for non-LB usage (depending on the entitlement, where those can be used for LB as well)

Added missing validation for new network creation path, now if the request contains endpoint gateway subnets, it is a validation error.

See detailed description in the commit message.

2022-11-10 13:16 UTC, lajosrodek requested changes
Some sanity checks and small asks.

2022-11-10 13:55 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/service/EnvironmentCreationService.java
> +                getIfNotNull(creationDto.getNetwork(), NetworkDto::getEndpointGatewaySubnetIds));
Nope, please see design doc linked to the epic. 
It will basically determine whether we assign a public IP to the GW or not.

2022-11-10 14:23 UTC, bergerdenes commented on common-model/src/main/java/com/sequenceiq/common/api/type/DeploymentRestriction.java
> +    LOADBALANCER;
Renamed as discussed

2022-11-10 14:24 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/SubnetSelector.java
> +                if (entitlementService.endpointGatewaySkipValidation(ThreadBasedUserCrnProvider.getAccountId())
The entitlement is used by some customers as of now so cannot be easily removed.

2022-11-10 14:26 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/converter/NetworkV1ToNetworkV4Converter.java
> +            } else {
renamed

2022-11-10 14:33 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/network/v1/converter/AwsEnvironmentNetworkConverter.java
> +                                subnet.isPublicSubnet() ? DeploymentRestriction.LOADBALANCERS : getDeploymentRestrictionForPrivateSubnet())
Nope. The logic that creates subnets is fuzzy (for me at least)

2022-11-10 22:36 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/cloudbreak/converter/v4/environment/network/SubnetSelector.java
> +                if (entitlementService.endpointGatewaySkipValidation(ThreadBasedUserCrnProvider.getAccountId())
changed

2022-11-11 12:09 UTC, lajosrodek approved these changes
Two minor bits, but approving in advance. LGTM

2022-11-11 12:09 UTC, lajosrodek commented on environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidator.java
> +    private void validateNetworkCidrAndLoadBalancerSubnet(NetworkDto network, ValidationResultBuilder resultBuilder) {
Nit: `LoadBalancer` -> `EndpointGateway`

2022-11-11 12:12 UTC, bergerdenes commented on common-model/src/main/java/com/sequenceiq/common/api/type/DeploymentRestriction.java
> +    public static final Set<DeploymentRestriction> NON_ENDPOINT_ACCESS_GATEWAY =
fixed

2022-11-11 12:12 UTC, bergerdenes commented on environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/NetworkCreationValidator.java
> +    private void validateNetworkCidrAndLoadBalancerSubnet(NetworkDto network, ValidationResultBuilder resultBuilder) {
fixed

2022-11-11 12:15 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-11-14 12:02 UTC, lajosrodek approved these changes
LGTM

2022-11-15 09:25 UTC, merged