CB-19874 adding more log to environment validation step to help us de…
hortonworks/cloudbreak pull request #13877
Opened 2022-11-30 12:48 UTC by doktoric

…bugging problems

See detailed description in the commit message.

2022-12-01 10:51 UTC, topolyai5 commented on environment/src/main/java/com/sequenceiq/environment/environment/flow/creation/handler/EnvironmentValidationHandler.java
> +        LOGGER.debug("Validate Environment telemetry location.");
maybe the log better inside the validate method

2022-12-01 12:19 UTC, lajosrodek requested changes
A few small asks.

2022-12-01 12:19 UTC, lajosrodek commented on environment/src/main/java/com/sequenceiq/environment/environment/validation/validators/EnvironmentNetworkProviderValidator.java
> +        LOGGER.debug("Validate security group that it exist on provider side.");
Nit: `exist` -> `exists`

2022-12-01 12:21 UTC, topolyai5 approved these changes

2022-12-02 10:08 UTC, lajosrodek approved these changes
Thanks, LGTM

2022-12-05 09:14 UTC, lnardai approved these changes

2022-12-05 09:14 UTC, merged