CB-19671 refactor the current cert logic and make it more maintainable.
hortonworks/cloudbreak pull request #13950
Opened 2022-12-12 17:02 UTC by doktoric

See detailed description in the commit message.

2022-12-19 18:02 UTC, lajosrodek requested changes

2022-12-22 21:24 UTC, doktoric commented on redbeams/src/test/java/com/sequenceiq/redbeams/configuration/SslCertificateEntryTest.java
it can not be null. the path contains the provider.

2022-12-23 14:08 UTC, doktoric commented on redbeams/src/test/java/com/sequenceiq/redbeams/configuration/DatabaseServerSslCertificateConfigTest.java
> -    }
I dont think this is make sense anymore

2022-12-29 15:24 UTC, bergerdenes approved these changes
LGTM

2023-01-02 14:33 UTC, lajosrodek requested changes
Three small asks, looks great otherwise. :smile:

2023-01-02 14:33 UTC, lajosrodek commented on redbeams/src/test/java/com/sequenceiq/redbeams/configuration/DatabaseServerSslCertificateConfigTest.java
> -    }
This shall be ideally kept.

2023-01-02 14:33 UTC, lajosrodek commented on redbeams/src/test/java/com/sequenceiq/redbeams/configuration/DatabaseServerSslCertificateConfigTest.java
> -    }
Well the check in `DatabaseServerSslCertificateConfig.validateCloudPlatformFormat()` is still in place. If you feel this is not worth keeping, the associated check shall be also removed (along with `CLOUD_PLATFORM_AND_REGION_PATTERN`).

2023-01-02 14:33 UTC, lajosrodek commented on redbeams/src/test/java/com/sequenceiq/redbeams/configuration/SslCertificateEntryTest.java
> +    }
Perhaps add one more test case where `cloudProviderIdentifier` contains a region different than the `.default` suffix, e.g. `"certID.someregion"`. `getCloudKey()` shall then return the input `cloudProviderIdentifier` unchanged without stripping the suffix.

2023-01-04 16:24 UTC, lajosrodek approved these changes
LGTM. Nice work and thanks for your patience! :smile:

2023-01-04 19:38 UTC, merged