CB-20083 Removes no-ntp flag from ipa-replica-install
hortonworks/cloudbreak pull request #13964
Opened 2022-12-14 21:36 UTC by pkedvessy

Validation has been applied to avoid ntp config change in case of already installed ipa client.
https://github.com/freeipa/freeipa/commit/2fba5acc5245caf62ec9af8b8707c13f59bfcff4

2022-12-16 08:38 UTC, sgabor001 approved these changes
LGTM

2022-12-16 14:02 UTC, lacikaaa commented
have you validated that ntp is not enabled on freeipa replicas? neither on centos7 nor on redhat8?

2022-12-16 14:08 UTC, pkedvessy commented
I did not validate anything manually. I ran all freeipa related tests and they passed the validation. If you need me to check this or that on top of the tests, please give me a guide.

2022-12-16 14:25 UTC, pkedvessy commented
Okey, thanks @lacikaaa

2022-12-16 16:14 UTC, pkedvessy commented
@lacikaaa Seems like ntpd is running on the centos7 replica :-( So we should check the freeipa version (or the os? what do you think?) and apply the flag where needed.
ntpd is not installed at all on redhat8. chrony shows an error on both master and replica instances but they are up and runing:
`[root@ipaserver0 cloudbreak]# systemctl status chronyd.service
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2022-12-16 15:32:35 UTC; 32min ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
 Main PID: 6378 (chronyd)
    Tasks: 1 (limit: 47350)
   Memory: 812.0K
   CGroup: /system.slice/chronyd.service
           └─6378 /usr/sbin/chronyd

dec 16 15:32:35 ipaserver0 systemd[1]: chronyd.service: Succeeded.
dec 16 15:32:35 ipaserver0 systemd[1]: Stopped NTP client/server.
dec 16 15:32:35 ipaserver0 systemd[1]: Starting NTP client/server...
dec 16 15:32:35 ipaserver0 chronyd[6378]: chronyd version 4.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG)
dec 16 15:32:35 ipaserver0 chronyd[6378]: Frequency -13.106 +/- 0.023 ppm read from /var/lib/chrony/drift
dec 16 15:32:35 ipaserver0 chronyd[6378]: Could not add source 169.254.169.123
dec 16 15:32:35 ipaserver0 systemd[1]: Started NTP client/server.
dec 16 15:32:39 ipaserver0 chronyd[6378]: Selected source 169.254.169.123
`
Is it something we should worry about?

2022-12-16 16:22 UTC, lacikaaa commented
what is the error?

yes, either freeipa version (bit more complicated, as we have to find the version where this behavior changed) or the os major version should be checked

2022-12-16 16:23 UTC, lacikaaa requested changes
just to prevent accidental merge

2022-12-16 23:06 UTC, pkedvessy commented
@lacikaaa Thanks for you suggestions. Timesync got verified and it is working as expected. Now we apply the change only in case of RHEL 8 where ntp is not installed at all.

2022-12-17 12:01 UTC, lacikaaa commented
I got the idea, that we might add to one of the e2e test to check these services.

2022-12-17 12:13 UTC, lacikaaa requested changes

2022-12-17 12:13 UTC, lacikaaa commented on freeipa/src/main/resources/freeipa-salt/salt/freeipa/scripts/freeipa_replica_install.sh
> +          $NO_NTP_FLAG
that seems a bit overcomplicated
you could just do something like
```
--unattended \
{%- if grains['os_family'] == 'RedHat' and grains['osmajorrelease'] | int == 7 %}
--no-ntp \
{%- endif %}
--dirsrv-config-file /opt/salt/initial-ldap-conf.ldif

2022-12-17 20:59 UTC, pkedvessy commented
@lacikaaa I definitely support your idea on having an e2e test to verify must have services are active and others are disabled or not installed at all. If you need me, I can create it. The other one what we should create is to have an image validator e2e test for gov images (like we have for other providers)... I don't know why it has not been created right after the support got introduced or why it has not been called out yet but it is definitely needed to avoid issues like this.

2022-12-18 10:45 UTC, lacikaaa approved these changes
thanks for the changes

please create the e2e tickets, thanks

2022-12-18 22:17 UTC, pkedvessy commented
@lacikaaa  Thanks for taking care about this PR during the weekend. Tickets to improve our validations:
https://jira.cloudera.com/browse/CB-20121
https://jira.cloudera.com/browse/CB-20122

2022-12-19 11:36 UTC, merged