CB-18484 Modify proxy config of DataLake
hortonworks/cloudbreak pull request #13977
Opened 2022-12-19 14:51 UTC by Bajzathd

Will open the PR after https://github.com/hortonworks/cloudbreak/pull/13975

2023-01-09 19:48 UTC, bergerdenes requested changes
Minor things

2023-01-09 19:48 UTC, bergerdenes commented on datalake/src/test/java/com/sequenceiq/datalake/flow/modifyproxy/handler/ModifyProxyConfigWaitHandlerTest.java
> +class ModifyProxyConfigWaitHandlerTest {
No test for the failure case.

2023-01-09 19:48 UTC, bergerdenes commented on environment/src/test/java/com/sequenceiq/environment/environment/service/sdx/SdxServiceTest.java
> +    private static <T> T doAsCurrentUserCrn(Supplier<T> callable) {
Static is not needed

2023-01-10 15:08 UTC, bergerdenes approved these changes
LGTM

2023-01-11 08:59 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/modifyproxy/ModifyProxyConfigStatusService.java
> +        LOGGER.info("Failed modify proxy config state", exception);
this should be error

2023-01-11 09:00 UTC, lacikaaa commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/cluster/modifyproxy/action/ModifyProxyConfigAction.java
> +        StackView stackView = stackDtoService.getStackViewById(payload.getResourceId());
we usually set up the mdccontext at this point just to be sure we have it

2023-01-11 09:05 UTC, lacikaaa commented on datalake/src/main/java/com/sequenceiq/datalake/controller/sdx/SdxInternalController.java
> +    public FlowIdentifier modifyProxy(@TenantAwareParam String crn, String previousProxyCrn, @InitiatorUserCrn String initiatorUserCrn) {
I see it's crn everywhere else, so maybe it's obvious for others :)

2023-01-11 13:43 UTC, lacikaaa approved these changes

2023-01-11 15:56 UTC, sodre90 commented
wouldn't be nice to create an e2e test for this feature or do we have jira ticket for this?

2023-01-11 16:09 UTC, sodre90 approved these changes

2023-01-11 16:44 UTC, merged