CB-19879 Fixed cdp-prometheus not being able to start on Azure base images
hortonworks/cloudbreak pull request #13987
Opened 2022-12-21 12:03 UTC by szabolcs-horvath

2023-01-12 10:00 UTC, aszegedi approved these changes

2023-01-13 07:57 UTC, lacikaaa requested changes

2023-01-13 07:57 UTC, lacikaaa commented on orchestrator-salt/src/main/resources/salt-common/salt/monitoring/scripts/monitoring-secret-handler.sh
> +    yes | yum install httpd-tools &> /dev/null
usually there is no internet connection on the customers machine so this won't work. you would have to fix this on the image side
also for this we usually use salt states and not yum commands, as those are not OS independent

2023-03-01 10:58 UTC, lnardai commented
The change will be implemented in cloudbreak-images. Closing this PR.

2023-03-01 10:58 UTC, closed without merging