CB-18474 FREEIPA - AWS quota issue is hidden, hard to investigate e2e test results
hortonworks/cloudbreak pull request #13998
Opened 2022-12-22 22:00 UTC by adarshsharma1983

code changes to capture reason of failure as additonal failure details

See detailed description in the commit message.

2022-12-23 08:06 UTC, lacikaaa requested changes

2022-12-23 08:06 UTC, lacikaaa commented on freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/upscale/failure/UpscaleStackResultToUpscaleFailureEventConverterTest.java
> +        assert (upscaleFailureEvent.getFailureDetails()).equals(Map.of("statusReason", upscaleStackResult.getStatusReason()));
please use junit asserts, like assertTrue

2022-12-23 13:55 UTC, adarshsharma1983 commented on freeipa/src/test/java/com/sequenceiq/freeipa/flow/freeipa/upscale/failure/UpscaleStackResultToUpscaleFailureEventConverterTest.java
> +        assert (upscaleFailureEvent.getFailureDetails()).equals(Map.of("statusReason", upscaleStackResult.getStatusReason()));
Done

2022-12-23 14:04 UTC, lacikaaa approved these changes

2022-12-27 08:08 UTC, doktoric approved these changes

2022-12-27 08:08 UTC, merged