CB-20174 Generate embedded PostgreSQL server cert using FMS
hortonworks/cloudbreak pull request #14029
Opened 2023-01-05 16:31 UTC by schfeca75

* Extend the postgres/init salt state with certificate generation when postgres ssl is enabled
* Create a rsa:2048 keypair using openssl
* Sign the certificate with freeipa

First the certificate generation and sign was planned to be implemented in FMS service via API, but for this
the postgres server host has to be registered in FreeIPA. The host registration is happening during salt highstate,
so it is not possible to sign the certificate before salt highstate has finished. This is the reason why we choose
the previously described solution for certificate generation.

2023-01-06 13:23 UTC, lajosrodek requested changes

2023-01-06 13:23 UTC, lajosrodek commented on orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/create_embeddeddb_certificate.sh
> +CERTS_DIR=/opt/certs/postgres
Like above, one more point in favor of restricting DB SSL support only when the embedded DB is on the attached disk. :smile:

2023-01-06 13:23 UTC, lajosrodek commented on orchestrator-salt/src/main/resources/salt/salt/postgresql/scripts/create_embeddeddb_certificate.sh
> +ipa cert-request ${CERTS_DIR}/postgres.csr --principal=postgres/{{ postgres_fqdn }} --add --certificate-out=${CERTS_DIR}/postgres.cert
Perhaps `${CERTS_DIR}/postgres.csr` could be removed after a successful cert issuance.

2023-01-06 22:12 UTC, schfeca75 commented
retest this please

2023-01-09 11:32 UTC, lacikaaa approved these changes
could you add the reason why we went with script instead of API call to the commit message? I think you've already summarized it in a jira ticket, but it would make sense to have it here too

2023-01-09 14:33 UTC, schfeca75 commented
> could you add the reason why we went with script instead of API call to the commit message? I think you've already summarized it in a jira ticket, but it would make sense to have it here too

@lacikaaa the commit message has been updated.

2023-01-09 16:52 UTC, merged