CB-20328 SSL for embedded DB
hortonworks/cloudbreak pull request #14101
Opened 2023-01-19 14:44 UTC by lajosrodek

Code complete, but missing UTs.

See detailed description in the commit message.

2023-01-26 18:34 UTC, lajosrodek commented
Hmm, `integration-test ` fails with this: `MockSdxResizeTests.minimalSetupForClusterCreation`
```
Cloudbreak await for flow SdxInternalTestDto[name: mock-test-b049342a1]:  Flow has been finalized with failed status. Crn=crn:cdp:datalake:us-west-1:cloudera:datalake:33fc249f-87db-4d5e-b577-5fbd3ce623ec, FlowId=d2af667d-52e7-4617-8804-0809318ac18e , FlowChainId=null 
com.sequenceiq.it.cloudbreak.exception.TestFailException:  Flow has been finalized with failed status. Crn=crn:cdp:datalake:us-west-1:cloudera:datalake:33fc249f-87db-4d5e-b577-5fbd3ce623ec, FlowId=d2af667d-52e7-4617-8804-0809318ac18e , FlowChainId=null 
...
mock-test-b049342a1 - crn:cdp:datalake:us-west-1:cloudera:datalake:33fc249f-87db-4d5e-b577-5fbd3ce623ec
Audit events:
- START_FAILED - Cluster could not be started. Reason: [Node status monitor is unreachable. The possible reasons are: the cluster doesn't support the node status monitor service, or the network configuration is not CDP compatible, or some required components are in bad health. Please ssh into the cluster and run cdp doctor.]
- CREATE_FAILED - Failed to GET FreeIPA root certificate by environment CRN: crn:cdp:environments:us-west-1:cloudera:environment:e5414a7e-b711-4a5a-aef0-5ecd4b08536d, due to: HTTP 500 Internal Server Error. .
- UPDATE_IN_PROGRESS - Starting Cloudera Manager
```
Perhaps this FreeIPA call is not implemented in mock-infrastructure? I will have a look at IT logs to confirm.

2023-01-26 18:49 UTC, lajosrodek commented
core:
```
2023-01-26 17:14:42,807 [reactorDispatcher-90] getRootCertificateByEnvironmentCrn:138 ERROR c.s.c.s.
f.FreeipaClientService - [type:CLUSTER] [crn:crn:cdp:datalake:us-west-1:sdxbploadtenant10:datalake:8
138c12d-c8dd-4214-8272-d4fb515233a4] [name:mock-test-7060ed0e3] [flow:6910fea0-bdb4-4f7c-b2c0-4d93ed
d8b30a] [requestid:90135545-c5b8-47dd-bffe-c8f0a9fbcbe9] [tenant:sdxbploadtenant10] [userCrn:crn:cdp
:iam:us-west-1:sdxbploadtenant10:user:sdxbpload@cloudera.com] [environment:crn:cdp:environments:us-w
est-1:sdxbploadtenant10:environment:68f4f160-660e-47dd-9e1c-890d936a292a] [traceId:] [spanId:] Faile
d to GET FreeIPA root certificate by environment CRN: crn:cdp:environments:us-west-1:sdxbploadtenant
10:environment:68f4f160-660e-47dd-9e1c-890d936a292a, due to: HTTP 500 Internal Server Error. .
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:960
)
...
        at com.sequenceiq.cloudbreak.service.freeipa.FreeipaClientService.getRootCertificateByEnviro
nmentCrn(FreeipaClientService.java:132)
        at com.sequenceiq.cloudbreak.service.cluster.DatabaseSslService.getEmbeddedDatabaseRootCerti
ficate(DatabaseSslService.java:164)
        at com.sequenceiq.cloudbreak.service.cluster.DatabaseSslService.decorateSslDetailsWithEmbedd
edDatabase(DatabaseSslService.java:100)
        at com.sequenceiq.cloudbreak.service.cluster.DatabaseSslService.getDbSslDetailsAndUpdateInCl
usterInternal(DatabaseSslService.java:73)
        at com.sequenceiq.cloudbreak.service.cluster.DatabaseSslService.getDbSslDetailsForCreationAn
dUpdateInCluster(DatabaseSslService.java:62)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.container.postgres.PostgresConfigService
.getSslSaltConfigWhenRootCertNull(PostgresConfigService.java:107)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.container.postgres.PostgresConfigService
.decorateServicePillarWithPostgresIfNeeded(PostgresConfigService.java:69)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.host.ClusterHostServiceRunner.createSalt
Config(ClusterHostServiceRunner.java:456)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.host.ClusterHostServiceRunner.executeRun
ClusterServices(ClusterHostServiceRunner.java:301)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.host.ClusterHostServiceRunner.runCluster
Services(ClusterHostServiceRunner.java:259)
        at com.sequenceiq.cloudbreak.core.bootstrap.service.ClusterServiceRunner.runClusterManagerSe
rvices(ClusterServiceRunner.java:60)
        at com.sequenceiq.cloudbreak.reactor.handler.orchestration.StartAmbariServicesHandler.accept
(StartAmbariServicesHandler.java:51)
        at com.sequenceiq.cloudbreak.reactor.handler.orchestration.StartAmbariServicesHandler.accept
(StartAmbariServicesHandler.java:22)
```

FMS:
```
2023-01-26 17:14:42,793 [http-nio-8080-exec-5] aroundWriteTo:222 ERROR o.g.j.m.i.WriterInterceptorEx
ecutor - [type:FREEIPAV1] [crn:] [name:] [flow:] [requestid:90135545-c5b8-47dd-bffe-c8f0a9fbcbe9] [t
enant:sdxbploadtenant10] [userCrn:crn:cdp:iam:us-west-1:sdxbploadtenant10:user:sdxbpload@cloudera.co
m] [environment:crn:cdp:environments:us-west-1:sdxbploadtenant10:environment:68f4f160-660e-47dd-9e1c
-890d936a292a] [traceId:] [spanId:] [operationId:] MessageBodyWriter not found for media type=text/p
lain, type=class com.sequenceiq.cloudbreak.common.exception.ExceptionResponse, genericType=class com
.sequenceiq.cloudbreak.common.exception.ExceptionResponse.
2023-01-26 17:14:42,794 [http-nio-8080-exec-5] process:421 ERROR o.g.j.s.ServerRuntime$Responder - [
type:FREEIPAV1] [crn:] [name:] [flow:] [requestid:90135545-c5b8-47dd-bffe-c8f0a9fbcbe9] [tenant:sdxb
ploadtenant10] [userCrn:crn:cdp:iam:us-west-1:sdxbploadtenant10:user:sdxbpload@cloudera.com] [enviro
nment:crn:cdp:environments:us-west-1:sdxbploadtenant10:environment:68f4f160-660e-47dd-9e1c-890d936a2
92a] [traceId:] [spanId:] [operationId:] Error occurred when processing a response created from an a
lready mapped exception.
2023-01-26 17:14:42,796 [http-nio-8080-exec-5] log:175 ERROR o.a.c.c.C.[.[.[.[.s.f.c.EndpointConfig]
 - [type:FREEIPAV1] [crn:] [name:] [flow:] [requestid:90135545-c5b8-47dd-bffe-c8f0a9fbcbe9] [tenant:
sdxbploadtenant10] [userCrn:crn:cdp:iam:us-west-1:sdxbploadtenant10:user:sdxbpload@cloudera.com] [en
vironment:crn:cdp:environments:us-west-1:sdxbploadtenant10:environment:68f4f160-660e-47dd-9e1c-890d9
36a292a] [traceId:] [spanId:] [operationId:] Servlet.service() for servlet [com.sequenceiq.freeipa.c
onfiguration.EndpointConfig] in context with path [/freeipa] threw exception [javax.ws.rs.InternalSe
rverErrorException: HTTP 500 Internal Server Error] with root cause
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not fo
und for media type=text/plain, type=class com.sequenceiq.cloudbreak.common.exception.ExceptionRespon
se, genericType=class com.sequenceiq.cloudbreak.common.exception.ExceptionResponse.
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor
.aroundWriteTo(WriterInterceptorExecutor.java:224)
```

2023-01-26 18:55 UTC, lajosrodek commented
Strangely the non-internal cert operations seems to work fine. Here are the calls just surrounding the above error timestamp.
```
2023-01-26 17:11:40,806 [http-nio-8080-exec-6] doFilterInternal:64 DEBUG c.s.c.l.RestLoggerFilter -
[type:STACK] [crn:crn:cdp:freeipa:us-west-1:cloudera:freeipa:4643348c-4c21-4a4f-9ce0-987b9881eb6d] [
name:mock-test-f61421327] [flow:] [requestid:f4a76508-ba33-433b-a105-0bdcf3166b88] [tenant:cloudera]
 [userCrn:crn:altus:iam:us-west-1:cloudera:user:mockuser@ums.mock] [environment:crn:cdp:environments
:us-west-1:cloudera:environment:f15a58f9-6558-44fb-b125-10e0005eee6c] [traceId:] [spanId:] [operatio
nId:] startTime: 17:11:40.790
endTime: 17:11:40.804
duration: 14 ms
httpMethod: GET
path: /freeipa/api/v1/freeipa/ca.crt
queryString: environment=crn%3Acdp%3Aenvironments%3Aus-west-1%3Acloudera%3Aenvironment%3Af15a58f9-65
58-44fb-b125-10e0005eee6c
clientIp: 192.168.192.18
request:
responseStatus: 200
response: -----BEGIN CERTIFICATE-----
MIID0DCCArigAwIBAgIBATANBgkqhkiG9w0BAQsFADBNMSswKQYDVQQKDCJNTU9M
...
cSQj9z09/bLeGI/9RUiMvEJ5Bvg=
-----END CERTIFICATE-----


2023-01-26 17:19:26,603 [http-nio-8080-exec-8] doFilterInternal:64 DEBUG c.s.c.l.RestLoggerFilter -
[type:STACK] [crn:crn:cdp:freeipa:us-west-1:cloudera:freeipa:ee51d1e1-947c-4545-ab9a-ba2695a25229] [
name:mock-test-3824281e7] [flow:] [requestid:e8814277-80ee-4d51-a418-dd3332fc22b3] [tenant:cloudera]
 [userCrn:crn:altus:iam:us-west-1:cloudera:user:mockuser@ums.mock] [environment:crn:cdp:environments
:us-west-1:cloudera:environment:96fb241a-194e-4de6-a3b7-44a00a0437d0] [traceId:] [spanId:] [operatio
nId:] startTime: 17:19:26.591
endTime: 17:19:26.602
duration: 11 ms
httpMethod: GET
path: /freeipa/api/v1/freeipa/ca.crt
queryString: environment=crn%3Acdp%3Aenvironments%3Aus-west-1%3Acloudera%3Aenvironment%3A96fb241a-19
4e-4de6-a3b7-44a00a0437d0
clientIp: 192.168.192.18
request:
responseStatus: 200
response: -----BEGIN CERTIFICATE-----
MIID0DCCArigAwIBAgIBATANBgkqhkiG9w0BAQsFADBNMSswKQYDVQQKDCJNTU9M
...
cSQj9z09/bLeGI/9RUiMvEJ5Bvg=
-----END CERTIFICATE-----
```

2023-01-26 19:28 UTC, lajosrodek commented
Okay, so the root cause seems to be the following in FMS (GET `/freeipa/api/v1/freeipa/ca.crt`):
```
... Exception text has been mapped: FreeIPA stack by envir
onment [crn:cdp:environments:us-west-1:sdxbploadtenant10:environment:68f4f160-660e-47dd-9e1c-890d936
a292a] not found
```

2023-01-27 12:31 UTC, biharitomi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(PostgresConfigService.class);
nice fix :smile:

2023-01-27 12:54 UTC, biharitomi commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
> +        // DatabaseSslService.getDbSslDetailsForRotationAndUpdateInCluster() invocation from ClusterDbCertRotationHandler.
I think the log message with the warn message is enough and handling the mentioned edge case, so would you mind remove the commented explanation?

2023-01-27 16:57 UTC, biharitomi requested changes

2023-01-30 12:37 UTC, lajosrodek commented
retest this please

2023-01-30 16:48 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
> +        LOGGER.info("Cluster.dbSslRootCertBundle is not null. Using SslDetails from Cluster: dbSslRootCertBundle='{}', dbSslEnabled={}", dbSslRootCertBundle,
This small logic has been extracted as `DatabaseSslService.isDbSslEnabledByClusterView()`.

2023-01-31 15:18 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/DatabaseSslService.java
> +            // The stack dbSslEnabled flag is not expected to change after cluster provisioning, so its recent value from Cluster shall be honored in Rotation
We already have it for external DB: `RedbeamsDbCertificateProvider.getRelatedSslCerts()`. `DatabaseSslService` is meant to be a single point of contact for both embedded and external DBs when it comes to their SSL status. :smile:

2023-01-31 15:21 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/DatabaseSslService.java
> +        // Note: The result of this method is meaningful only if invoked when isEmbeddedDatabase(clusterView) == true.
Comment has been removed. This method is only called inside `if (isEmbeddedDatabase(clusterView))`, so it should be enough. Moreover, the method name also expresses that it is meaningful for embedded DB only. :smile:

2023-01-31 15:51 UTC, lajosrodek commented
Raised [CB-20758](https://jira.cloudera.com/browse/CB-20758) for the above FMS exception mapping issue.

2023-02-01 13:17 UTC, lajosrodek commented
retest this please

2023-02-01 16:18 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/DatabaseSslService.java
> +            // The stack dbSslEnabled flag is not expected to change after cluster provisioning, so its recent value from Cluster shall be honored in Rotation
I would prefer leaving this comment as is if you do not mind. :smile:

2023-02-01 17:03 UTC, biharitomi approved these changes
LGTM, nice coverage! Thanks!

2023-02-02 09:54 UTC, lajosrodek commented
IT failed with DB traffic limit being exceeded. :frowning_face: 
```
+ pg_res='POSTGRES>> Max allowed postgres network output: 4.6GB
POSTGRES>> Actual postgres network output: 4.61GB/4.6GB'
+ pg_ok='POSTGRES>> OK'
+ [[ POSTGRES>> Max allowed postgres network output: 4.6GB
POSTGRES>> Actual postgres network output: 4.61GB/4.6GB == POSTGRES>> OK* ]]
+ echo -e '\033[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.6GB
POSTGRES>> Actual postgres network output: 4.61GB/4.6GB !!! ---\n'
[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.6GB
POSTGRES>> Actual postgres network output: 4.61GB/4.6GB !!! ---

+ status_code=1
+ [[ status_code -eq 1 ]]
+ echo -e '\033[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---\n'
[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---

+ exit 1
make: *** [check-results] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

This is likely due to the additional overhead of creating FreeIPA for the mock test cases where DL with embedded DB is tested.

2023-02-03 11:34 UTC, schfeca75 requested changes

2023-02-03 11:34 UTC, schfeca75 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/cluster/EmbeddedDatabaseService.java
> +    @VisibleForTesting
Can you please remove this annotation

2023-02-03 11:34 UTC, schfeca75 commented on core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/container/postgres/PostgresConfigService.java
> +    @VisibleForTesting
Can you please remove this annotation

2023-02-03 13:32 UTC, schfeca75 approved these changes

2023-02-03 13:57 UTC, lajosrodek commented
Swagger errors:
```
Downloading cloudbreak 2.68.0-b97 swagger definition, if possible https://cloudbreak-swagger.s3.eu-central-1.amazonaws.com/swagger-2.68.0-b97.json

================ COMPATIBILITY BREAKS in cloudbreak ================
...
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)

...
================ COMPATIBILITY BREAKS in freeipa ================
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)

...
================ COMPATIBILITY BREAKS in environment ================
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)

...
================ COMPATIBILITY BREAKS in datalake ================
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)

...
================ COMPATIBILITY BREAKS in redbeams ================
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)

...
================ COMPATIBILITY BREAKS in consumption ================
ERROR rules:
	[MIS-E002] Changed type: #/paths//flow/logs/flowIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
	[MIS-E002] Changed type: #/paths//flow/check/chainIds/get/responses/200/schema (documentation: https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/MIS-E002.html)
```

These are due to the recent breaking changes introduced in 2.68 / #14227.

2023-02-04 16:27 UTC, lajosrodek commented
After the new master rebase, IT failed again with DB traffic limit being exceeded. :disappointed: 
```
POSTGRES>> Actual postgres network output: 4.62GB/4.61GB'
+ pg_ok='POSTGRES>> OK'
+ [[ POSTGRES>> Max allowed postgres network output: 4.61GB
POSTGRES>> Actual postgres network output: 4.62GB/4.61GB == POSTGRES>> OK* ]]
+ echo -e '\033[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.61GB
POSTGRES>> Actual postgres network output: 4.62GB/4.61GB !!! ---\n'
[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.61GB
POSTGRES>> Actual postgres network output: 4.62GB/4.61GB !!! ---

+ status_code=1
+ [[ status_code -eq 1 ]]
+ echo -e '\033[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---\n'
[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---

+ exit 1
make: *** [check-results] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

2023-02-04 17:44 UTC, lajosrodek commented
Great, now even 4.62GB was not enough for the DB traffic:
```
+ pg_res='POSTGRES>> Max allowed postgres network output: 4.62GB
POSTGRES>> Actual postgres network output: 4.63GB/4.62GB'
+ pg_ok='POSTGRES>> OK'
+ [[ POSTGRES>> Max allowed postgres network output: 4.62GB
POSTGRES>> Actual postgres network output: 4.63GB/4.62GB == POSTGRES>> OK* ]]
+ echo -e '\033[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.62GB
POSTGRES>> Actual postgres network output: 4.63GB/4.62GB !!! ---\n'
[0;91m--- !!! POSTGRES TRAFIC CHECK FAILED: POSTGRES>> Max allowed postgres network output: 4.62GB
POSTGRES>> Actual postgres network output: 4.63GB/4.62GB !!! ---

+ status_code=1
+ [[ status_code -eq 1 ]]
+ echo -e '\033[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---\n'
[0;91m--- !!! INTEGRATION TEST HAS BEEN FAILED !!! ---

+ exit 1
make: *** [check-results] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

2023-02-06 07:15 UTC, merged