CB-20462 CB API changes to support java version opt-in parameter
hortonworks/cloudbreak pull request #14143
Opened 2023-01-25 10:49 UTC by pkedvessy

We changing the API first so we can work in parallel on implementating the feature both in CB and CDP CLI

2023-01-25 12:57 UTC, Bajzathd approved these changes

2023-01-26 09:27 UTC, lacikaaa requested changes
please add validation to the version

2023-01-26 09:43 UTC, horadla23 commented
> please add validation to the version

yes, we should have a list/enum about supported java versions

2023-01-26 09:58 UTC, pkedvessy commented
> > please add validation to the version
> 
> yes, we should have a list/enum about supported java versions

@lacikaaa @horadla23 Yes, you are absolutely right and a ticket is already prepared: https://jira.cloudera.com/browse/CB-20466 As I mentioned in the description, this PR is only about the API change to work in parallel on CB and CDP CLI related implementations.

2023-01-27 09:31 UTC, horadla23 approved these changes

2023-01-27 12:18 UTC, lacikaaa approved these changes

2023-01-27 12:18 UTC, merged