CDPSDX-3528; fix configuration conditions to enable new sdx optimization config values
hortonworks/cloudbreak pull request #14194
Opened 2023-01-30 19:17 UTC by RokolyA94

CDPSDX-3528; fix configuration conditions to enable new sdx optimization config values.

2023-01-31 21:00 UTC, sxxgrc commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
> +        if (!templateProcessor.isRoleTypePresentInService(HDFS, Lists.newArrayList(NAMENODE))
I don't know enough to answer this myself, but I always get concerned when we add a new conditional around central logic. 

What happens to calls to this method that don't satisfy this condition? Do they get an empty config list? How does that differ from what we're doing right now?

My main concern is that we accidentally give empty configs to other services which need to go through the rest of this method.

2023-01-31 21:01 UTC, sxxgrc commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
> +        return true;
What is the point of this method now?

2023-02-07 18:24 UTC, votez approved these changes

2023-02-07 20:07 UTC, romedeiro approved these changes

2023-02-13 14:49 UTC, lnardai commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
> +        if (!cmTemplateProcessor.isRoleTypePresentInService(HDFS, Lists.newArrayList(NAMENODE))
This if condition and the previous one on L68 is the same. Please add a meaningful name to it an make a helper method.

2023-02-13 14:51 UTC, lnardai commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/core/CoreConfigProvider.java
> +        return true;
Why move this condition in to two different parts? This should be the only part where we logically apply a config change. If you change a different config value it should be a different ConfigProvider.

2023-02-13 14:53 UTC, lnardai commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hdfs/HdfsRoleConfigProvider.java
>      private boolean isSDXOptimizationEnabled(TemplatePreparationObject source) {
We have 2 different version of this logical switch, one here and the other is in the other config provider?
Can't we have the same logic for both?
`entitlementService.isSDXOptimizedConfigurationEnabled(ThreadBasedUserCrnProvider.getAccountId()`

2023-02-13 14:54 UTC, lnardai requested changes
Please refactor the logic in the configprovider.

2023-02-22 01:21 UTC, sxxgrc approved these changes

2023-02-24 17:19 UTC, lnardai approved these changes

2023-02-27 09:16 UTC, merged