move to AWS SDK v2 WIP
hortonworks/cloudbreak pull request #14193
Opened 2023-01-30 16:54 UTC by tiborpopovics

2023-02-09 09:28 UTC, bergerdenes requested changes
Thanks for finishing this large piece.
I have a general ask apart from the small things mentioned: I saw that in some places you migrated to Junit 5 as well, but in some places it is still Junit 4. If it is possible, could you please migrate those tests too?

2023-02-09 12:08 UTC, tiborpopovics commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/util/aws/amazonec2/action/EC2ClientActions.java
> +                    if (InstanceStateName.TERMINATED == actualInstanceState.name()) {
the `actualInstanceState.name()` is returns a InstanceStateName not a string

2023-02-10 10:15 UTC, bergerdenes approved these changes

2023-02-10 13:58 UTC, lturcsanyi reviewed
Nice work, minor comments added. 
Could you please elaborate in the description on what/how you have tested?

2023-02-10 13:58 UTC, lturcsanyi commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/VolumeBuilderUtil.java
> +        software.amazon.awssdk.services.ec2.model.Image image = images.images().get(0);
could be an import instead

2023-02-14 11:51 UTC, lturcsanyi approved these changes

2023-02-21 09:07 UTC, bergerdenes approved these changes

2023-02-21 09:18 UTC, keyki commented
retest this please

2023-02-23 15:59 UTC, tiborpopovics commented
retest this please

2023-02-23 16:00 UTC, tiborpopovics commented
retest this please

2023-03-03 15:20 UTC, merged