CB-20713 Skip ORG policy decisions(AWS) for datalake creation
hortonworks/cloudbreak pull request #14192
Opened 2023-01-30 14:44 UTC by romedeiro

Context: For now the org policy decisions should be always skipped in the datalake creation.

Test:
Created a custom response for simulation policy that returns 'denied by organization rules' and then deub if it was skipped and the datalake created.

2023-01-30 16:54 UTC, grace303303 approved these changes
TY!

2023-01-30 22:44 UTC, sxxgrc commented
Confused by this change, from what I see we are trying to help a customer avoid this issue, but I don't think this change will really help them.

First of all, this change here will take a long time to reach mow-prod unless we try to hotfix it which will come with its own lengthy review time. Also, if the customer already has a created DL and they just want to backup/restore then this won't really help will it?

Second, have we considered the unintended consequences of just skipping all this process for all datalake creation? I am concerned we may accidentally break a ton of operations because of this.

Can we not just find some way to modify the customer's credential so it sets this value to true? That way we only affect one customer and not all of them.

2023-01-31 06:43 UTC, lturcsanyi requested changes
I totally agree with @sxxgrc. We shouldnt disable it for all customers. And we have already created a property at the credential level to skip these validation errors (UI development in progress). Until that, please disable the related entitlement if necessary.

2023-01-31 09:17 UTC, lnardai commented
There is no plan or any design decision to disable this functionality. We've also added a functionality in a credential settings.

2023-01-31 09:17 UTC, closed without merging