CB-20713 Skip ORG policy decisions rule(AWS) for datalake backup
hortonworks/cloudbreak pull request #14226
Opened 2023-02-01 15:49 UTC by romedeiro

Context: Org policy decisions should always be skipped for datalake backup.

Test:
Added a custom result for the simultate policy (com.sequenceiq.cloudbreak.cloud.aws.common.util.AwsIamService#simulatePrincipalPolicy) with a 'denied by organization rules' and then checked if it was ignored and the precheckStoragePermission step in datalake backup was successful.

2023-02-01 21:14 UTC, sxxgrc approved these changes
Looks fine, please make sure to revert this in the future once the root cause has been fixed, unless we decide that it is always fine to keep this as true.

2023-02-02 06:25 UTC, lturcsanyi commented
As I have mentioned in the previous PR, we have already addressed this issue where the customer can set the skipOrgPolicyDecisions flag at the credential level, this will be available for customers in the next (2.68) relesase. See the related PRs: 
https://github.com/hortonworks/cloudbreak/pull/13856
https://github.com/hortonworks/hortonworks-cloud/pull/3397
Could you please explain why this is needed in addition to the changes above? Maybe I am missing something.

2023-02-02 13:53 UTC, kkalvagadda1 commented
> As I have mentioned in the previous PR, we have already addressed this issue where the customer can set the skipOrgPolicyDecisions flag at the credential level, this will be available for customers in the next (2.68) relesase. See the related PRs: #13856 [hortonworks/hortonworks-cloud#3397](https://github.com/hortonworks/hortonworks-cloud/pull/3397) Could you please explain why this is needed in addition to the changes above? Maybe I am missing something.

Hello Laszlo,

The change you made would help new customers. How about existing customers?

2023-02-02 13:57 UTC, lturcsanyi commented
> > As I have mentioned in the previous PR, we have already addressed this issue where the customer can set the skipOrgPolicyDecisions flag at the credential level, this will be available for customers in the next (2.68) relesase. See the related PRs: #13856 [hortonworks/hortonworks-cloud#3397](https://github.com/hortonworks/hortonworks-cloud/pull/3397) Could you please explain why this is needed in addition to the changes above? Maybe I am missing something.
> 
> Hello Laszlo,
> 
> The change you made would help new customers. How about existing customers?

Why just new customers? You can edit the credential.

2023-02-03 09:19 UTC, lnardai commented
Based on @lturcsanyi comment, can we close this?

2023-02-03 09:20 UTC, lnardai requested changes
I think this change is unnecessary. Please see Laszlo's comment.

2023-02-06 20:42 UTC, votez approved these changes

2023-02-09 15:04 UTC, grace303303 approved these changes

2023-02-15 14:48 UTC, closed without merging