CDPSDX-3900 Add logging to DB backup/restore for errors when wrong no…
hortonworks/cloudbreak pull request #14308
Opened 2023-02-14 20:30 UTC by grace303303

…de is used

JIRA: [CDPSDX-3900](https://jira.cloudera.com/browse/CDPSDX-3900)
ISSUE: When a user ran the salt command to manually backup database on a wrong node the backup fails because it is missing values in the pillar file, as below:
<img width="912" alt="V9b9V" src="https://user-images.githubusercontent.com/39275944/218854743-b3f90d6a-1913-47df-8bf8-df36b7a0fe43.png">

SOLUTION: Add in logs when that value is missing. I added in "-z "$1" which means $1 is null and I didn't remove "$1" == "None" since Im not sure if that was a case I don't know where object_storage_url is "None".

Before:
<img width="1187" alt="Screen Shot 2023-02-13 at 4 41 16 PM" src="https://user-images.githubusercontent.com/39275944/218854504-b58e345b-e617-4df9-bb14-dc7a13d03bc4.png">

After:
Backup:
<img width="1179" alt="YXQpK" src="https://user-images.githubusercontent.com/39275944/218854949-9dfdc2e6-f73f-4323-b0ec-4e39e9d2f8da.png">
Restore: 
<img width="1153" alt="3Z8XB" src="https://user-images.githubusercontent.com/39275944/218854967-27cf9caa-100f-4e4c-9f96-b89a52fa6469.png">

2023-02-15 14:57 UTC, votez requested changes
I don't see this improves the diagnostic of an error. Extra hint is good but we should be more specific on what is expected and what is missing.
Consider using [getopts](https://www.howtogeek.com/778410/how-to-use-getopts-to-parse-linux-shell-script-options/)

2023-02-16 13:51 UTC, kkalvagadda1 reviewed
looks good.

2023-02-21 02:44 UTC, grace303303 commented
> I don't see this improves the diagnostic of an error. Extra hint is good but we should be more specific on what is expected and what is missing. Consider using [getopts](https://www.howtogeek.com/778410/how-to-use-getopts-to-parse-linux-shell-script-options/)

Hi @votez CC @kkalvagadda1 I made a very small change to this PR by just logging in how many inputs there are. I'm not sure how detailed we want the logging to be - if we want to use `getopts` to make the logging more detailed & clear, we need to make more changes, including how the jinjia file. Therefore, I created another PR that makes the logging more clear (currently it's just for backup, will make changes for restore if we want to use the other PR) and you can take a look at it here: https://github.com/hortonworks/cloudbreak/pull/14325 We can determine how detailed we want to be to see which PR we want to use. To summarize - this PR is a simple change which logs out what might cause this error; the second PR has more changes to log the errors more with more details. Im just not sure if I should make that many changes just to log some errors.

2023-02-21 17:26 UTC, grace303303 commented
Closed this because we prefer the other version: https://github.com/hortonworks/cloudbreak/pull/14325

2023-02-21 17:26 UTC, closed without merging