CDPSDX-3936 add hive direct sql configatrion to the blueprints
hortonworks/cloudbreak pull request #14380
Opened 2023-03-01 14:48 UTC by RokolyA94

CDPSDX-3936 add hive direct sql configatrion to the blueprints

2023-03-01 17:48 UTC, kkalvagadda1 commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveKnoxConfigProvider.java
> +        return configs;
Why is this change needed for changing the HMS configuration for Md Ha blueprints with profilers?

2023-03-03 16:26 UTC, doktoric commented
checkstyle failed

2023-03-08 13:54 UTC, romedeiro approved these changes
Small thing, typo in the commit message "configatrion"

2023-03-08 18:49 UTC, sxxgrc approved these changes

2023-03-22 20:18 UTC, grace303303 approved these changes

2023-03-24 15:36 UTC, lajosrodek requested changes

2023-03-24 15:36 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
Please cover with UT.

2023-03-24 15:36 UTC, lajosrodek commented on template-manager-cmtemplate/src/main/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProvider.java
> +            }
What is the rationale behind moving this out from the bp and adding it dynamically?

2023-03-27 12:13 UTC, lajosrodek commented
@RokolyA94 

CheckStyle error:
```
> Task :template-manager-cmtemplate:checkstyleTest
[ant:checkstyle] [ERROR] /grid/0/jenkins/workspace/workspace/cloudbreak-pull-request-builder-checkstyle-test/template-manager-cmtemplate/src/test/java/com/sequenceiq/cloudbreak/cmtemplate/configproviders/hive/HiveMetastoreConfigProviderTest.java:368: Line is longer than 161 characters (found 167). [LineLength]
```

plus there 16 UT failures; see [here[(http://build.eng.hortonworks.com/job/cloudbreak-pull-request-builder-unit-test/638/).

2023-03-27 14:46 UTC, horadla23 approved these changes

2023-03-28 15:46 UTC, merged