CB-14941 Repair stuck in UPDATE_IN_PROGRESS state if any of the disks…
hortonworks/cloudbreak pull request #14400
Opened 2023-03-03 09:01 UTC by bbihari

… are deleted on provider

During termination when the user requested the volumes to be preserved: 1) If all volumes are already deleted for an instance cb throws an exception 2) Otherwise the missing volumes are recreated

2023-04-21 14:38 UTC, sodre90 requested changes

2023-04-21 14:38 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +                deleted = ResourceStatus.DELETED == getResourceStatus(result);
we can put getResourceStatus(result) into a variable

2023-04-21 14:38 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +        return volumeSet;
it looks like the build() method, can we somehow avoid code duplication?

2023-04-21 14:38 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +            return rebuiltVolumes;
as it can contain not deleted volumes also, it is a little deceptive name

2023-04-21 14:38 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +                LOGGER.debug(String.format("Recovered/recreated volumes: %s", recoveredVolumes));
it contains the non-deleted volumes too (naming)

2023-04-21 14:38 UTC, sodre90 commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +                }
for safety reason shouldn't be better to move setVolumeDetachParameters(auth, resource, volumeSetAttributes, cloudResourceStatuses, client);  out of the above if branch?

2023-05-03 06:59 UTC, doktoric commented
retest this please

2023-06-19 11:20 UTC, lnardai commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +            setVolumeDetachParameters(auth, resource, volumeSetAttributes, cloudResourceStatuses, client);
I might move this exception throwing outside of the setter to make the code more readable.

2023-06-19 11:35 UTC, lnardai commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +        throw new PreserveResourceException("Resource will be preserved for later reattachment.");
I might move this exception throwing outside of the setter to make the code more readable.

2023-06-19 11:53 UTC, lnardai commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/resource/volume/AwsVolumeResourceBuilder.java
> +    private List<Volume> rebuildVolumes(AuthenticatedContext auth, VolumeSetAttributes volumeSetAttributes,
Can we notify the customer that some of the disks were missing and have been recreated?

2023-07-03 10:09 UTC, lnardai commented
@bbihari  Please resolve the conflicts.

2023-07-05 06:34 UTC, keyki commented
Closing the PR, please re-open if it's still relevant.

2023-07-05 06:34 UTC, closed without merging