CB-21142 in FedRAMP environment all datahub should use external datab…
hortonworks/cloudbreak pull request #14431
Opened 2023-03-08 12:46 UTC by doktoric

…ase. For dicrease the cost in qa tenants I added a backdoor for QA team.

See detailed description in the commit message.

2023-03-09 08:55 UTC, bergerdenes requested changes

2023-03-09 08:55 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/fedramp/FedRAMPModificationService.java
> +                request.setExternalDatabase(distroXDatabaseRequest);
First I would check if the DistroX request has a DistroXDatabase request and create a new one only if missing.
In the case when it exists I would just update the AvailabiltyType

2023-03-09 08:55 UTC, bergerdenes commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/fedramp/FedRAMPModificationService.java
> +public class FedRAMPModificationService {
The naming should be `FedRampMofificationService` (i.e., not using full caps even within abbreviations)
Or `Fedramp...`, just make sure to be consistent with Entitlement service's check method name

2023-03-09 08:55 UTC, bergerdenes commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/EntitlementService.java
> +    public boolean isFedrampExternalDatabaseForceDisabled(String accountId) {
FedRamp vs Fedramp

2023-03-09 19:04 UTC, lajosrodek commented on auth-connector/src/main/java/com/sequenceiq/cloudbreak/auth/altus/model/Entitlement.java
> +    CDP_FEDRAMP_EXTERNAL_DATABASE_FORCE_DISABLED
Nit: What about mock-thunderhead changes? For sake of local development, the entitlement shall be granted by default I think.

2023-03-09 19:08 UTC, lajosrodek commented on core/src/main/java/com/sequenceiq/distrox/v1/distrox/service/DistroXService.java
> +    private FedRampModificationService fedRAMPModificationService;
Nit: Variable name casing not in sync with the class name.

2023-03-09 19:14 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
> +    private FedRampModificationService fedRAMPModificationService;
Nit: Variable name casing not in sync with the class name.

2023-03-09 19:17 UTC, lajosrodek commented on core/src/test/java/com/sequenceiq/distrox/v1/distrox/service/DistroXServiceTest.java
>          MockitoAnnotations.initMocks(this);
This will likely not be needed after annotating the test class with `@ExtendWith(MockitoExtension.class)`.

2023-03-10 10:44 UTC, lajosrodek approved these changes
Thanks, LGTM

2023-03-10 16:44 UTC, merged