CB-19604 E2E Marketplace image tests for datalake and datahub
hortonworks/cloudbreak pull request #14446
Opened 2023-03-09 08:27 UTC by daszabo

See detailed description in the commit message.

2023-03-10 11:17 UTC, aszegedi requested changes

2023-03-10 11:17 UTC, aszegedi commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxMarketplaceImageTests.java
> +                .withUrl("https://gist.githubusercontent.com/daszabo/6b53c1a413d9b6cb847b9ad786e7bbf5/raw/0edb66302b7f485527b3bc03fdff1d68695d354c/" +
Could you replace this GIST reference with a versioned one in this project at https://github.com/hortonworks/cloudbreak/tree/master/integration-test/src/main/resources. Please create a new sub folder then move the `v3-marketplace-image-catalog.json` to here, like we have for blueprints.

2023-03-10 11:20 UTC, aszegedi commented
Please add commit message for your commit with a brief description about the goal and reason of this change. This should be appeared as the PR description too.

2023-03-10 11:33 UTC, gergopapi2 requested changes
Let's find out locally, how come the POST method works for you and does not for me, and vica versa the PUT works for me and not for you. Maybe there is a difference in how marketplace images are published now? Let's put this PR on hold until then.

2023-03-10 11:33 UTC, gergopapi2 commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/marketplace/AzureImageTermsSignerService.java
> +            AzureImageTerms responseImageTerms = azureRestOperationsService.httpPost(signUri, null, AzureImageTerms.class, token);
I tried locally and for me the POST endpoint with the above URL gives an error:
`Bad Request({"error":{"code":"BadRequest","message":"You must accept the legal terms through the Azure portal (http://go.microsoft.com/fwlink/?LinkId=534873). Correlation Id: '1bdf2fe2-542a-47ce-9a14-80abe382499d'."}})`

I also remember that I had to do it over the PUT endpoint. I quickly tested it via the command `az rest` and agreement accept and decline did work.

2023-03-10 11:33 UTC, gergopapi2 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/distrox/DistroXMarketplaceImageTests.java
> +                .withUrl("https://gist.githubusercontent.com/daszabo/6b53c1a413d9b6cb847b9ad786e7bbf5/raw/0edb66302b7f485527b3bc03fdff1d68695d354c/" +
Would be better to have an official marketplace image catalog, up in s3, next to the test image catalog.

2023-03-10 11:33 UTC, gergopapi2 commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/testcase/e2e/sdx/SdxMarketplaceImageTests.java
> +    public void testSDXWithMarketplaceImageCanBeCreatedSuccessfully(TestContext testContext) {
Would this mean a brand new test would be introduced for marketplace testing? 
Just from pure test cost savings, would it be possible to alter one of our existing tests, to use marketplace? Or, change one of the azure suits (api or longrunning) to use marketplace images.

2023-04-14 08:06 UTC, aszegedi approved these changes

2023-04-17 10:01 UTC, daszabo commented
> Let's find out locally, how come the POST method works for you and does not for me, and vica versa the PUT works for me and not for you. Maybe there is a difference in how marketplace images are published now? Let's put this PR on hold until then.

Fixed the signing request based on your draft PR

2023-04-19 07:20 UTC, merged