CB-12577 Azure Marketplace image automatic terms acceptance setting
hortonworks/cloudbreak pull request #14512
Opened 2023-03-22 08:54 UTC by daszabo

See detailed description in the commit message.

2023-03-29 17:37 UTC, pdarvasi requested changes

2023-03-29 17:37 UTC, pdarvasi commented on environment/src/main/java/com/sequenceiq/environment/marketplace/domain/Terms.java
> +public class Terms implements Serializable, AuthResource, AccountIdAwareResource {
would it make sense to store the last update date for later auditing purposes?

2023-04-03 07:05 UTC, daszabo commented on environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/endpoint/AzureMarketplaceTermsEndpoint.java
> +    AzureMarketplaceTermsResponse get();
Based on other examples in the code like the endpoints responsible for creating tags, there is one endpoint for the UI and one for internal actors or requests between services

2023-04-04 09:28 UTC, pdarvasi commented on environment-api/src/main/java/com/sequenceiq/environment/api/v1/marketplace/endpoint/AzureMarketplaceTermsEndpoint.java
> +    @ApiOperation(value = MarketplaceDescription.GET, produces = MediaType.APPLICATION_JSON, notes = TagDescription.GET_NOTES,
typo: `TagDescription.GET_NOTES`

2023-04-04 09:28 UTC, pdarvasi approved these changes

2023-04-05 16:10 UTC, merged