CB-21196: Optimize FreeIPA StackRepository.findByAccountId query
hortonworks/cloudbreak pull request #14520
Opened 2023-03-22 16:24 UTC by tiborpopovics

In this commit, I introduced some changes to improve the performance of the StackRepository.findByAccountId query.

- I've created a new query for the PasswordService because it does not necessary to retrieve the whole Stack table.
- I've removed the joining of the instanceGroups and instanceMetaData table from the original query.
- Removed some unused queries from the StackRepository

2023-03-22 16:28 UTC, lajosrodek commented on freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
> +            //"LEFT JOIN FETCH ig.instanceMetaData " +
Perhaps better remove these altogether. :wink:

2023-03-22 16:29 UTC, tiborpopovics commented on freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
> +            //"LEFT JOIN FETCH ig.instanceMetaData " +
Ahh... Thanks!

2023-03-23 08:46 UTC, lacikaaa requested changes

2023-03-23 08:46 UTC, lacikaaa commented on freeipa/src/main/java/com/sequenceiq/freeipa/repository/StackRepository.java
please make sure every `ResourceBasicView` has the env crn too

2023-03-24 11:11 UTC, lacikaaa approved these changes

2023-03-24 15:54 UTC, merged