CDPD-43642, increase CM memory threshold on all host
hortonworks/cloudbreak pull request #14577
Opened 2023-03-30 13:25 UTC by RokolyA94

CDPD-43642, increase CM memory threshold on all hosts to 95% in the case of Medium duty Datalake and the EDL.

Our current datalakes have warnings about the memory settings. The default CM memory threshold is 80%. This means if we allocate more than 80% of the available resource. We cannot handle the basic datalake resource. Therefore we pump up the memory threshold to 95%.

2023-04-12 04:29 UTC, kkalvagadda1 commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
> +            LOGGER.warn("Couldn't start Cloudera Manager services", e);
Please fix the log message.

2023-04-12 04:32 UTC, kkalvagadda1 commented on core/src/main/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandler.java
> +//            }
Looks like stale change. Is this change needed?

2023-04-13 18:01 UTC, kkalvagadda1 requested changes

2023-04-17 15:39 UTC, kkalvagadda1 approved these changes
Looks good.

2023-04-18 11:29 UTC, kkalvagadda1 approved these changes
The code change looks good.

2023-04-25 00:43 UTC, grace303303 commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
> +            LOGGER.warn("Couldn't Configure CM memory setttings", e);
Here is a typo `setttings `

2023-04-25 00:48 UTC, grace303303 commented on core/src/test/java/com/sequenceiq/cloudbreak/reactor/handler/cluster/ClusterStartHandlerTest.java
> +    private ClusterServicesRestartService clusterServicesRestartService;
It seems this is not used in the test?

2023-04-25 00:48 UTC, grace303303 requested changes
Two very minor change requests. Other than that this looks great. Thank you!

2023-04-25 17:56 UTC, grace303303 approved these changes

2023-04-26 06:09 UTC, doktoric commented
Why is this not an OPSAPS issue?

2023-04-26 06:31 UTC, lnardai commented
Might worth to have a chat with @foldik as we are working in the same domain, please see:
https://jira.cloudera.com/browse/CB-21447

2023-04-26 07:21 UTC, foldik approved these changes
LGTM

2023-04-26 08:53 UTC, merged

2023-06-19 09:04 UTC, horadla23 commented on sdx-connector/src/main/java/com/sequenceiq/cloudbreak/saas/sdx/SaasSdxService.java
> +    public SdxClusterResponse getSdxClusterByEnvironmentCrn(String environmentCrn) {
paas related API response is SaasSdxService, definitely not good, can you create a followup jira @RokolyA94 to fix this?