CB-20104 Handle AWS InsufficientInstanceCapacityException during stop…
hortonworks/cloudbreak pull request #14675
Opened 2023-04-12 16:29 UTC by aakashshankar

…start upscale

See detailed description in the commit message.

2023-05-03 08:27 UTC, lajosrodek requested changes

2023-05-03 08:27 UTC, lajosrodek commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnector.java
Please cover the new logic with UT.

2023-05-03 08:27 UTC, lajosrodek commented on cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java
Please cover the new logic with UT.

2023-05-03 08:27 UTC, lajosrodek commented on cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java
> +            LOGGER.error("Insufficient capacity on the cloud provider while attempting to start instances. Trying to fetch statuses of nodes");
Please also log `ice`.

2023-05-05 07:16 UTC, aakashshankar commented on cloud-aws-common/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/common/AwsInstanceConnector.java
Added UT

2023-05-05 07:16 UTC, aakashshankar commented on cloud-reactor/src/main/java/com/sequenceiq/cloudbreak/cloud/handler/StopStartUpscaleStartInstancesHandler.java
> +            LOGGER.error("Insufficient capacity on the cloud provider while attempting to start instances. Trying to fetch statuses of nodes");
Logged `ice`

2023-05-05 08:38 UTC, lajosrodek approved these changes
Thanks, LGTM

2023-05-05 10:05 UTC, merged