CB-20093 Add argument runAutoConfig for applyHostTemplate call to CM
hortonworks/cloudbreak pull request #14706
Opened 2023-04-17 20:15 UTC by doktoric

See detailed description in the commit message.

2023-04-20 18:47 UTC, doktoric commented
resetest this please

2023-04-27 09:29 UTC, lajosrodek requested changes

2023-04-27 09:29 UTC, lajosrodek commented on cluster-cm/src/main/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationService.java
> +            LOGGER.warn("Client init failed for V45 client!");
Nit: `V45` -> `V52`

2023-04-27 09:29 UTC, lajosrodek commented on cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
Could you please add a test case for the new scenario?

2023-05-02 09:28 UTC, lajosrodek commented on cluster-cm/src/test/java/com/sequenceiq/cloudbreak/cm/ClouderaManagerModificationServiceTest.java
Still pending. :smile:

2023-05-05 08:51 UTC, doktoric commented
retest this please

2023-05-05 12:03 UTC, merged