CB-21803: Fixed failing enterprise e2e tests which require specific 7.2.17 image catalog.
hortonworks/cloudbreak pull request #14854
Opened 2023-05-09 04:03 UTC by sxxgrc

Jira: https://jira.cloudera.com/browse/CB-21803

The tests were failing since the default QE image catalog does not have 7.2.17 on it. This change attempts to fix this by specifying a specific image catalog URL to be used for the SDX cluster which does have 7.2.17.

2023-05-10 03:36 UTC, sxxgrc commented
I do not know why the unit test process is failing I see no errors.

2023-05-10 11:17 UTC, aszegedi approved these changes

2023-05-11 09:02 UTC, biharitomi requested changes

2023-05-11 17:03 UTC, aszegedi approved these changes

2023-05-11 18:14 UTC, biharitomi approved these changes

2023-05-17 19:36 UTC, merged