CB-21760 Adding kafka broker endpoints to api endpoints. Also fixed a…
hortonworks/cloudbreak pull request #14878
Opened 2023-05-11 07:40 UTC by doktoric

… problem because we did not filtered out endpoint based on datalakes and datahubs. In case of stopped clusters some of the endpoint was empty which is also a bug so I fixed that as well.

See detailed description in the commit message.

2023-05-15 10:02 UTC, biharitomi requested changes

2023-05-15 10:02 UTC, biharitomi commented on core-api/src/main/java/com/sequenceiq/cloudbreak/api/service/ExposedServiceCollector.java
> +    public Set<String> getFullServiceListByNameBasedOnList(Collection<String> services, Optional<String> bpVersion) {
Could you please rename it?
`getFullServiceListWithDefaultValues` would be more understandable here.
Don't we need to remove the `ALL` service type after adding all Knox exposed service name the services as default contains it?

2023-05-15 10:54 UTC, bergerdenes approved these changes

2023-05-15 14:47 UTC, biharitomi approved these changes

2023-05-16 14:30 UTC, doktoric commented
retest this please

2023-05-17 19:38 UTC, merged