CB-21834 Azure datalake upgrade E2E test fails on master with bad request from Azure related to image creation
hortonworks/cloudbreak pull request #14924
Opened 2023-05-21 21:16 UTC by schfeca75

CB-21834 Azure datalake upgrade E2E test fails on master with bad request from Azure related to image creation

In case of marketplace -> vhd upgrade without vm replacement, the original marketplace image is stored in instance metadata, but the image in stack will be replaced with the new vhd one.
The fix: In AzureStackViewProvider.getCustomImageNamePerInstance() we will check if the image is marketplace on instance level when we collect instance image names not boased on image name stored in stack.

The fix was tested with marketplace -> vhd upgrade without vm replacement, after it vertical scale, repair, os upgrade is worked, na azure exception has thrown.

2023-05-22 18:03 UTC, pdarvasi requested changes

2023-05-22 18:03 UTC, pdarvasi commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProvider.java
> +                    customImageNamePerInstance.put(instance.getInstanceId(), imageCustomName);
could you pls add an extra log here?

2023-05-22 18:03 UTC, pdarvasi commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java
> +    public boolean isVhdImageFormat(String imageUri) {
this could be private

2023-05-23 09:33 UTC, pdarvasi approved these changes

2023-05-23 13:22 UTC, lajosrodek requested changes
Two small asks.

2023-05-23 13:22 UTC, lajosrodek commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureStackViewProvider.java
> +                    LOGGER.debug("ImageId {} is empty or is a marketplace image identifier for instance {}, custom image name colletion is not needed.",
Nit: `colletion` -> `collection`

2023-05-23 13:22 UTC, lajosrodek commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/validator/AzureImageFormatValidator.java
> +    public boolean isMarketplaceImageFormat(String imageUri) {
Please cover both methods with UT.

2023-05-23 14:43 UTC, biharitomi approved these changes

2023-05-23 15:37 UTC, lajosrodek approved these changes
Thanks, LGTM

2023-05-23 17:33 UTC, merged