CB-8735 set CDP_ENV to PUBLIC_CLOUD when CM server starts rather than…
hortonworks/cloudbreak pull request #8975
Opened 2020-09-10 10:06 UTC by keyki

… with API

Previously, we set this env var with API call after them CM server has started.
However, CM team would like to rely on this env var during CM startup so they can
initialise the application accordingly.

2020-09-10 13:19 UTC, schfeca75 approved these changes

2020-09-10 13:23 UTC, lacikaaa approved these changes

2020-09-11 05:57 UTC, keyki commented
@lacikaaa I had to change the implementation to use `-env` as CM server arg rather than the settings file. Please re-review the changes.

2020-09-11 06:56 UTC, lacikaaa requested changes

2020-09-11 06:56 UTC, lacikaaa commented on orchestrator-salt/src/main/resources/salt/salt/cloudera/manager/init.sls
> +    - unless: grep "CMF_SERVER_ARGS=\"-i /etc/cloudera-scm-server/cm.settings\"" /etc/default/cloudera-scm-server
this won't match `"-i /etc/cloudera-scm-server/cm.settings -env PUBLIC_CLOUD"`

2020-09-11 07:04 UTC, lacikaaa approved these changes

2020-09-11 07:23 UTC, lacikaaa approved these changes

2020-09-11 07:58 UTC, merged