CB-8809 verify that AWS credentials' role is assumable without external Id
hortonworks/cloudbreak pull request #9042
Opened 2020-09-18 13:07 UTC by biharitomi

See detailed description in the commit message.

2020-09-18 19:53 UTC, doktoric commented on cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
> +                String message = String.format("CDP Control Pane is able to perform 'sts:AssumeRole' on '%s' role without external id. " +
I am not sure but should we somehow show what is the external id which is missing ? I guess not but lets check

2020-09-18 19:54 UTC, doktoric commented on cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
> +                            "CDP Control Pane is not authorized to perform sts:AssumeRole on '%s' role without external Id.", roleArn);
I think here the problem is not the missing external id right ?

2020-09-18 19:55 UTC, doktoric requested changes
we should also mention this in mow-dev channel

2020-09-21 08:08 UTC, biharitomi commented on cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/AwsCredentialConnector.java
> +                            "CDP Control Pane is not authorized to perform sts:AssumeRole on '%s' role without external Id.", roleArn);
That's a happy path and only a log is called to leave a sign about it.

2020-09-21 15:05 UTC, doktoric approved these changes

2020-09-21 15:05 UTC, merged