CB-8636 move cloud related validation into a flow step which improves…
hortonworks/cloudbreak pull request #9046
Opened 2020-09-19 20:29 UTC by doktoric

… the request response times. Moved group validation, template validation, parameters like encryption keys, DL and ENV validation. Also moved kerberos config generation under the kerberos validation.

See detailed description in the commit message.

2020-09-28 05:29 UTC, topolyai5 requested changes

2020-09-28 05:29 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/StackCreatorService.java
> +        // TODO grpc call
what kind of grpc call?

2020-09-28 05:29 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/InstanceTemplateValidator.java
>              resultBuilder.error("Template request cannot be null in the instance group request.");
Maybe this validation runs in the flow

2020-09-28 05:29 UTC, topolyai5 commented on core/src/test/java/com/sequenceiq/cloudbreak/controller/validation/stack/StackV4RequestValidatorTest.java
>  public class StackV4RequestValidatorTest extends StackRequestValidatorTestBase {
Please rename the test class, and check all the test names in the PR

2020-09-28 05:29 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/core/flow2/validate/cloud/CloudConfigValidationActions.java
> +    private StackValidator stackRequestValidator;
please rename the field

2020-09-28 05:29 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/service/blueprint/BlueprintService.java
> +        //updateDefaultBlueprintCollection(workspace);
please remove the slash or delete the code

2020-09-28 05:29 UTC, topolyai5 commented on core/src/test/java/com/sequenceiq/cloudbreak/controller/StackCreatorServiceTest.java
> +        //when(validationResult.getState()).thenReturn(State.VALID);
remove comment section

2020-09-28 06:31 UTC, doktoric commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/InstanceTemplateValidator.java
>              resultBuilder.error("Template request cannot be null in the instance group request.");
there is no provider related validation

2020-10-02 16:23 UTC, topolyai5 commented on core/src/main/java/com/sequenceiq/cloudbreak/controller/validation/template/InstanceTemplateValidator.java
>              resultBuilder.error("Template request cannot be null in the instance group request.");
I mean `request` in the message

2020-10-02 16:25 UTC, topolyai5 commented on freeipa/src/main/java/com/sequenceiq/freeipa/converter/stack/CreateFreeIpaRequestToStackConverter.java
> +            throw new BadRequestException("Failed to convert dynamic tags." + ignored.getMessage());
it will conflict with my change

2020-10-07 06:56 UTC, topolyai5 approved these changes

2020-10-07 06:57 UTC, merged