CB-8681 CB-3257 Adding GCS support for telemetry Logging
hortonworks/cloudbreak pull request #9057
Opened 2020-09-22 06:45 UTC by cegganesh84

1. This is required for creating CDP cli for environment creation.
2. The actual logging is yet to be done.

./gradlew build

2020-09-22 14:53 UTC, doktoric commented on freeipa/src/main/java/com/sequenceiq/freeipa/converter/telemetry/TelemetryConverter.java
> +            } else if (loggingRequest.getGcs() != null) {
the unit test part should be also added

2020-09-22 14:53 UTC, doktoric commented on datalake/src/main/java/com/sequenceiq/datalake/service/sdx/CloudStorageManifester.java
> +            } else if (logging.getGcs() != null) {
unit test will be required probably

2020-09-22 14:53 UTC, doktoric requested changes
comments were added

2020-09-22 22:43 UTC, cegganesh84 commented
Thanks, @doktoric, added the unit test, and was able to fix a couple of bugs I introduced!

2020-09-23 06:41 UTC, doktoric approved these changes

2020-09-23 11:15 UTC, merged