CB-8137: Fix FreeIPA status for deleted, stopped, available, unreac...
hortonworks/cloudbreak pull request #9065
Opened 2020-09-23 02:38 UTC by jamisonbennett

...hable, and unhealthy

Fixed FreeIPA status for HA clusters.
 * Stopped + Running = Unhealthy
 * Stopped + Terminated = Unhealthy (It may temporarily be unreachable)
 * Unreachable + Unreachable = Unreachable
 * Unreahable + Running = Unhealthy
 * Running + Deleted = Unhealthy

This was tested with unit tests and also manually with a local
deployment of cloudbreak.

See detailed description in the commit message.

2020-09-23 08:11 UTC, lacikaaa requested changes

2020-09-23 08:11 UTC, lacikaaa commented on freeipa/src/main/java/com/sequenceiq/freeipa/sync/StackStatusCheckerJob.java
> +                    // Exclude terminated but include deleted
`InstanceMetaDataService` is not used anymore, please remove

2020-09-23 09:13 UTC, Bajzathd commented on freeipa/src/test/java/com/sequenceiq/freeipa/sync/StackStatusTest.java
> +                createCloudVmInstanceStatus(INSTANCE_1, com.sequenceiq.cloudbreak.cloud.model.InstanceStatus.STOPPED)
I guess this should be INSTANCE_2. Same applies to someStoppped

2020-09-23 22:52 UTC, jamisonbennett commented on freeipa/src/main/java/com/sequenceiq/freeipa/sync/FreeipaChecker.java
> +            Boolean result = false;
I didn't notice that the result isn't even ever read. So I got rid of it and that helped clean up more of the logic.

Thanks.

2020-09-24 06:28 UTC, lacikaaa approved these changes

2020-09-24 08:33 UTC, Bajzathd approved these changes

2020-09-24 08:44 UTC, merged