CDPCP-3122. Bulk user sync state retrieval fails over to default retr…
hortonworks/cloudbreak pull request #9160
Opened 2020-10-07 02:59 UTC by handavid

…ieval

The UMS may protect itself by rejecting bulk computation requests for
large tenants. There is also a grpc timeout built into the system of
one minute after which the transport will be closed and the request
will fail.

In these cases, the ums user sync state model retrieval
should failover to the default approach.

See detailed description in the commit message.

2020-10-07 08:40 UTC, horadla23 commented
what "default approach" means? Will it have performance impact for example on mow-dev? If yes, then we should target this change to master to fully test it .

2020-10-07 16:26 UTC, handavid commented
Our concern is that, if each request takes more than a minute, then running multiple simultaneous requests could consume all of the UMS' resources. We want the ability for the UMS to protect itself without needing to revisit the FMS code. E.g., the UMS could implement a limit on the number of bulk requests it accepts at a time or reject bulk requests for cases where we suspect we would exceed the 1 minute threshold without breaking user sync in the FMS.

We've identified a number of inefficiencies in the bulk calculation in the UMS. This is because we started with a direct translation of the work that the FMS was doing. See https://jira.cloudera.com/browse/CDPCP-3078 for more details on areas of improvement on the UMS side. Essentially there are some data retrieval operation that are still performed on a per-actor basis that can be replaced. Our intention is to target and test this feature against 2000 actors.

In the meantime, we discovered (from https://jira.cloudera.com/browse/CDPCP-2986) that there are an excessive number of actors in mow-dev due to orphaned internal machine users (some 8000+ actors total) which far exceeded our expectations. We are looking at ways to pull back or modify that change as well while we understand where all the orphan internal machine users are coming from.

cc: @giladwolff @mdzz

2020-10-08 06:52 UTC, lacikaaa approved these changes
I'm ok with this change, but raven team is the 2.31 branch guardian, they have to decide if they let it in or you have to move this to master.

2020-10-08 06:53 UTC, lacikaaa commented
retest this please

2020-10-08 06:57 UTC, horadla23 commented
if current behaviour on 2.31 does not cause any issue on PROD, then I would put this change into master to have time to test it properly

2020-10-08 07:09 UTC, horadla23 requested changes
Same here: I have checked related jira ticket and it seems for me that this improvement will have effect mostly on mow-dev, so I wouldn't put this into the upcoming CB release, I think master will branched soon to 2.32 and it will reach mow-dev soon, so please rebase this to master and change PR accordingly

2020-10-08 17:48 UTC, horadla23 commented
@mdzz has user sync changed somehow in 2.31 ? are there such amount of machine users in prod which can affect customers negatively compared to 2.29 ? My concern is almost same here as in https://github.com/hortonworks/cloudbreak/pull/9166 that 2.31 release coming soon and I cannot tell if this change won't cause any issue in prod. It would be better to have time to test and experience this change in mow-dev before release to avoid any unexpected issues in prod.

2020-10-09 20:37 UTC, handavid commented
retest this please

2020-10-19 15:58 UTC, handavid commented
@horadla23 I retargeted this to master. can you merge if acceptable?

2020-10-19 16:12 UTC, horadla23 approved these changes

2020-10-19 16:12 UTC, merged