CB-9212: Fix findVirtualMachineCustomImage to use the image name instead of the whole URL of the image.
hortonworks/cloudbreak pull request #9176
Opened 2020-10-08 12:27 UTC by tiborpopovics

2020-10-08 13:36 UTC, keyki requested changes
According to my testing, it does not solve the problem.

2020-10-09 13:17 UTC, gergopapi2 requested changes

2020-10-09 13:17 UTC, gergopapi2 commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/image/AzureImageSetupService.java
> +    private String getImageName(String fromVhdUri, String region) {
This piece is present already in class AzureImageService. It might make sense to extract them.

2020-10-12 15:13 UTC, keyki approved these changes

2020-10-12 15:15 UTC, merged