CB-9227 - unable to get cluster definition on a stopped environment
hortonworks/cloudbreak pull request #9193
Opened 2020-10-10 09:46 UTC by gregito

CB-9227 - unable to get cluster definition on a stopped environment

2020-10-12 08:10 UTC, akanto requested changes
Please ensure that we have proper test coverage for this error.

2020-10-12 22:21 UTC, doktoric commented
and please add some details to the commit message

2020-10-14 20:07 UTC, doktoric commented
please check the integration test job

2020-10-19 08:07 UTC, doktoric approved these changes

2020-10-19 08:07 UTC, merged