Distx 534 use v1 committer for spark
hortonworks/cloudbreak pull request #9204
Opened 2020-10-12 15:11 UTC by amitagarwal06

DISTX-534 As per TSB-437, FileOutputCommitter algorithm v2 may result into
bad output data. Hence it has been advised to go back to v1 version.
This commit makes following config changes in 710, 720, 721, 722, 723
DE, DE HA & Spark3 templates so that v1 algorithm is configured ootb
in DH clusters :

  fs.s3a.committer.name=directory
  mapreduce.fileoutputcommitter.algorithm.version=1
  spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version=1

Testing done :
Have created a DE cluster using a modified 7.2.2 template that includes above mentioned config changes. Cluster creation was successful on AWS using m5d.2xl instance types.

2020-10-12 15:40 UTC, amitagarwal06 commented
@keyki @lnardai Please merge it in CB-2.31.0 as well as master once its reviewed and all the tests pass.

2020-10-12 17:08 UTC, amitagarwal06 commented
@steveloughran Pls review and approve it.

2020-10-13 08:20 UTC, horadla23 commented
@amitagarwal06 is it needed into 2.31? Is there any issue with current solution? If not, please change this PR's target to master, since we are about to release 2.31. Merging changes like this can cause major delay in release process, so if this is required, we can still add this later in 2.31 and release it using hotfix process.

2020-10-13 08:21 UTC, horadla23 requested changes
@amitagarwal06 is it needed into 2.31? Is there any issue with current solution? If not, please change this PR's target to master, since we are about to release 2.31. Merging changes like this can cause major delay in release process, so if this is required, we can still add this later in 2.31 and release it using hotfix process.

2020-10-13 11:38 UTC, amitagarwal06 commented
@horadla23 As mentioned in the PR comment, there is data correctness issue in FileOutputCommitter algorithm version V2 which effects customers using Spark (on previous version of clusters too). Hence its required to configure a prior version V1 of the algorithm. It is very much needed as per TSB (https://jira.cloudera.com/browse/TSB-437), that is why I have been asked to put this in CB-2.31.0 as well as master branches.

cc @shwethags can also add her thoughts.

2020-10-13 12:44 UTC, horadla23 commented
And do we know about any customer issue caused by using v2?
I'm ok with this if it impacts customers, but without it, it is little bit risky to merge this into 2.31, since it affects all DE templates and this requires retesting on AWS and Azure all DE templates enabled in 2.31. But after proper test it can go into 2.31 and can be released via hotfix process.

2020-10-13 14:54 UTC, shwethags approved these changes

2020-10-13 14:56 UTC, shwethags commented
I will coordinate with Prasad for testing. Can we get this in CB 2.31 as its for the TSB issue

2020-10-13 15:56 UTC, horadla23 approved these changes
we decided with team that this can go in but please test it with all possible runtime version on aws and azure too

2020-10-13 15:56 UTC, merged