CB-8664: Use new FreeIPA health checks for instance status
hortonworks/cloudbreak pull request #9210
Opened 2020-10-12 22:18 UTC by jamisonbennett

Use the new FreeIPA health checks for the instance status. This is
used for the periodic polling of the status, the on demand status for
the health API, and for the internal repair status.

Unit tests were added and this was tested manually using a local
deployment of cloudbreak.

See detailed description in the commit message.

2020-10-13 07:23 UTC, doktoric commented on freeipa/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClientFactory.java
> +            throw new FreeIpaClientException("Unable to create clietn for freeipa health checks", e);
clietn -> client

2020-10-13 07:24 UTC, doktoric commented on freeipa-client/src/main/java/com/sequenceiq/freeipa/client/FreeIpaHealthCheckClient.java
> +            String message = String.format("Invoke FreeIpa health check failed: %s", throwable.getLocalizedMessage());
FreeIpa or FreeIPA just asking because in this pr both word were used.

2020-10-14 08:03 UTC, lacikaaa requested changes
Have you tested it with FreeIPA started with an older version?

2020-10-14 19:03 UTC, jamisonbennett commented on freeipa-client/src/main/java/com/sequenceiq/freeipa/client/healthcheckmodel/CheckResult.java
> +                .collect(Collectors.joining(","));
Thanks, you are correct.

2020-10-14 19:06 UTC, jamisonbennett commented on freeipa/src/main/java/com/sequenceiq/freeipa/service/stack/FreeIpaHealthDetailsService.java
> +                .allMatch(isEqual(Response.Status.Family.SUCCESSFUL));
Good point. We really shouldn't have 0 RPCs for any health check, but it's better to be safe.

2020-10-14 19:26 UTC, jamisonbennett commented
> Have you tested it with FreeIPA started with an older version?
Yes and the old version uses the old health check since HealthCheckAvailabilityChecker.isCdpFreeIpaHeathAgentAvailable() checks if both the entitlement is enabled and the stack version is after 2.31.

2020-10-19 06:51 UTC, lacikaaa approved these changes

2020-10-21 15:10 UTC, merged