CB-9051 [AuthZ] Improve error pop up message for non entitled users
hortonworks/cloudbreak pull request #9224
Opened 2020-10-14 17:41 UTC by bbihari

See detailed description in the commit message.

2020-10-29 11:52 UTC, horadla23 requested changes
Please add the description of the PR to the commit message. Also it seems you need to rebase this branch (swagger check failed because of that possibly).

2020-10-29 11:56 UTC, horadla23 commented
This solution can extract resource type from CRN but still not showing the name of the resource in the message, as I see this is part of the ticket. Is this intentional?

2020-10-29 12:05 UTC, bbihari commented
I think it's too expensive

2020-10-30 10:29 UTC, horadla23 approved these changes

2020-10-30 15:20 UTC, merged