CB-9306 - Env service should create private DNS zones - various follow-ups
hortonworks/cloudbreak pull request #9274
Opened 2020-10-22 14:35 UTC by pdarvasi

This contains 2 commits deliberately, to be able to revert the first separately if needed:

First contains: 
- upgrade ARM template API versions to the latest

Second contains:
- validation on already existing network link
- externalize poller values for all pollers like in AzureDnsZoneCreationPoller
- refactor + unit test coverage for AzureDnsZoneService
- DataAccessException comment
- the EndpointType enum refactor

2020-11-09 09:12 UTC, lacikaaa requested changes

2020-11-09 09:12 UTC, lacikaaa commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
> +        return null;
instead of returning `null` please consider a different way, like using `Optional`

2020-11-09 09:12 UTC, lacikaaa commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/client/AzureClient.java
> +                return validationMessage;
please avoid in the middle return

2020-11-09 18:13 UTC, pdarvasi commented on cloud-azure/src/main/java/com/sequenceiq/cloudbreak/cloud/azure/AzureDnsZoneService.java
>          } else if (!dnsZonesDeployed) {
it contains only service calls, debug lines and if-s. I could extract the second if-else section, but I do not want to as it reduces readability.

2020-11-10 10:53 UTC, lacikaaa approved these changes

2020-11-10 10:54 UTC, merged