CB-9449 if AWS returns that DBInstance does not exsist, then we shall…
hortonworks/cloudbreak pull request #9279
Opened 2020-10-23 09:12 UTC by akanto

… consider this as the termination protection is not enabled.

Before this change if somebody went to AWS console and removed the protection and deleted the DB instance, that caused Environment/SDX/DH delete failures, since Redbeams would just thorw a CloudConnectorException for delete call and Environment/SDX/DH deletion stuck forever. After this change Redbeams realises that DB does not exsist anymore and it just proceeds and Environment/SDX/DH deletion will be successful.

I have intentionally changed the unit test as well, to make sure that it reflects the the expected behaviour.

See detailed description in the commit message.

2020-10-26 11:43 UTC, gergopapi2 requested changes
LGTM, just some typos:
- commit message: thorw, exsist
- typos in log-lines

2020-10-26 11:43 UTC, gergopapi2 commented on cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java
> +            LOGGER.debug("DB Instance does not exists: {}", ex.getMessage());
typo: exists => exist

2020-10-26 11:55 UTC, akanto commented on cloud-aws/src/main/java/com/sequenceiq/cloudbreak/cloud/aws/connector/resource/AwsRdsStatusLookupService.java
> +            LOGGER.debug("DB Instance does not exists: {}", ex.getMessage());
Fixed

2020-10-27 06:56 UTC, gergopapi2 approved these changes

2020-10-27 06:57 UTC, merged