CB-9362 on aws rds postgres version is 10.14 instead of 10.6
hortonworks/cloudbreak pull request #9285
Opened 2020-10-26 09:35 UTC by afarsang

CB-9362 on aws rds postgres version is 10.14 instead of 10.6

2020-10-26 13:02 UTC, akanto requested changes
Embedded DB should default to the same version

2020-10-26 15:42 UTC, pdarvasi commented
> Embedded DB should default to the same version

@akanto  Do we specify a minor version for embedded install? https://github.com/hortonworks/cloudbreak-images/blob/76d44d0eddb60b4a64e84545c56bc53fde731a7a/saltstack/base/salt/postgresql/init.sls#L16-L18

2020-10-26 15:44 UTC, pdarvasi approved these changes

2020-10-26 15:46 UTC, akanto commented
You might be right: https://github.com/hortonworks/cloudbreak-images/blob/76d44d0eddb60b4a64e84545c56bc53fde731a7a/saltstack/base/salt/postgresql/yum/postgres10-el7.repo#L3 


And this is updated continuously: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/

2020-10-28 10:45 UTC, akanto approved these changes

2020-10-28 10:45 UTC, merged