ENGESC-5519 Azure D64s_v3 support for Datahub
hortonworks/cloudbreak pull request #9510
Opened 2020-11-24 17:35 UTC by topolyai5

See detailed description in the commit message.

2020-11-24 17:48 UTC, doktoric approved these changes

2020-11-24 20:35 UTC, doktoric requested changes
please add other d64 instances as well

2020-11-25 11:33 UTC, pdarvasi approved these changes

2020-11-25 13:02 UTC, pdarvasi commented
Tried and succeded launching DH with "vmSize": "Standard_D64s_v3"
![image](https://user-images.githubusercontent.com/19725708/100231070-d0023380-2f26-11eb-8d77-006629cf54dc.png)

2020-11-25 13:37 UTC, keyki approved these changes

2020-11-25 15:54 UTC, merged