CB-9879 Allow option to not start datahub cluster automatically when …
hortonworks/cloudbreak pull request #9513
Opened 2020-11-25 07:55 UTC by doktoric

…environment starts up

See detailed description in the commit message.

2020-11-25 12:57 UTC, doktoric commented
retest this please

2020-11-26 09:52 UTC, topolyai5 requested changes
I have a suggestion. If we plan to add the `Recover to before stop` state, much better to use an enum with 2 different states. We can extend the num easily

2020-11-26 15:39 UTC, topolyai5 commented on environment/src/main/java/com/sequenceiq/environment/environment/dto/EnvironmentStartDto.java
> +package com.sequenceiq.environment.environment.dto;
is this a good package? I think it does not relate to telemetruy

2020-11-26 16:41 UTC, topolyai5 commented on common-model/src/main/java/com/sequenceiq/common/api/telemetry/model/DataHubStartAction.java
> +package com.sequenceiq.common.api.telemetry.model;
is this a good package? I think it does not relate to telemetruy

2020-11-30 08:31 UTC, doktoric commented
restest this please

2020-11-30 12:51 UTC, topolyai5 approved these changes

2020-11-30 21:34 UTC, doktoric commented
retest this please

2020-12-01 08:33 UTC, merged