Manually revert CB-7306.
hortonworks/cloudbreak pull request #9708
Opened 2021-01-05 20:31 UTC by brycederriso

* Remove code that added dfs_replication to hdfs service configs
* Add `dfs_replication` values to templates:
  * 7.2.0
  * 7.2.1
  * 7.2.2
  * 7.2.6
  * 7.2.7
  * 7.2.7 HA
  * 7.2.8
  * 7.2.8 HA

See detailed description in the commit message.

2021-01-05 20:46 UTC, orngejaket requested changes

2021-01-05 20:46 UTC, orngejaket commented on core/src/main/resources/defaults/blueprints/7.2.1/cdp-sdx.bp
> +            },
remove extra ,

2021-01-05 20:46 UTC, orngejaket commented
LGTM other than extra comma

2021-01-07 16:45 UTC, brycederriso commented
Tested 7.2.7 Light duty replication value on CBD:
<img width="399" alt="7 2 7 light duty replication" src="https://user-images.githubusercontent.com/14059838/103919270-78361b00-50d5-11eb-89a8-efc8f74c89cf.png">

2021-01-07 16:46 UTC, brycederriso commented
Tested 7.2.7 Medium Duty replication value on CBD:
<img width="399" alt="7 2 7 medium duty replication" src="https://user-images.githubusercontent.com/14059838/103919342-897f2780-50d5-11eb-9d21-3deb27ed85d1.png">

2021-01-07 17:47 UTC, brycederriso commented
Also, tested successful provisioning of:
* 7.2.0
* 7.2.1
* 7.2.2
* 7.2.6

2021-01-07 21:47 UTC, orngejaket approved these changes

2021-01-07 21:48 UTC, merged