adf
hortonworks/cloudbreak pull request #9815
Opened 2021-01-18 20:46 UTC by topolyai5

See detailed description in the commit message.

2021-01-19 08:29 UTC, doktoric approved these changes

2021-01-19 08:35 UTC, bergerdenes commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/MockUriNameParser.java
> +import org.jetbrains.annotations.NotNull;
I think we don't need this.

2021-01-19 08:36 UTC, bergerdenes commented on integration-test/src/main/java/com/sequenceiq/it/cloudbreak/dto/mock/MockUriNameParser.java
> +                    clazz.getName() + " SparkUri annotation url value is empty"
annotation name is MockUri from now on

2021-01-19 10:19 UTC, bergerdenes requested changes
2 minor things

2021-01-20 08:34 UTC, bergerdenes approved these changes

2021-01-20 08:35 UTC, merged